# BERTopic clustering with BGE-M3, UMAP, and HDBSCAN

This notebook mirrors the aggregation pipeline pattern used in the other notebooks, but uses `BAAI/bge-m3` embeddings inside a BERTopic workflow. UMAP reduces the embedding space, HDBSCAN discovers dense event/topic clusters, and `CountVectorizer` uses a trilingual stopword list to suppress boilerplate vocabulary while preserving meaningful Sinhala, Tamil, and English terms.

In [1]:
# Install dependencies when running in a fresh notebook environment.
# Restart the kernel if any package is newly installed.
!pip install -q bertopic sentence-transformers umap-learn hdbscan grapheme
!pip install -U "scipy>=1.15.1"

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 4.6 MB/s eta 0:00:0000:01
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 10.7 MB/s eta 0:00:00
  Building wheel for grapheme (setup.py) ... done
Requirement already satisfied: scipy>=1.15.1 in /usr/local/lib/python3.12/dist-packages (1.16.3)
Collecting scipy>=1.15.1
  Downloading scipy-1.18.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 1.4 MB/s eta 0:00:0000:01
Requirement already satisfied: numpy<2.8,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from scipy>=1.15.1) (2.0.2)
Downloading scipy-1.18.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.3/35.3 MB 52.5 MB/s eta 0:00:00:00:0100:01
Installing collected packages: scipy
  Attempting uninstall: scipy
    Found existing installation: scipy 1.16.3
    Uninstalling scipy-1.16.3:
      Successfully uninstalled scipy-1.16.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ydata-profiling 4.18.4 requires scipy<1.17,>=1.8, but you have scipy 1.18.0 which is incompatible.
Successfully installed scipy-1.18.0

In [2]:
from pathlib import Path
import os
import re
import unicodedata

import numpy as np
import pandas as pd
import grapheme

SEED = 42
np.random.seed(SEED)

NOTEBOOK_DIR = Path.cwd()

# Dataset location
DATA_DIR = Path("/kaggle/input/datasets/uom230425m/aggregation-pipeline-data/data")

# Writable location for results
RESULTS_ROOT = Path("/kaggle/working/results")
RESULTS_DIR = RESULTS_ROOT / "bge_m3_bertopic"

RESULTS_DIR.mkdir(parents=True, exist_ok=True)

print(f"Data dir: {DATA_DIR.resolve()}")
print(f"Results dir: {RESULTS_DIR.resolve()}")

Data dir: /kaggle/input/datasets/uom230425m/aggregation-pipeline-data/data
Results dir: /kaggle/working/results/bge_m3_bertopic

In [3]:
# Load annotator files
df_a = pd.read_csv(DATA_DIR / "a.csv")
df_d = pd.read_csv(DATA_DIR / "d.csv")
df_p = pd.read_csv(DATA_DIR / "p.csv")

for frame in (df_a, df_d, df_p):
    frame.drop(columns=["bias_label"], inplace=True, errors="ignore")

print(df_a.shape, df_d.shape, df_p.shape)

(750, 6) (750, 8) (800, 6)

In [4]:
# Concatenate dataframes and drop duplicate articles by article_id
df = pd.concat([df_a, df_d, df_p], ignore_index=True, sort=False)
df = df.drop_duplicates(subset="article_id", keep="first").reset_index(drop=True)
df.drop(columns=["flags", "Unnamed: 8"], inplace=True, errors="ignore")

print("df shape:", df.shape)
df.head()

df shape: (2000, 6)

,article_id,publisher,url,published_at,title,body_text
0,f92797eb-a338-5886-a45a-66f01292a912,Lanka Deepa,https://www.lankadeepa.lk/news/දන-තර-මර-අහවන-ක...,2025-09-26 00:00:00+00:00,දැන් තෝරු-මෝරු අහුවෙන කාලේ,දැන් තෝරු-මෝරු අහුවෙන කාලේ\n\nදැන් හාල්මැස්සො ...
1,5c7946aa-a810-59e2-a126-ff58347aad21,BBC Sinhala,https://www.bbc.com/sinhala/articles/c0vy04qd14yo,2024-01-17 00:00:00+00:00,අවුරුදු 67යි. ඇස් දෙකම පේන්නේ නෑ. මම පොල් කඩනවා',අවුරුදු 67යි. ඇස් දෙකම පේන්නේ නෑ. මම පොල් කඩනව...
2,6fc575d1-2be5-5d49-be20-c846617bdacd,Ada,https://www.ada.lk/breaking_news/පිදුරංගල-ගිය-...,2026-02-17 00:00:00+00:00,පිදුරංගල ගිය විදේශිකයා වන අලි ප්‍රහාරයෙන් මරුට,පිදුරංගල ගිය විදේශිකයා වන අලි ප්‍රහාරයෙන් මරුට...
3,47965836-064f-530a-a34d-02f6898fb94a,Ada Derana Sinhala,http://sinhala.adaderana.lk/news/194266,2024-03-07 00:00:00+00:00,හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් ගැ...,හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් ගැ...
4,132990f7-a4f4-54ba-8b12-b469d9803bde,Ada Derana Sinhala,http://sinhala.adaderana.lk/news/195779,2024-04-19 00:00:00+00:00,ස්ථාන දෙකකදී ඝාතන දෙකක්,ස්ථාන දෙකකදී ඝාතන දෙකක්\n\nකුලී නිවසක පදිංචිව ...

In [5]:
# Keep rows with the fields required for clustering
required_columns = ["article_id", "publisher", "url", "published_at", "title", "body_text"]
df = df.dropna(subset=required_columns).copy()

print("df shape after required-field dropna:", df.shape)
df.info()

df shape after required-field dropna: (1999, 6)
<class 'pandas.core.frame.DataFrame'>
Index: 1999 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   article_id    1999 non-null   object
 1   publisher     1999 non-null   object
 2   url           1999 non-null   object
 3   published_at  1999 non-null   object
 4   title         1999 non-null   object
 5   body_text     1999 non-null   object
dtypes: object(6)
memory usage: 109.3+ KB

In [6]:
# Unicode normalization (NFC - canonical decomposition + composition)
for column in ["title", "body_text"]:
    df[column] = df[column].astype(str).map(lambda value: unicodedata.normalize("NFC", value))

df.head()

,article_id,publisher,url,published_at,title,body_text
0,f92797eb-a338-5886-a45a-66f01292a912,Lanka Deepa,https://www.lankadeepa.lk/news/දන-තර-මර-අහවන-ක...,2025-09-26 00:00:00+00:00,දැන් තෝරු-මෝරු අහුවෙන කාලේ,දැන් තෝරු-මෝරු අහුවෙන කාලේ\n\nදැන් හාල්මැස්සො ...
1,5c7946aa-a810-59e2-a126-ff58347aad21,BBC Sinhala,https://www.bbc.com/sinhala/articles/c0vy04qd14yo,2024-01-17 00:00:00+00:00,අවුරුදු 67යි. ඇස් දෙකම පේන්නේ නෑ. මම පොල් කඩනවා',අවුරුදු 67යි. ඇස් දෙකම පේන්නේ නෑ. මම පොල් කඩනව...
2,6fc575d1-2be5-5d49-be20-c846617bdacd,Ada,https://www.ada.lk/breaking_news/පිදුරංගල-ගිය-...,2026-02-17 00:00:00+00:00,පිදුරංගල ගිය විදේශිකයා වන අලි ප්‍රහාරයෙන් මරුට,පිදුරංගල ගිය විදේශිකයා වන අලි ප්‍රහාරයෙන් මරුට...
3,47965836-064f-530a-a34d-02f6898fb94a,Ada Derana Sinhala,http://sinhala.adaderana.lk/news/194266,2024-03-07 00:00:00+00:00,හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් ගැ...,හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් ගැ...
4,132990f7-a4f4-54ba-8b12-b469d9803bde,Ada Derana Sinhala,http://sinhala.adaderana.lk/news/195779,2024-04-19 00:00:00+00:00,ස්ථාන දෙකකදී ඝාතන දෙකක්,ස්ථාන දෙකකදී ඝාතන දෙකක්\n\nකුලී නිවසක පදිංචිව ...

In [7]:
# Remove title duplication from the beginning of the body text
def remove_title_from_body(row):
    body = row["body_text"].strip()
    title = row["title"].strip()
    if body.startswith(title):
        body = body[len(title):].lstrip("\n").lstrip()
    return body


df["text"] = df.apply(remove_title_from_body, axis=1)
df[["title", "text"]].head()

,title,text
0,දැන් තෝරු-මෝරු අහුවෙන කාලේ,දැන් හාල්මැස්සො නොව තෝරු මෝරු අහුවෙන කාලය බවමහ...
1,අවුරුදු 67යි. ඇස් දෙකම පේන්නේ නෑ. මම පොල් කඩනවා',"මෙහි කිසිවක් අඩංගු නැත.Play video, ""දිරිය මිනි..."
2,පිදුරංගල ගිය විදේශිකයා වන අලි ප්‍රහාරයෙන් මරුට,සිගිරිය පිදුරංගල මාර්ගයේදී ඊයේ සවස වන අලියෙකු ...
3,හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් ගැ...,හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් දෙ...
4,ස්ථාන දෙකකදී ඝාතන දෙකක්,කුලී නිවසක පදිංචිව සිටි පුද්ගලයෙකුව ඊයේ (18) ර...

In [8]:
print(df["text"][10])

2025.12.07 වන දින රාත්‍රී කාලයේ ගල්නෑව පොලිස් වසමේ බුල්නෑව ප්‍රදේශයේ නිවසක් බිඳ රුපියල් පන්කෝටි හැත්තැදෙලක්ෂ හැටඅටදහාක් (57,268,000/-) වටිනා ප්‍රාඩෝ වර්ගයේ ජීප් රථයක්, රන් භාණ්ඩ මුදල් සහ ජංගම දුරකථන කොල්ලකෑමක් සම්බන්ධයෙන් ගල්නෑව පොලිස් ස්ථානයට ලද පැමිණිල්ලක් මත විමර්ශන ආරම්භ කර තිබුණි.

2025.12.14 වන දින ගල්නෑව පොලිස් ස්ථානයේ නිලධාරීන් විසින් ඉහත අපරාධයට සම්බන්ධ සැකකරුවන් හයදෙනෙකු කුරුණෑගල, මාතවතගම හා විල්ගමුව ප්‍රදේශවලදී හෙරොයින්  ග්‍රෑම් 10 මිලිග්‍රෑම් 300 ක්, අයිස් මත්ද්‍රව්‍ය ග්‍රෑම් 10 මිලිග්‍රෑම් 250 ක්, අපරාධයට යොදාගත් අත්වැසුම් ජෝඩු 04 ක්, උල් පිහි 04 ක්, අපරාධයට යොදා ගත් යතුරුපැදියක්, වෑන් රථයක් හා ලොරි රථයක් සමඟ අත්අඩංගුවට ගෙන ඇත.

සැකකරුවන් අවුරුදු 34, 36, 38, 40, 43 හා 48 වයස්වල පසුවන කුරුණෑගල, නුගගොල්ල, මාවතගම, මැල්සිරිපුර හා මහනුවර ප්‍රදේශවල පදිංචිකරුවන් වේ.

සැකකරුවන් විසින් කොල්ලකන ලද ප්‍රාඩෝ වර්ගයේ ජීප් රථය මීගලෑව ප්‍රදේශයේ දමා ගොස් තිබියදී සොයාගෙන ඇත. තවද කොල්ලකන ලද මුදලින් රුපියල් පනස්නමලක්ෂ තිස්නමදාහක (5,939,000/-) මුදලක් හා කොල්ලකන ලද මුදල් වලින් උපයාගන්නා ලද දේපළ රැසක් විමර්ශන නිලධාරීන් භාරයට ගෙන ඇත.

සැකකරුවන් 2025.12.15 වන දින කැකිරාව මහේස්ත්‍රාත් අධිකරණයට ඉදිරිපත් කර වැඩිදුර විමර්ශන සඳහා 2025.12.18 වන දින දක්වා රැඳවුම් නියෝග ලබාගෙන ඇත. ගල්නෑව පොලිසිය වැඩිදුර විමර්ශන සිදු කරනු ලබයි.

In [9]:
import unicodedata

def clean_text(text):
    # Replace punctuation with spaces
    text = "".join(
        " " if unicodedata.category(char).startswith("P") else char
        for char in text
    )

    # Keep words with more than 2 graphemes
    return " ".join(
        word for word in text.split()
        if len(list(grapheme.graphemes(word))) > 2
    )

df["text"] = df["text"].apply(clean_text)

In [10]:
print(df["text"][10])

2025 රාත්‍රී කාලයේ ගල්නෑව පොලිස් වසමේ බුල්නෑව ප්‍රදේශයේ නිවසක් රුපියල් පන්කෝටි හැත්තැදෙලක්ෂ හැටඅටදහාක් 268 000 වටිනා ප්‍රාඩෝ වර්ගයේ රථයක් භාණ්ඩ මුදල් ජංගම දුරකථන කොල්ලකෑමක් සම්බන්ධයෙන් ගල්නෑව පොලිස් ස්ථානයට පැමිණිල්ලක් විමර්ශන ආරම්භ තිබුණි 2025 ගල්නෑව පොලිස් ස්ථානයේ නිලධාරීන් විසින් ඉහත අපරාධයට සම්බන්ධ සැකකරුවන් හයදෙනෙකු කුරුණෑගල මාතවතගම විල්ගමුව ප්‍රදේශවලදී හෙරොයින් ග්‍රෑම් මිලිග්‍රෑම් 300 අයිස් මත්ද්‍රව්‍ය ග්‍රෑම් මිලිග්‍රෑම් 250 අපරාධයට යොදාගත් අත්වැසුම් අපරාධයට යතුරුපැදියක් රථයක් රථයක් සමඟ අත්අඩංගුවට සැකකරුවන් අවුරුදු වයස්වල පසුවන කුරුණෑගල නුගගොල්ල මාවතගම මැල්සිරිපුර මහනුවර ප්‍රදේශවල පදිංචිකරුවන් සැකකරුවන් විසින් කොල්ලකන ප්‍රාඩෝ වර්ගයේ රථය මීගලෑව ප්‍රදේශයේ තිබියදී සොයාගෙන තවද කොල්ලකන මුදලින් රුපියල් පනස්නමලක්ෂ තිස්නමදාහක 939 000 මුදලක් කොල්ලකන මුදල් වලින් උපයාගන්නා දේපළ රැසක් විමර්ශන නිලධාරීන් භාරයට සැකකරුවන් 2025 කැකිරාව මහේස්ත්‍රාත් අධිකරණයට ඉදිරිපත් වැඩිදුර විමර්ශන සඳහා 2025 දක්වා රැඳවුම් නියෝග ලබාගෙන ගල්නෑව පොලිසිය වැඩිදුර විමර්ශන කරනු ලබයි

In [11]:
# Whitespace normalization
df["text"] = df["text"].map(lambda value: re.sub(r"\n{2,}", "\n", value))
df["text"] = df["text"].map(lambda value: re.sub(r"[ \t]+", " ", value))
df["text"] = df["text"].str.strip()

df = df[df["text"].str.len() > 0].reset_index(drop=True)
print("df shape after text cleaning:", df.shape)
df.head()
print(df["text"][10])

df shape after text cleaning: (1999, 7)
2025 රාත්‍රී කාලයේ ගල්නෑව පොලිස් වසමේ බුල්නෑව ප්‍රදේශයේ නිවසක් රුපියල් පන්කෝටි හැත්තැදෙලක්ෂ හැටඅටදහාක් 268 000 වටිනා ප්‍රාඩෝ වර්ගයේ රථයක් භාණ්ඩ මුදල් ජංගම දුරකථන කොල්ලකෑමක් සම්බන්ධයෙන් ගල්නෑව පොලිස් ස්ථානයට පැමිණිල්ලක් විමර්ශන ආරම්භ තිබුණි 2025 ගල්නෑව පොලිස් ස්ථානයේ නිලධාරීන් විසින් ඉහත අපරාධයට සම්බන්ධ සැකකරුවන් හයදෙනෙකු කුරුණෑගල මාතවතගම විල්ගමුව ප්‍රදේශවලදී හෙරොයින් ග්‍රෑම් මිලිග්‍රෑම් 300 අයිස් මත්ද්‍රව්‍ය ග්‍රෑම් මිලිග්‍රෑම් 250 අපරාධයට යොදාගත් අත්වැසුම් අපරාධයට යතුරුපැදියක් රථයක් රථයක් සමඟ අත්අඩංගුවට සැකකරුවන් අවුරුදු වයස්වල පසුවන කුරුණෑගල නුගගොල්ල මාවතගම මැල්සිරිපුර මහනුවර ප්‍රදේශවල පදිංචිකරුවන් සැකකරුවන් විසින් කොල්ලකන ප්‍රාඩෝ වර්ගයේ රථය මීගලෑව ප්‍රදේශයේ තිබියදී සොයාගෙන තවද කොල්ලකන මුදලින් රුපියල් පනස්නමලක්ෂ තිස්නමදාහක 939 000 මුදලක් කොල්ලකන මුදල් වලින් උපයාගන්නා දේපළ රැසක් විමර්ශන නිලධාරීන් භාරයට සැකකරුවන් 2025 කැකිරාව මහේස්ත්‍රාත් අධිකරණයට ඉදිරිපත් වැඩිදුර විමර්ශන සඳහා 2025 දක්වා රැඳවුම් නියෝග ලබාගෙන ගල්නෑව පොලිසිය වැඩිදුර විමර්ශන කරනු ලබයි

In [12]:
# Build documents for semantic embedding and topic representation
def build_document(title, body):
    title = str(title).strip()
    body = str(body).strip()
    return f"{title}. {body}" if title else body


df["document"] = df.apply(lambda row: build_document(row["title"], row["text"]), axis=1)
documents = df["document"].tolist()

print(f"Documents: {len(documents)}")
documents[0][:500]
print(df["text"][10])

Documents: 1999
2025 රාත්‍රී කාලයේ ගල්නෑව පොලිස් වසමේ බුල්නෑව ප්‍රදේශයේ නිවසක් රුපියල් පන්කෝටි හැත්තැදෙලක්ෂ හැටඅටදහාක් 268 000 වටිනා ප්‍රාඩෝ වර්ගයේ රථයක් භාණ්ඩ මුදල් ජංගම දුරකථන කොල්ලකෑමක් සම්බන්ධයෙන් ගල්නෑව පොලිස් ස්ථානයට පැමිණිල්ලක් විමර්ශන ආරම්භ තිබුණි 2025 ගල්නෑව පොලිස් ස්ථානයේ නිලධාරීන් විසින් ඉහත අපරාධයට සම්බන්ධ සැකකරුවන් හයදෙනෙකු කුරුණෑගල මාතවතගම විල්ගමුව ප්‍රදේශවලදී හෙරොයින් ග්‍රෑම් මිලිග්‍රෑම් 300 අයිස් මත්ද්‍රව්‍ය ග්‍රෑම් මිලිග්‍රෑම් 250 අපරාධයට යොදාගත් අත්වැසුම් අපරාධයට යතුරුපැදියක් රථයක් රථයක් සමඟ අත්අඩංගුවට සැකකරුවන් අවුරුදු වයස්වල පසුවන කුරුණෑගල නුගගොල්ල මාවතගම මැල්සිරිපුර මහනුවර ප්‍රදේශවල පදිංචිකරුවන් සැකකරුවන් විසින් කොල්ලකන ප්‍රාඩෝ වර්ගයේ රථය මීගලෑව ප්‍රදේශයේ තිබියදී සොයාගෙන තවද කොල්ලකන මුදලින් රුපියල් පනස්නමලක්ෂ තිස්නමදාහක 939 000 මුදලක් කොල්ලකන මුදල් වලින් උපයාගන්නා දේපළ රැසක් විමර්ශන නිලධාරීන් භාරයට සැකකරුවන් 2025 කැකිරාව මහේස්ත්‍රාත් අධිකරණයට ඉදිරිපත් වැඩිදුර විමර්ශන සඳහා 2025 දක්වා රැඳවුම් නියෝග ලබාගෙන ගල්නෑව පොලිසිය වැඩිදුර විමර්ශන කරනු ලබයි

In [13]:
print("Sample document:", documents[10:50])

Sample document: ['බුල්නෑව නිවසක් බිඳ ජීප් රථයක්, රන් භාණ්ඩ හා මුදල් කෝල්ල කෑ සැකකරුවන් අල්ලයි. 2025 රාත්\u200dරී කාලයේ ගල්නෑව පොලිස් වසමේ බුල්නෑව ප්\u200dරදේශයේ නිවසක් රුපියල් පන්කෝටි හැත්තැදෙලක්ෂ හැටඅටදහාක් 268 000 වටිනා ප්\u200dරාඩෝ වර්ගයේ රථයක් භාණ්ඩ මුදල් ජංගම දුරකථන කොල්ලකෑමක් සම්බන්ධයෙන් ගල්නෑව පොලිස් ස්ථානයට පැමිණිල්ලක් විමර්ශන ආරම්භ තිබුණි 2025 ගල්නෑව පොලිස් ස්ථානයේ නිලධාරීන් විසින් ඉහත අපරාධයට සම්බන්ධ සැකකරුවන් හයදෙනෙකු කුරුණෑගල මාතවතගම විල්ගමුව ප්\u200dරදේශවලදී හෙරොයින් ග්\u200dරෑම් මිලිග්\u200dරෑම් 300 අයිස් මත්ද්\u200dරව්\u200dය ග්\u200dරෑම් මිලිග්\u200dරෑම් 250 අපරාධයට යොදාගත් අත්වැසුම් අපරාධයට යතුරුපැදියක් රථයක් රථයක් සමඟ අත්අඩංගුවට සැකකරුවන් අවුරුදු වයස්වල පසුවන කුරුණෑගල නුගගොල්ල මාවතගම මැල්සිරිපුර මහනුවර ප්\u200dරදේශවල පදිංචිකරුවන් සැකකරුවන් විසින් කොල්ලකන ප්\u200dරාඩෝ වර්ගයේ රථය මීගලෑව ප්\u200dරදේශයේ තිබියදී සොයාගෙන තවද කොල්ලකන මුදලින් රුපියල් පනස්නමලක්ෂ තිස්නමදාහක 939 000 මුදලක් කොල්ලකන මුදල් වලින් උපයාගන්නා දේපළ රැසක් විමර්ශන නිලධාරීන් භාරයට සැකකරුවන් 2025 කැකිරාව මහේස්ත්\u200dරාත් අධිකරණයට ඉදිරිපත් වැඩිදුර විමර්ශන සඳහා 2025 දක්වා රැඳවුම් නියෝග ලබාගෙන ගල්නෑව පොලිසිය වැඩිදුර විමර්ශන කරනු ලබයි', 'දින 8කින් ලංකාව පුරා තනිව සංචාරය කළ චිත්\u200dර ශිල්පිනිය සමන්මලී ලැබූ අත්දැකීම්. වසරක අවසානය සිහිනයක් ගැනීමට කාන්තාවක සිටියේ නොඉවසිල්ලෙනි මෝටර් සයිකලයෙන් ලංකාව යාමට අවුරුද්දක් සැලසුම් ගමන ආරම්භ කිරීමට වේයන්ගොඩ ප්\u200dරදේශයේ ජීවත් හැවිරිදි වෘත්තීයෙන් චිත්\u200dර ශිල්පිනියකි මෝටර් සයිකලයෙන් තනිව සංචාර කිහිපයක් සමන්මලී තුෂාරා තමන් සේවය කරන ආයතනයෙන් ගමනට අවශ්\u200dය නිවාඩු අනුමත ගැනීමෙන් සංචාරය ආරම්භ කිරීම සඳහා වසරක කාලයක් බීබීසී සිංහල සමග අදහස් දක්වමින් පැවසුවා වසරක් හොඳින් සැලසුම් අටකින් කිලෝමීටර් 822කින් ලංකාව ඇයගේ අත්දැකීම බීබීසී සිංහල පැහැදිලි අයුරිනි මුලින් බයික් ගමනක් මාතර තාත්තාගේ අම්මාව බලලා එන්න යද්දී ගොඩක් ලස්සන එහෙම කරගෙන ගමනත් එක්ක බයික් එකෙන් සංචාරය කරන්න අදහස සමන්මලී තුෂාරා පවසයි සොබාදහමේ ඡායාරූප ගැනීමට උනන්දු අතර මෝටර් සයිකලයෙන් එවැනි යාමට පටන්ගෙන පායන බහින බලන්න ආසයි එතකොට ඒවගේ ලස්සන දේවල් ගන්නත් ආසයි ඒකත් එක්ක තනියම විදිහේ ගමන් යන්න පටන් ගත්තා පැවසුවා ජයමාන්න ලංකාවේ උසම ඇල්ල නෙලුම් කුලුණෙන් පහළට බැස්ස ලංකාවේ පළමු කාන්තාව අනුව අම්පාර ආරුගම්බේ පොළොන්නරුව යාපනය ප්\u200dරදේශවල සංචාරය නමුත් දිගට ලංකාව ගමන් ගන්නා චාරිකාවක් සඳහා සූදානම සැලසුම්සහගතව සඳහා ගමනට කලින් බයික් සම්පූර්ණ පරීක්ෂාවක් කරලා අඩුපාඩු පවසයි ඇයට අවශ්\u200dය ඇඳුම් පහසුවෙන් සොයාගත ආකාරයට අසුරාගෙන අත්\u200dයවශ්\u200dය ඖෂධ අත්\u200dයවශ්\u200dය ලියකියවිලි කබායක් අත්\u200dයවශ්\u200dය භාණ්ඩ පමණක් ගමනට කරගෙන දෙසැම්බර් ආරම්භ චාරිකාව අවසන් ඇත්තේ ජනවාරි වනදා ගමන පැයට කිලෝමීටර් අතර වේගයක් පවත්වා පැවසුවා රාත්\u200dරී වෙන්න කලින් නවාතැනට කෑමත් අරගෙන නවාතැන් ගනිද්දී ගූගල් රිවීව් එහෙම බලලා තමයි ගත්තේ අදාළ දවසේ තමයි නවතින හොයාගෙන විස්තර සාමාන්\u200dය සැහැල්ලු ඇඳුම් ඇඳලා පහසුවක් අවධානයක් ලැබුණේත් පවසයි නවාතැනට ගියාට පස්සේ විවේකයක් ගත්තා විවේකයක් ගත්තා මහන්සි දැනෙන අඩුයි සමන්මලී පවසයි පළමු දිනය වේයන්ගොඩ කල්පිටියදෙවන දිනය කල්පිටිය මන්නාරමතුන්වන දිනය මන්නාරම යාපනයහතරවන දිනය යාපනය මුලතිව්පස්වන දිනය මුලතිව් ත්\u200dරිකුණාමලයහයවන දිනය ත්\u200dරිකුණාමලය ආරුගම්බේහත්වන දිනය ආරුගම්බේ වැලිගමඅටවන දිනය වැලිගම වේයන්ගොඩ සමන්මලීට අතරමගදී හමුවූ සමග කිරීමේදී දෙනෙකු තනිව සංචාරය පිළිබඳව පුදුමයට පත්වූ පැවසුවා නැවතුණු තැන්වල එහෙම ගොඩක් පුදුම එහෙම යනවා කිව්වා හැබැයි ගොඩක් සතුටු සහයෝගයක් දුන්නා සිහිපත් කරයි විදේශීය කාන්තාවකුත් නෙවෙයි ලංකාවේ කෙනෙක් එයාලා තවත් පුදුම විස්තර එහෙම අහනවා ගමන යාපනය ප්\u200dරදේශයේ සංචාරය දිනයේදී ඇයට තවත් අපූරු අත්දැකීමක් තිබිණි යාපනයට ගිහින් නවතින තැනින් තියලා කයිට්ස් පැත්තට එතන ජැටියකින් වෙලාවේ පාලම් පාරුවක් වෙන්න හදමින් හිටියේ ගිහින් ඇහුවා මමත් එන්න කියලා කීයක් ගන්නවා කියලා සල්ලි එන්න කියලා කිව්වා බයික් එකත් අරගෙන ඒකට නැග්ගා පැවසුවා පාරුවේ හිටියා කෙනෙක් එයාට කරන්න භාෂාවෙන් මගෙන් ඇහුවේ අරන් කැමරාව මමත් පුළුවන් විදිහට කිව්වා කැමරාවක් කියලා ගමනේදී ලංකාවේ විශාලතම වනෝද්\u200dයාන දෙකක් විල්පත්තු වනෝද්\u200dයාන සීමාවන් වනෝද්\u200dයාන හරහා යාමට නොහැකි අභ්\u200dයන්තරයෙන් ගමන් බලාපොරොත්තුවෙන් හිටියා අලියෙක් හම්බ කියලා නමුත් අලියෙක් ගමනේදී හම්බ මුලතිව් හරියේදී එහෙමත් තිබුණු හිතුවෙන් අලියෙක් ගැහෙයි කියලා නමුත් ඇයට මුලතිව් ප්\u200dරදේශයේදී වෙනත් අමුත්තෙකු හමුවූ පැවසුවා මුලතිව් ඉඳලා නයාරු පැත්තට කියන්නේ කෝකිලායි කලපුව පැත්තට යනකොට එහෙම පාරවල් පාළුයි පාරෙන් යන්න පහුගිය දවස්වල පාලම කැඩිලා තිබුණ එතනින් ආපස්සට එනකොට ටැමිල් අම්මා කෙනෙක් හම්බ පැවසුවා අඩුයි අම්මා හෙල්මට් එකකුත් දාගෙන පාරට බලාගෙන ඉන්නවා බයික් එකක් නවත්වලා යන්න එද්දිත් විදිහට නැවැත්තුවා නවත්වලා දෙමළෙන් කිව්වා මුලතිව්වලට යන්න ඉන්නේ කියලා පස්සේ එයාව මුලතිව්වලින් දාගෙන පැවසුවා සංචාරය සඳහා ඇයට වියදම් මුදල් සම්බන්ධයෙන් තොරතුරු ගත්තා අනුව ඇයට අටක සංචාරය සඳහා ආසන්න වශයෙන් මුදල 000කි වසරක් සැලසුම් සංචාරය අවසන් නැවත වේයන්ගොඩ නිවසට පැමිණ ඇත්තේ 2026 ජනවාරි මාර්ග නොකොට කිසිදු ආකාරයක අපහසුතාවකට නැවත පැමිණීමට සම්බන්ධයෙන් සතුටු පැවසුවා කල්පිටියේදී පොලිසියෙන් පස්සේ තැන්වලින් පැවසුවා එහිදී බීබීසී සිංහල මීළඟට සංචාරය පිළිබඳව සමන්මලීගෙන් විමසී කලින් මන්දාරම් නුවර වෙලාවේදී පවුලක් පැවසුවා එයාලා එක්ක ගොඩක් හිතවත් පහුගිය දවස්වලදී තත්ත්වයත් එක්ක එයාලට කරදර බලාපොරොත්තු වෙනවා එයාලව බලලා එන්න මන්දාරම් නුවර ගිහින් එන්න සමන්මලී පැවසුවා', 'ශ්\u200dරී ලංකා - කොදෙව් පළමු T20 තරගය අද. ලංකාව බටහිර ඉන්දීය කොදෙව් කණ්ඩායම සමඟ පැවැත්වෙන තරග 3කින් සමන්විත 20යි තරගාවලියේ පළමු තරගය රංගිරි දඹුල්ල ක්\u200dරිකට් ක්\u200dරීඩාංගණයේදී පැවැත්වෙයි දෙරට අතර වනවිට 20යි තරග 15ක් පවත්වා අතර තරග ලංකාව හිමිකර ගනිද්දී කොදෙව් කණ්ඩායම තරග හිමිකරගෙන වෙතත් කණ්ඩායමක් කොදෙව්වන්ට එරෙහිව 20යි තරගාවලි ජයක් මෙතෙක් හිමිකරගෙන නොමැත අතර තරගයට ක්\u200dරීඩාකරන කණ්ඩායමේ අවසන් 11දෙනා ප්\u200dරකාශ කරනු ලැබීය කණ්ඩායම වන්නේ නායක චරිත් අසලංක පැතුම් නිස්සංක කුසල් මෙන්ඩිස් කුසල් ජනිත් පෙරේරා කමිඳු මෙන්ඩිස් භානුක රාජපක්ෂ වනිඳු හසරංග මහිෂ් තීක්ෂණ චමිඳු වික්\u200dරමසිංහ මතීෂ පතිරණ අසිත ප්\u200dරනාන්දුයි අවස්ථාවේදී අදහස් දැක්වූ ක්\u200dරිකට් කණ්ඩායමේ නායක චරිත් අසලංක දැක්කා දසුන් ශානක කණ්ඩායමෙන් ඉවතට පිතිකරුවෙක් වශයෙන් තමයි මමත් පුහුණුකරු තේරුම් කමිටුවත් කතාවෙලා නැවත භානුකව කණ්ඩායමට ගෙනාවේ භානුක රාජපක්ෂගෙන් කණ්ඩායම වැඩිපුරම බලාපොරොත්තු වෙන්නේ එයාගේ අත්දැකීම් වෙලාවේ භානුක රාජපක්ෂ කියන්නේ 20යි තරග ගොඩක් ක්\u200dරීඩා කරලා තියෙන අත්දැකීම් බහුල ක්\u200dරීඩකයෙක් කණ්ඩායමට වැදගත් එයාගේ අත්දැකීම ඉතින් අත්දැකීම අපට වැදගත් අත්දැකීමත් සමග කියන්නේ පවර්හිටින් පැත්ත තමයි භානුක විශේෂයෙන් කණ්ඩායමට කැඳෙව්වේ මොකද එයාට වෙලාවක හයක් ගහන්න පුළුවන් වේලාවට වෙනස් කරලා රොටෙට් කරන් සෙල්ලම් කරන්න පුළුවන් තමයි ප්\u200dරධාන හේතුව භානුක රාජපක්ෂ කැඳවීමට', 'පල්ලි පන්සල් පිළිසකර කිරීමට ප්\u200dරමුඛතාව දෙන්න. ගංවතුරෙන් නායයාමෙන් විපතට ජනතාවට උපරිම සහන සලසන ගමන් විනාශයට විහාරස්ථාන පල්ලි කෝවිල් ඇතුළු සියලු පූජ්\u200dයස්ථාන පිළිසකර කිරීමට ප්\u200dරමුඛතාව ලබාදෙන පෙරමුණේ ජාතික සංවිධායක මන්ත්\u200dරී නාමල් රාජපක්ෂ රජයෙන් ඉල්ලා තමන්ට තොරතුරු අනුව මධ්\u200dයම වයඹ සබරගමුව බස්නාහිර දකුණ උතුරු නැගෙනහිර ප්\u200dරදේශවල විහාරස්ථාන කතෝලික පල්ලි හින්දු කෝවිල් මුස්ලිම් පල්ලි ඇතුළු ආගමික ස්ථාන ගණනකට ගංවතුරින් සිදුවී තිබෙන බවද මන්ත්\u200dරීවරයා පැවසීය පිළිබඳව රජයේ විධිමත් සමීක්ෂණයක් සිදුකර කඩිනම් පියවර', 'විස්කි ඉස්සූ සිද්ධියේ සැකකරු රිමාන්ඩ්. කොළඹ මහෙස්ත්\u200dරාත් අධිකරණයේ භාණ්ඩ රුපියල් විස්කි බෝතල් අතුරුදන්වූ සිද්ධිය සම්බන්ධයෙන් අත්අඩංගුවට සැකකරු එළඹෙන වනදා රක්ෂිත බන්ධනාගාරගත සිද්ධිය සම්බන්ධයෙන් පසුගියදා අධිකරණ අමාත්\u200dය විජයදාස රාජපක්ෂ මහතා පාර්ලිමේන්තුවේදී අනාවරණයක් කළේය එහිදී වැඩිදුරටත් සඳහන් නියමිත යතුරෙන් කාමරයේ විවෘත සොරකම සිදුකර බවට පරීක්ෂක වාර්තාවෙන් අනාවරණය බවය', 'ඊශ්\u200dරායල ජාතිකයින් විසින් සිදුකරන ඉදිකිරීම්වලට අවසර දීලා නැහැ - අගමැති. ඊශ්\u200dරායල ජාතික ආගමික මධ්\u200dයස්ථාන සමාන ස්ථාන ගොඩනැගීම සඳහා රජයේ කිසිදු ආයතනයකින් අවසරයක් ලබාදී නොමැති අග්\u200dරාමාත්\u200dය ආචාර්ය හරිනි අමරසූරිය පවසයි පාර්ලිමේන්තු මන්ත්\u200dරී මුජිබුර් රහුමාන් මහතා පාර්ලිමේන්තුවේදී යොමුකළ ප්\u200dරශ්නයක පිළිතුරු දෙමින් සඳහන් කළාය ඊශ්\u200dරායල ජාතිකයින් ආගමික මධ්\u200dයස්ථාන සමාන ස්ථාන ගොඩනැගීම සඳහා දක්වා බුද්ධශාසන ආගමික සංස්කෘතික කටයුතු අමාත්\u200dයාංශය යටතේ පවතින දෙපාර්තමේන්තු මගින් අවසර ලබාදීමක් සිදුකර නමුත් දන්නවා ඔවුන් එවැනි මධ්\u200dයස්ථාන පවත්වාගෙන බවට සම්බන්ධයෙන් අපිට තොතරු ලැබිලා තියෙනවා පිළිබඳව නිරීක්ෂණයක් කරලා තියෙනවා අවසරයෙන් කරන නෙමෙයි කිසිවිටක අවසරයක් පිළිබඳව මොකද්ද සිදුකළ යුතුතේ කියන පිළිබඳව සාකච්ඡා කරනවා නවත්නවන් කුමක්ද යුත්තේ විදෙස් කටයුතු අමාත්\u200dයාංශය මගින් මැදිහත්වීමක් සිදුවෙනවා එහිදී පාර්ලිමේන්තු මන්ත්\u200dරී මුජිබුර් රහුමාන් මහතා පෙන්වා දුනේන වනවිට ලංකාවේ විවිධ ප්\u200dරදේශවල ඊශ්\u200dරායල් ආගමික මධ්\u200dයස්ථාන සංස්කෘතික මධ්\u200dයස්ථාවටල ආරක්ෂක අමාත්\u200dයංශය මගින් අවරසය ලබාදී ගොඩනගමින් පවතින බවය එවැනි ස්ථානවලට පොලිස් විශේෂ කාර්ය බළකායේ ආරක්ෂාව යොදවා පාර්ලිමේන්තු මන්ත්\u200dරී මුජිබුර් රහුමාන් මහතා වැඩිදුරටත් පැවසීය', 'සාපෙළ සමීක්ෂණ ගාස්තු ගැන අමාත්\u200dයාංශයෙන් නිවේදනයක්. සාමාන්\u200dය පිළිතුරු පත්\u200dර සමීක්ෂණය සඳහා ගුරුවරුන්ට පරීක්ෂකවරුන්ට ගෙවනු ලබන දීමනාව කිරීමට අදාළ අමාත්\u200dය මණ්ඩල සංදේශය ඉදිරිපත් තිබෙන අධ්\u200dයාපන අමාත්\u200dයාංශය නිවේදනයක් නිකුත් කරමින් පවසයි සඳහා කමිටු වාර්තා 2024 ලැබීමට නියමිත අතර වාර්තාව මීළඟ අමාත්\u200dය මණ්ඩලයට ඉදිරිපත් කිරීමටත් අනුව දීමනා කිරීමටත් අපේක්ෂිත නි\u200cවේදනයේ වැඩිදුරටත් දැක්\u200cවෙයි', 'පාර්ලිමේන්තුව අද යළි රැස්වෙයි. ලබන දක්වා පාර්ලිමේන්තුව රැස්වීමට නියමිත පාර්ලිමේන්තු මහලේකම් කාර්යාලය සඳහන් කළේය සේවකයන්ගේ අයවැය සහන දීමනා සංශෝධන පනත් කෙටුම්පත සේවකයන්ගේ ජාතික අවම වේතනය සංශෝධන පනත් කෙටුම්පත ඇතුළු පනත් කෙටුම්පත් දිනයේ විවාදයට ගැනීමට නියමිතව දිනයේ සමාගම් සංශෝධන පනත් කෙටුම්පත දෙවන කියවීමේ විවාදය පැවැත්වීමට නියමිත අතර අනිද්දා දිනයේ විදුලි සංශෝධන පනත් කෙටුම්පත දෙවන කියවීමේ විවාදය පැවැත්වීමට නියමිතය අතර ඉදිරි පාර්ලිමේන්තු සතිය සම්බන්ධයෙන් සාකච්ඡා කිරීම සඳහා විපක්ෂයේ පාර්ලිමේන්තු කණ්ඩායම් රැස්වීම පස්වරුවේ රැස්වුණි අතර දිනයේ ආණ්ඩුක්\u200dරම ව්\u200dයවස්ථා සභාව රැස්වීමට නියමිතව කථානායක ජගත් වික්\u200dරමරත්න මහතාගේ ප්\u200dරධානත්වයෙන් ආණ්ඩුක්\u200dරම ව්\u200dයවස්ථා සභාව රැස්වීමට නියමිත වාර්තා මෙහිදී අගවිනිසුරුවරයෙකු පත්කිරීම සම්බන්ධයෙන් ජනාධිපතිවරයාගේ යෝජනා පිළිබඳව අවධානය යොමුකිරීමට නියමිත සඳහන් අගවිනිසුරු මුර්දු ප්\u200dරනාන්දු මහත්මිය ලබන විශ්\u200dරාම යෑමට නියමිත අතර පුරප්පාඩුව සඳහා අගවිනිසුරුවරයෙකු පත්කිරීමට නියමිතය', "මට කියන්නේ ජංගම සුපර්මාර්කට් එක කියලා.'. කිසිවක් අඩංගු වීඩියෝ ශීර්ෂ වැකිය ඉදිකට්ට පිස්ස සෙරප්පු ඉඳලා දෙයක්ම තියෙනවා මහනුවර පිළිමතලාවේ පදිංචි වින්සන් ජගත් ගණනක් භාණ්ඩ ශරීරයේ එල්ලාගෙන ජංගම වෙළඳාමේ නිරත පුද්ගලයකි භාණ්ඩ වර්ග 300ක් පමණ අතර අලෙවි කිරීමට දිනකට කිලෝමීටර් පමණ ගමන් කරන පවසයි ඉදිකට්ට පිස්සා සෙරප්පු ඉඳලා දෙයක්ම තියෙනවා දරුවන්ට රටට ණයකාරයෙක් වෙන්න කැමති කාටවත් අතපාන්නෙත් එකම බලාපොරොත්තුව මටත් හොඳට දරුවෝ ඉන්නවා දකින්න යනුවෙන් BBC සිංහල පැවසුවේය", 'ලෝක කුසලානය අතරේ ක්\u200dරිකට් තරු දෙකක් විවාහ ගිවිස ගනිති. ලංකාවේදී දිනවල පැවැත්වෙන 2025 ගෘහස්ත ක්\u200dරිකට් තරගාවලියට සහභාගී සඳහා පැමිණ සිටින අතරතුරේදී එංගලන්ත ගෘහස්ථ පිරිමි ක්\u200dරිකට් කණ්ඩායමේ නායක පටෙල් එරට ගෘහස්ත කාන්තා ක්\u200dරිකට් කණ්ඩායම් සාමාජිකා මැලෝරි බාර්ටොෂ් විවාහ ගිවිස ගත්හ පවුල්වල සාමාජික සාමාජිකාවන් පිරිසක් ඉදිරියේ යුවළ ගල්කිස්ස හෝටලයේදී මංගල කරගත් අවස්ථාව 2025 ගෘහස්ත ක්\u200dරිකට් තරඟාවලිය තලවතුගොඩ ඕස්ට්\u200dරේෂියා ගෘහස්ත ක්\u200dරිකට් ක්\u200dරීඩාංගනයේදී දිනවල පැවැත්වේ', 'අවුරුදු තුනකින් නාගරික ගෙවල් පන්දාහක්. ඉදිරි වසර ඇතුළත නාගරික ජනතාවට ගෙවල් පන්දාහක් හදන්න බලාපොරොත්තු නාගරික සංවර්ධන ඉදිකිරීම් නිවාස අමාත්\u200dය අනුර කරුණාතිලක මහතා පාර්ලිමේන්තුවේදී පැවසීය ප්\u200dරතිපත්ති ප්\u200dරකාශනය ඉදිරිපත් කරන විටම පළමු පියවර යටතේ මෙපමණ ප්\u200dරමාණයක් තේරුම් තිබෙනවා ජාත්\u200dයන්තර මූල්\u200dය අරමුදල සම්බන්ධයෙන් ප්\u200dරතිපත්ති ප්\u200dරකාශයේ පැහැදිලි සඳහනක් තිබෙනවා දුප්පත් ජනතාව තත්ත්වයෙන් ගැනීම සඳහා මූල්\u200dය අරමුදල සමග නැවත සාකච්ඡා කරන සඳහන් සහන ලබාදිය ඉලක්ක සහගත කණ්ඩායම් සඳහා වැඩසටහන් සැකසීමට කටයුතු අස්වැසුම ප්\u200dරතිලාභ කිරීමට කටයුතු සිසුන් සඳහා ප්\u200dරවේශ දීමනා සුභසාධන වියදම කිරීමට කටයුතු පැත්තකින් මූල්\u200dය විනය පවත්වා ගැනීම සඳහා කටයුතු තිබෙනවා වගේම මූල්\u200dය විනය පවත්වා ගැනීමෙන් ලැබුණු ප්\u200dරතිලාභය ජනතාවට ලබාදීමට කටයුතු තිබෙනවා වසරේ රැකියා නියුක්තිය සීයට දෙකකින් වසර ඇතුළත නාගරික ජනතාවට ගෙවල් පන්දාහක් හදන්න බලාපොරොත්තු වෙනවා අපිට ඉස්සරහට යන්න තියෙන්නේ ආර්ථික අර්බුදයේ කරගහගෙන යනුවෙන්ද අමාත්\u200dයවරයා', 'විෂ මත් මඩිද්දී කඹ ඇදිලි එපා. දේශපාලන ආර්ථික කරුණු සම්බන්ධයෙන් විවාද නමුත් මත්ද්\u200dරව්\u200dය උවදුර රටින් තුරන් දැමීමේ ජාතික වගකීම කිරීමේදී තවදුරටත් කිසිදු විවාදයකට ඉඩක් නොමැති ජනාධිපති අනුර කුමාර දිසානායක මහතා පැවැසීය මත්ද්\u200dරව්\u200dය උවදුර මුලිනුපුටා දැමීමේ කඩිනම් වැඩපිළිවෙළක් වෙනුවෙන් රටම එකට බවද ජනාධිපතිවරයා අවධාරණය කළේය ජනාධිපතිවරයා සඳහන් මත්ද්\u200dරව්\u200dය මුලිනුපුටා දැමීම සඳහා රටම එකට ජාතික මෙහෙයුම පිළිබඳ මාධ්\u200dය ආයතන ප්\u200dරධානීන් දැනුවත් කිරීම වෙනුවෙන් ජනාධිපති කාර්යාලයේ පැවති හමුවට වෙමිනි මත්ද්\u200dරව්\u200dය ජාවාරම බැදුණු අපරාධ කල්ලිවල මූල්\u200dය බලය විසින් ආර්ථිකය සමාජ දේහය රාජ්\u200dය යාන්ත්\u200dරණය නීතියේ විධානයේ ආධිපත්\u200dය වට්ටමින් රටත් සමාජයත් විනාශ කරමින් තිබෙන ජනාධිපතිවරයා සඳහන් කළේය උවදුරට තවදුරටත් නොතැබීමට වත්මන් රජය තීරණය තිබෙන පැවසු ජනාධිපතිවරයා වෙනුවෙන් සියලු දෙනාගේ දායකත්වය අපේක්ෂා කරන බවද පැවසීය එමෙන්ම පසුගිය සමයේ දේශපාලන රශ්මි කදම්භය නිදැල්ලේ වර්ධනය අපරාධ රටත් සමාජයත් දැඩිව වෙළාගෙන තිබෙන අන්දම පොලිසිය රේගුව මෝටර් ප්\u200dරවාහන දෙපාරත්මේන්තුව ආගමන විගමන දෙපාර්තමේන්තුව ඇතුළු රජයේ වගකිවයුතු ආයතනවලින් සහාය පිළිබඳවද ජනාධිපතිවරයා මෙහිදී සිහිපත් කළේය නැවත එවැනි තත්ත්වයකට නොතබා අනාගත පරපුර වෙනුවෙන් ජාතික ව්\u200dයසනය පරාජය කිරීමට සියලු පැවරි අත්හළ නොහැකි වගකීම ජනාධිපතිවරයා මෙහිදී වැඩිදුරටත් අවධාරණය කළේය රටම එකට ජාතික මෙහෙයුම සමාරම්භය ජනාධිපති අනුර කුමාර දිසානායක මහතාගේ ප්\u200dරධානත්වයෙන් කොළඹ සුගතදාස ගෘහස්ථ ක්\u200dරීඩාංගණයේදී වැනිදා පෙරවරු 10ට පැවැත්වේ සෞඛ්\u200dය ජනමාධ්\u200dය අමාත්\u200dය වෛද්\u200dය නලින්ද ජයතිස්ස ජනාධිපති ලේකම් ආචාර්ය නන්දික සනත් කුමානායක මහත්වරු රාජ්\u200dය පෞද්ගලික විද්\u200dයුත් මුද්\u200dරිත මාධ්\u200dය ආයතන ප්\u200dරධානීහු නියෝජිතයෝ විනෝදාස්වාද කර්මාන්තයට අදාළ ආයතන ප්\u200dරධානීහු ඇතුළු පිරිසක් අවස්ථාවට එක්ව සිටියහ', "අතුරුදන්වූවන්ගේ ඥාතීන්ගේ විරෝධතාවට වසර 7: 'ජාත්\u200dයන්තර විමර්ශනයක් අවශ්\u200dයයයි'. කිසිවක් අඩංගු Play video අයිතීන් ගන්න අරගල කිරීම මාවතක් තියෙනවා කියලා හිතන්නේ ධාවන කාලය 5602 56වීඩියෝ ශීර්ෂ වැකිය අයිතීන් ගන්න අරගල කිරීම මාවතක් තියෙනවා කියලා හිතන්නේ යුද්ධයෙන් අතුරුදන්වූවන්ගේ උතුරු නැගෙනහිර පළාත් ඥාතීන් පවත්වන අඛණ්ඩ විරෝධතා උපවාස මාලාවට වසර හතක් ගතවීම නිමිත්තෙන් අතුරුදන්වූවන් සොයාදෙන ලෙසට ඉල්ලා අතුරුදන්වූවන්ගේ ඥාතීහූ පෙබරවාරි වැනිදා කිලිනොච්චිය නගරයේදී විරෝධතා පාගමනක් පැවැත්වූහ ඔවුන් කිලිනොච්චිය කන්දසාමි කෝවිල අසළින් පාගමන ආරම්භ කරමින් කිලිනොච්චිය නගරය ඔස්සේ ගමන් කරමින් විරෝධතාව පවත්වනු ලැබීය කිලිනොච්චිය යාපනය වවුනියාව මුලතිව් මන්නාරම දිස්ත්\u200dරික්කවල අතුරුදන්වූවන්ගේ ඥාතීන්ගේ සංගම් විසින් විරෝධතාවය පැවැත්වනු ලැබූහ යුද්ධයෙන් අතුරුදන්වූවන් සොයාදෙන ලෙසට ඉල්ලීම් කරමින් 2017 පෙබරවාරි වැනිදා අතුරුදන්වූවන්ගේ ඥාතීන් විසින් විරෝධතාවය ආරම්භ කරනු ලැබීය විරෝධතාවයට එක්වු කිලිනොච්චිය දිස්ත්\u200dරික් අතුරුදන්වූවන්ගේ සංගමයේ සභාපති කනගරංජනි පැවසුවාය යුද්දේ කාලයේ අතුරුදන්වු ඥාතීන් සොයාදෙන ලෙසට ආරම්භ විරෝධතාවයට අදට අවුරුදු හතක් ගතවෙනවා අපිට කිසිදු සාධාරණයක් වෙනකම් ඉටුවෙලා යුද්ධය ඉවරවෙලා අවුරුදු පහළොවකට කාලයක් ගතවෙලා දක්වා පත්වුණු කිසිදු රජයක් සමයේ අතුරුදන්වූවන් සොයාදීමට කටයුතු කරලා කිසිම ආණ්ඩුවක් කිසිම පාලකයෙක් තමන්ගේ ඉල්ලීම් වෙනුවෙන් සාධාරණය ඉටුකරදීමට උත්සහ කරලාවත් ඉල්ලන්නේ ඥාතීන් කොහේද කියලා හොයලා දෙන්න කියලා විතරයි පැවසුවාය අවුරුදු හතක් කිලිනොච්චිය කන්දසාමි කෝවිල ඉදිරිපිට ඉඳගෙන ඥාතීන් හොයලා දෙන්න කියලා ඉල්ලීම් ගැටළුවට දක්වා කිසිම සහනයක් ලැබුණේ උතුරු නැගෙනහිර අතුරුදන්වූවන්ගේ ඥාතීන් විරෝධතාවකඋතුරු නැගෙනහිර අතුරුදහන්වූවන්ගේ ඥාතීන්ගේ අඛණ්ඩ උපවාසයට 2000 ඉල්ලන්නේ ජාත්\u200dයන්තරයේ රටවල් මැදිහත්වෙලා ගැටළුවට සාධාරණය ලබාදෙන්න කියලා දේශීය ක්\u200dරමවේදයකින් ගැටළුවට විසදුම් ලැබෙන්නේ කියලා දන්නවා ඊශ්\u200dරායල පලස්තීන ගැටළුව වෙලාවේ දකුණු අප්\u200dරිකාව රටවල් මැදිහත්වෙලා යුද්ධය වෙලාවේ අතුරුදන්වූවන් සම්බන්ධයෙන් ගැටළුවට සාධාරණ පිළිතුරක් ලබාදෙන්න ක්\u200dරමයක් හැදුවා අතුරුදන්වූවන් වෙනුවෙන් ජාත්\u200dයන්තර රටවල් මැදිහත්වෙලා සාධාරණයක් ලබාදෙන්න කියලා තමයි ඉල්ලන්නේ නායකයෝ හදන වැඩසටහන්වලින් අපිට යහපතක් ලැබෙයි කියලා විශ්වාස කරන්න කිලිනොච්චිය දිස්ත්\u200dරික් අතුරුදහන්වූවන්ගේ සංගමයේ ලේකම් ලීලාවති පැවසුවාය අතුරුදහන්වූවන් සොයාදෙන බවට පවසමින් රජය විසින් අතුරුදහන්වූවන් සොයාදීමේ කාර්යාලයක් ස්ථාපිත තවත් විවිධ ආයතන බිහිකරලා අතුරුදන්වූවන්ට සාධාරණය කරන්න කටයුතු කරනවා කිව්වා දක්වා අපිට යහපතක් දැනට යුද්දේ ඉවරවෙලා ආණ්ඩු තුනක් බිහිවුණත් කිසිදු රජයකින් අතුරුදහන්වූවන්ගේ ගැටළුවට විසදුම් ලබාදීලා අතුරුදහන්වූවන්ගේ අම්මලාගේ ඉල්ලීම පාලකයින් කවදාවත් අහන්නේ වෙනුවෙන් සාධාරණයක් ලබාදෙන්නෙත් පාලකයෝ පාරවල් දුක්විදින අම්මලා වෙනුවෙන් ඇහුම්කන් දෙන්නේ යනුවෙන් විරෝධතාවයට එක්වු සන්ධ්\u200dය එක්නැළිගොඩ පැවසුවාය වවුනියාව දිස්ත්\u200dරික් අතුරුදන්වූවන්ගේ සංගමයේ සභාපති රාජ්කුමාර් පැවසූවේ අතුරුදන්වූවන්ගේ ගැටළුව දෙමළ ජනතාවගේ ප්\u200dරශ්න විසදුම් ලබාදීමට රජයක්ම අපොහොසත් තියෙනවා අතුරුදහන්වූවන්ගේ ගැටළුවට විසදුම් ඉල්ලීම් කරමින් වර්තමාන ජනාධිපතිවරයා අගමැතිවරයා අවදියේ ඉල්ලීම් දක්වා වෙනුවෙන් සාධාරණය ඉටුවෙලා එක්සත් ජාතීන්ගේ සංවිධානය යුරෝපා සංගමය ඇමෙරිකාව ඇතුළු රටවල් මැදිහත් යුද්ධයෙන් අතුරුදහන්වු උතුරු නැගෙනහිර වැසියන් පිළිබඳ සාධාරණය ඉටුකරදිය යුතුයි යනුවෙන් පැවසීය අවස්ථා ගණනාවකදී රජය විසින් අතුරුදන්වූවන්ගේ ගැටළුව වෙනුවෙන් පිළිතුරු ලබාදෙන බවට ප්\u200dරකාශ කළද තමන්ගේ ගැටළුව වෙනුවෙන් මෙතෙක් පිළිතුරක් නොලැබීම කණගාටුවට කරුණක් බවද අතුරුදහන්වූවන්ගේ ඥාතීහූ පැවසූහ අතුරුදහන්වූවන්ගේ ඥාතීන් වැඩිදුරටත් සඳහන් උතුරු නැගෙනහිර නියෝජනය කරන දෙමළ දේශපාලන නායකයින්ද තමන්ගේ ගැටළුවට විසදුම් ලබාදීම වෙනුවෙන් මැදිහත්වීමක් නොකරන ජාත්\u200dයන්තරය මැදිහත්ව තමන්ගේ ගැටළුව වෙනුවෙන් විසදුම් ලබාදිය බවද විරෝධතාවයට එක්වු අතුරුදහන්වූවන්ගේ ඥාතීහූ ඉල්ලා සිටියහ යුද්ධය එළැඹෙන වසර වසර ගතවුවද අතුරුදන්වූවන් සම්බන්ධයෙන් සඳහනක් බැලීමක් නොමැතිවීමෙන් තමන් මහත් අසරණ සිටින විරෝධතාකරුවෝ පැවසූහ", 'ජනපති බුද්ධගයාව වැඳ පුදා ගනී. ඉන්දියාවේ සංචාරයක නිරත ජනාධිපති අනුර කුමාර දිසානායක දෙසැම්බර් වැනිදා පෙරවරුවේ බුද්ධගයාවට පැමිණ විහාරයත් බෝධීන් වහන්සේත් ආශීර්වාද ගත්තේය ඉන්දියානු මහාබෝධි සමාගමේ මහලේකම් පූජ්\u200dය පැලවත්තේ සීවලි ස්වාමීන්වහන්සේ සාරනාත් මධ්\u200dයස්ථානාධිපති පූජ්\u200dය රත්මල්වල සුමිත්තානන්ද ස්වාමීන්වහන්සේ විසින් ජනාධිපතිවරයාට ආශිර්වාද කරන ජනාධිපති මාධ්\u200dය අංශය සඳහන් කළේය විදේශ කටයුතු විදේශ රැකියා සංචාරක අමාත්\u200dය විජිත හේරත් කම්කරු අමාත්\u200dය ආර්ථික සංවර්ධන නියෝජ්\u200dය අමාත්\u200dය මහාචාර්ය අනිල් ජයන්ත ප්\u200dරනාන්දු අවස්ථාවට එක්ව සිටියහ ඉන්දියාවේ තෙදින සංචාරයක නිරත ජනාධිපති අනුර කුමාර දිසානායක නවදිල්ලි නුවර දෙසැම්බර් වැනිදා පස්වරුවේ ඉන්දීය පරිමාණ ව්\u200dයාපාරික නියෝජිතයන් සමඟ සාකච්ඡාවකට ඉන්දියානු කර්මාන්ත සම්මේලනය විසින් සංවිධානය කරන සාකච්ඡාවට ඉන්දියාවේ ප්\u200dරමුඛතම ව්\u200dයවසායකයන් සහභාගී ලංකාවේ ආයෝජනවලට හිතකර පරිසරය පහදා ජනාධිපති අනුර කුමාර දිසානායක ලංකාවේ ආයෝජනය කරන ඉන්දීය ව්\u200dයවසායකයන්ගෙන් ඉල්ලා ජනාධිපති මාධ්\u200dය අංශය සඳහන් කළේය දෙරට අතර ආයෝජන වාණිජ සම්බන්ධතා පුළුල් කිරීමේ අරමුණෙන් පැවති සාකච්ඡාවේදී ඩිජිටල් ආර්ථික සංචාරක පුනර්ජනනීය බලශක්ති තොරතුරු තාක්ෂණ ක්ෂේත්\u200dර පිළිබඳව විශේෂ අවධානය කෙරිණි අනුව දෙරට අතර වෙළෙඳ කටයුතු මුල්කර ගනිමින් ලංකාවේ ආයෝජන අවස්ථා පුළුල් කිරීම පිළිබඳව සාකච්ඡාවට මෙහිදී ලංකාවේ අයෝජන අවස්ථා කෙරෙහි වීමට ඉන්දීය පරිමාණ ව්\u200dයාපාරික නියෝජිතයන් කැමැත්ත අතර සඳහා අවශ්\u200dය ආයෝජන පහසුකම් සැපයීමට රජය එකඟ ඉන්දියාවේ ආරක්ෂාවට හානිදායක අයුරින් භූමිය ගැනීමට නොදෙන බවට ජනාධිපති අනුර කුමාර දිසානායක ඉන්දීය අග්\u200dරාමාත්\u200dය නරේන්ද්\u200dර පොරොන්දු ඉන්දීය අග්\u200dරමාත්\u200dයවරයා සමග දෙසැම්බර් වැනිදා ඒකාබද්ධ ප්\u200dරවෘත්ති සාකච්ඡාවකට එක්වෙමින් ජනාධිපතිවරයා සිටියේය ඉන්දියාවේ ආරක්ෂාවටත් කලාපයේ ස්ථාවරත්වයටත් හානිදායක කිසිදු ආකාරයකින් භූමිය ගැනීමට ලංකාව නොදෙන බවට ඉන්දියානු අග්\u200dරාමාත්\u200dයවරයාට පොරොන්දු සහතික ජනාධිපතිවරයා පැවසීය සිටියේ එළඹෙන් වසර ගණනාව තවදුරටත් ශක්තිමත් බවට කිසිදු සැකයක් ඉන්දියාව සමග සහයෝගීතාවය අඛණ්ඩව වර්ධනය කිරීම පුළුල් කිරීම කෙරෙහි ලංකාව විශාල වැදගත්කමක් නැවත අවධාරණය කරනවා එමෙන්ම ලංකාවේ සංචාරයක් සඳහා පැමිණෙන ලෙසට ඉන්දීය අග්\u200dරාමාත්\u200dය නරේන්ද්\u200dර මෝදිට ආරාධනා ජනාධිපති අනුර කුමාර දිසානායක ප්\u200dරවෘත්ති සාකච්ඡාවේදී පැවසීය ජනාධිපති අනුර කුමාර දිසානායක පළමු විදෙස් සංචාරය ඉන්දියාව ගැනීම පිළිබඳව ඉන්දීය අගමැති නරේන්ද්\u200dර මෙහිදී සතුට කළේය ජනාධිපතිවරයා සමග සංහිඳියාව ප්\u200dරතිසංස්කරණය පිළිබඳව සාකච්ඡා පැවසූ ඉන්දීය අග්\u200dරාමාත්\u200dයවරයා රජය දෙමළ ජාතීන්ගේ අභිලාෂයන් කරනු ඇතැයි විශ්වාසය කළේය අද්විතීය ඩිජිටල් අනන්\u200dයතා වැඩසටහනක් සඳහා ලංකාව සමඟ ඉන්දියාව සහයෝගයෙන් කටයුතු කරන අගමැති මෙහිදී පැවසීය ලංකාවේ සංවර්ධනය සඳහා ඉන්දියාවේ ශක්තිමත් සහයෝගය ඉන්දීය අගමැතිවරයා ප්\u200dරකාශයේදී අවධාරණය කළේය සාම්පූර් සූර්ය බලශක්ති ව්\u200dයාපෘතිය ක්\u200dරියාත්මක කිරීමට පියවර ගැනීම ලංකාවේ අවශ්\u200dයතා අනුව ධාරිතාව තවදුරටත් කිරීම ඉන්දියාවෙන් ලංකාවට ස්වභාවික ද්\u200dරව සැපයීම ඉන්දියාව ලංකාව අතර ධාරිතා විදුලි අන්තර් සම්බන්ධතාවයක් ස්ථාපිත කිරීම සත්ත්ව වෘක්ෂලතා ඇතුළු පාරිසරික ආරක්ෂාවට ප්\u200dරමුඛත්වය දෙමින් සමුද්\u200dර සන්ධියේ අක්වෙරළ ශක්තිය ඒකාබද්ධව සංවර්ධනය කිරීම කරුණු ගැනද මෙහිදී ඉන්දීය අග්\u200dරාමාත්\u200dයවරයා ජනාධිපතිවරයා අතර සාකච්ජා පවත්වා ඉන්දීය විදේශ කට

In [14]:


stopwords = {
    "අද", "අප", "අපි", "අපේ", "අතර", "අනුව", "අය", "අයගේ", "ඇත", "ඇති", "ඇතුළු",
    "ඒ", "එම", "එය", "එහි", "එක්", "එක", "එකක්", "කර", "කරන", "කරයි", "කරමින්",
    "කළ", "කිරීම", "කියන", "කියා", "ගැන", "ගැනීමට", "ගැනීම", "තම", "තුළ", "ද", "දී",
    "දක්වා", "දැයි", "නම්", "නමුත්", "නිසා", "බව", "බවට", "බවයි", "බවද", "මත", "මෙන්",
    "මෙම", "මේ", "ය", "යන", "ලෙස", "වූ", "වෙත", "වෙනුවෙන්", "සහ", "සිට", "සඳහා",
    "හා", "හෝ", "මගින්", "බවත්"
}



stopwords = sorted(stopwords)

print(f"Stopwords: {len(stopwords)}")

Stopwords: 59

In [15]:
# Embed documents with BGE-M3
from sentence_transformers import SentenceTransformer
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
embedding_model_name = "BAAI/bge-m3"
embedding_model = SentenceTransformer(embedding_model_name, device=device)

embeddings = embedding_model.encode(
    documents,
    batch_size=16,
    show_progress_bar=True,
    normalize_embeddings=True,
)

print(embeddings.shape)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

Batches:   0%|          | 0/125 [00:00<?, ?it/s]

(1999, 1024)

In [16]:
# Embedding separation score (comparable across notebooks): 1 - mean pairwise cosine similarity
# on a random 100-document sample of the raw (pre-UMAP) embeddings.
from sklearn.metrics.pairwise import cosine_similarity

rng = np.random.default_rng(SEED)
sample_idx = rng.choice(len(embeddings), size=min(100, len(embeddings)), replace=False)
sample_emb = embeddings[sample_idx]

sims = cosine_similarity(sample_emb)
pairwise = sims[np.triu_indices_from(sims, k=1)]
separation_score = 1 - pairwise.mean()

print(f"Embedding model: {embedding_model_name}")
print(f"mean_sim={pairwise.mean():.4f} std={pairwise.std():.4f} min={pairwise.min():.4f} max={pairwise.max():.4f}")
print(f"Separation score (1 - mean cosine similarity): {separation_score:.4f}")

Embedding model: BAAI/bge-m3
mean_sim=0.4053 std=0.0668 min=0.2252 max=0.7894
Separation score (1 - mean cosine similarity): 0.5947

In [17]:
# Configure BERTopic with UMAP, HDBSCAN, and CountVectorizer
from bertopic import BERTopic
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer
from umap import UMAP

umap_model = UMAP(
    n_neighbors=3,
    n_components=5,
    min_dist=0.0,
    metric="cosine",
    random_state=SEED,
)

hdbscan_model = HDBSCAN(
    min_cluster_size=2,
    min_samples=1,
    metric="euclidean",
    cluster_selection_method="leaf",
    prediction_data=True,
)

vectorizer_model = CountVectorizer(
    stop_words=list(stopwords),
    token_pattern=r"(?u)\b\w\w+\b",
    ngram_range=(1, 2),
    min_df=1,
)

topic_model = BERTopic(
    embedding_model=embedding_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer_model,
    language="multilingual",
    calculate_probabilities=True,
    verbose=True,
)

In [18]:
# Fit BERTopic using the precomputed BGE-M3 embeddings
topics, probabilities = topic_model.fit_transform(documents, embeddings)

df["topic_id"] = topics
df["topic_probability"] = [float(np.max(row)) if row is not None and len(row) else np.nan for row in probabilities]

topic_info = topic_model.get_topic_info()
topic_info.head(20)

2026-08-20 12:05:45,756 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm

2026-08-20 12:06:04,665 - BERTopic - Dimensionality - Completed ✓
2026-08-20 12:06:04,666 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-08-20 12:06:19,580 - BERTopic - Cluster - Completed ✓
2026-08-20 12:06:19,589 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-08-20 12:06:21,585 - BERTopic - Representation - Completed ✓

,Topic,Count,Name,Representation,Representative_Docs
0,-1,160,-1_මන රම_පත_ජන පත_ජන,"[මන රම, පත, ජන පත, ජන, සම හය, ගණක පත, පත වරය, ...",[LOLC සමූහය ශක්තිමත් වර්ධනයක් වාර්තා කරයි. 202...
1,0,11,0_මහජන උපය_උපය සම_උපය_බල මණ,"[මහජන උපය, උපය සම, උපය, බල මණ, මහජන, මණ ඩලය, ඩ...",[විදුලි ගාස්තු ඉහළ දැමීමේ තීරණය 15වැනිදා. විදු...
2,1,8,1_නව කම_කම උල_උල_ලධ,"[නව කම, කම උල, උල, ලධ, උල ඝනය, ඝනය, කම සම, සත ...",[මානව හිමිකම් කොමිසම සිය මානව හිමිකම් කඩකළ බවට...
3,2,8,2_තරග තහනම_ෂක ජයත_ලක මහත_පර රව,"[තරග තහනම, ෂක ජයත, ලක මහත, පර රව, රව රම, අඩ වට...",[ශිරාන් බාසික් නිදොස් කොට නිදහස්. ප්‍රධාන මත්ද...
4,3,7,3_අයව_රත දන_අධ පන_පන රත,"[අයව, රත දන, අධ පන, පන රත, බඳවද, අයව රත, 2026,...",[සියලු මන්ත්‍රීවරුන්ට අධ්‍යාපන ප්‍රතිසංස්කරණ ග...
5,4,7,4_අග_අග යවර_අග ආච_ආච හර,"[අග, අග යවර, අග ආච, ආච හර, යථ තත, රව යමය, තත ව...",[ජීවිත ගොඩනගන්න නිලධාරීන්ගේ කාර්යක්ෂම සහය අවශ්...
6,5,7,5_කම වන_කම_චය සභ_අර ධක,"[කම වන, කම, චය සභ, අර ධක, ධක අරම, 200ක, රජය, ව...",[වතු කම්කරුවන් ගැන කම්කරු විනිශ්චය සභාව දුන් න...
7,6,7,6_ටලය_හග_රව රම_හග නය,"[ටලය, හග, රව රම, හග නය, රව, රව සමඟ, ළඹ මධ, සන ...",[කෝණා සමග කුඩු සැඟවූ නෝනලා. පොලීසියට පෙන්වා පළ...
8,7,7,7_දමර_ඇළට_සය දමර_ටර රථය,"[දමර, ඇළට, සය දමර, ටර රථය, අනත රක, ගමන කරම, ටර...",[බිරිඳගේ හිස රැගෙන පොලීසියට ගිය අනිල්. වනවිට ස...
9,8,7,8_රම මල_මල_පර ෂකවරය_ෂකවරය,"[රම මල, මල, පර ෂකවරය, ෂකවරය, නවත, මල මහ, රස ලධ...",[රිමාන්ඩ් - ජනමතය නිවැරැදිද?. කිසියම් චෝදනාවකට...
10,9,7,9_කත යක_සභ ජන_කත_යක රය,"[කත යක, සභ ජන, කත, යක රය, ඉල අස, එර සභ, යක රයට...",[කෝප් කමිටු සාමාජිකයින් දිගින් දිගට ම ඉල්ලා අස...
11,10,7,10_පත රය_පත උසස_වන පත_පළම රශ,"[පත රය, පත උසස, වන පත, පළම රශ, අයද, උසස, යයන ස...",[උසස් පෙළ විශිෂ්ටයෝ මෙන්න. උසස් විභාග ප්‍රතිඵල...
12,11,7,11_කසල_ටයර_කසල බද_නගර සභ,"[කසල, ටයර, කසල බද, නගර සභ, ඔය නගර, ටන ඔය, ටන, ...",[හිටි හැටියේ වාහන දෙකක් ගිනිගෙන. බදුල්ල වැලිමඩ...
13,12,6,12_කඩ ගන_ගමන බවත_සට ගමන_පහළ කඩ,"[කඩ ගන, ගමන බවත, සට ගමන, පහළ කඩ, ළඹ මහන, ධන අධ...",[අතුරුගිරිය හුවමාරුව ජලයෙන් යටවෙයි. අතුරුගිරිය...
14,13,6,13_අනත වල_යත යක_සට වනය_අනත,"[අනත වල, යත යක, සට වනය, අනත, වනය යත, රක අනත, ය...",[බුජ්ගමුව ඔයට ජීප් රථයක් පෙරළී අයියයි මල්ලියි ...
15,14,6,14_උප_තර සල_ඉග_සල,"[උප, තර සල, ඉග, සල, අධ පනය, සල වල, අධ පන, ඨම, ...",[ජාත්‍යන්තර පාසල් නියාමනය නොකිරීමෙන් 'දරුවන්ට...
16,15,6,15_එරබද_erythrina_ෂම_එරබද කය,"[එරබද, erythrina, ෂම, එරබද කය, කන නය, gall was...",[බඩගින්න දරාගන්න බැරිව කුරුම්බා ගෙඩියක් බිව්වා...
17,16,6,16_රභ ජයස_නය දක_යවන ඩක_නවතම ගත,"[රභ ජයස, නය දක, යවන ඩක, නවතම ගත, ඉද යට, ගත වල,...",[ප්‍රභාත් ජයසූරිය ශ්‍රේණිගත කිරීම් හී ඉහළට - න...
18,17,6,17_යම ඉලක_බද ආද_ආද_වත යල,"[යම ඉලක, බද ආද, ආද, වත යල, ආද යම, වර ෂය, ආයතනය...",[බදු ආදායමේ කැපී පෙනෙන වර්ධනයක්. මෝටර් ආනයන ලි...
19,18,6,18_හන ආනයනය_හන_ආනයනය_ආනයන,"[හන ආනයනය, හන, ආනයනය, ආනයන, හන ආනයන, අඩ මක, කථ...",[පෙබරවාරි 01 සිට පෞද්ගලික පරිහරණය සඳහා වාහන ආන...

In [19]:
# Clustering evaluation: unsupervised metrics on the UMAP-reduced space HDBSCAN actually clustered on
from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score

reduced_embeddings = topic_model.umap_model.embedding_

mask = df["topic_id"] != -1
X_valid = reduced_embeddings[mask.values]
labels_valid = df.loc[mask, "topic_id"].values
n_clusters = len(set(labels_valid))
noise_ratio = 1 - mask.mean()

print(f"Model: {embedding_model_name} + UMAP + HDBSCAN (BERTopic)")
print(f"Articles: {len(df)} | Topics (excl. noise): {n_clusters} | Noise ratio: {noise_ratio:.2%}")

if n_clusters > 1:
    sil = silhouette_score(X_valid, labels_valid, metric="cosine")
    dbi = davies_bouldin_score(X_valid, labels_valid)
    ch = calinski_harabasz_score(X_valid, labels_valid)
    print(f"Silhouette Score (cosine): {sil:.4f}")
    print(f"Davies-Bouldin Index:      {dbi:.4f}  (lower is better)")
    print(f"Calinski-Harabasz Index:   {ch:.2f}  (higher is better)")
else:
    sil = dbi = ch = float("nan")
    print("Not enough clusters to compute silhouette/DBI/CH.")

# Save scores so they can be compared against the other embedding models later
scores_path = RESULTS_DIR / "bge_m3_bertopic_scores.csv"
row = {
    "model": embedding_model_name,
    "pipeline": "UMAP+HDBSCAN (BERTopic)",
    "embedding_dim": embeddings.shape[1],
    "separation_score": round(separation_score, 4),
    "n_articles": len(df),
    "n_clusters": n_clusters,
    "noise_ratio": round(noise_ratio, 4),
    "silhouette": round(sil, 4) if n_clusters > 1 else None,
    "davies_bouldin": round(dbi, 4) if n_clusters > 1 else None,
    "calinski_harabasz": round(ch, 2) if n_clusters > 1 else None,
}
pd.DataFrame([row]).to_csv(scores_path, index=False)
print(f"Saved scores to {scores_path}")

Model: BAAI/bge-m3 + UMAP + HDBSCAN (BERTopic)
Articles: 1999 | Topics (excl. noise): 613 | Noise ratio: 8.00%
Silhouette Score (cosine): 0.8060
Davies-Bouldin Index:      0.3604  (lower is better)
Calinski-Harabasz Index:   25719.44  (higher is better)
Saved scores to /kaggle/working/results/bge_m3_bertopic/bge_m3_bertopic_scores.csv

In [20]:
# Cluster/topic summary
print(df["topic_id"].value_counts().head(20))
print("Noise articles:", int((df["topic_id"] == -1).sum()))
print("Number of topics found:", df["topic_id"].nunique() - (1 if -1 in df["topic_id"].values else 0))

topic_info.head(30)

topic_id
-1     160
 0      11
 1       8
 2       8
 3       7
 4       7
 5       7
 6       7
 7       7
 8       7
 9       7
 10      7
 11      7
 12      6
 13      6
 14      6
 15      6
 16      6
 17      6
 18      6
Name: count, dtype: int64
Noise articles: 160
Number of topics found: 613

,Topic,Count,Name,Representation,Representative_Docs
0,-1,160,-1_මන රම_පත_ජන පත_ජන,"[මන රම, පත, ජන පත, ජන, සම හය, ගණක පත, පත වරය, ...",[LOLC සමූහය ශක්තිමත් වර්ධනයක් වාර්තා කරයි. 202...
1,0,11,0_මහජන උපය_උපය සම_උපය_බල මණ,"[මහජන උපය, උපය සම, උපය, බල මණ, මහජන, මණ ඩලය, ඩ...",[විදුලි ගාස්තු ඉහළ දැමීමේ තීරණය 15වැනිදා. විදු...
2,1,8,1_නව කම_කම උල_උල_ලධ,"[නව කම, කම උල, උල, ලධ, උල ඝනය, ඝනය, කම සම, සත ...",[මානව හිමිකම් කොමිසම සිය මානව හිමිකම් කඩකළ බවට...
3,2,8,2_තරග තහනම_ෂක ජයත_ලක මහත_පර රව,"[තරග තහනම, ෂක ජයත, ලක මහත, පර රව, රව රම, අඩ වට...",[ශිරාන් බාසික් නිදොස් කොට නිදහස්. ප්‍රධාන මත්ද...
4,3,7,3_අයව_රත දන_අධ පන_පන රත,"[අයව, රත දන, අධ පන, පන රත, බඳවද, අයව රත, 2026,...",[සියලු මන්ත්‍රීවරුන්ට අධ්‍යාපන ප්‍රතිසංස්කරණ ග...
5,4,7,4_අග_අග යවර_අග ආච_ආච හර,"[අග, අග යවර, අග ආච, ආච හර, යථ තත, රව යමය, තත ව...",[ජීවිත ගොඩනගන්න නිලධාරීන්ගේ කාර්යක්ෂම සහය අවශ්...
6,5,7,5_කම වන_කම_චය සභ_අර ධක,"[කම වන, කම, චය සභ, අර ධක, ධක අරම, 200ක, රජය, ව...",[වතු කම්කරුවන් ගැන කම්කරු විනිශ්චය සභාව දුන් න...
7,6,7,6_ටලය_හග_රව රම_හග නය,"[ටලය, හග, රව රම, හග නය, රව, රව සමඟ, ළඹ මධ, සන ...",[කෝණා සමග කුඩු සැඟවූ නෝනලා. පොලීසියට පෙන්වා පළ...
8,7,7,7_දමර_ඇළට_සය දමර_ටර රථය,"[දමර, ඇළට, සය දමර, ටර රථය, අනත රක, ගමන කරම, ටර...",[බිරිඳගේ හිස රැගෙන පොලීසියට ගිය අනිල්. වනවිට ස...
9,8,7,8_රම මල_මල_පර ෂකවරය_ෂකවරය,"[රම මල, මල, පර ෂකවරය, ෂකවරය, නවත, මල මහ, රස ලධ...",[රිමාන්ඩ් - ජනමතය නිවැරැදිද?. කිසියම් චෝදනාවකට...
10,9,7,9_කත යක_සභ ජන_කත_යක රය,"[කත යක, සභ ජන, කත, යක රය, ඉල අස, එර සභ, යක රයට...",[කෝප් කමිටු සාමාජිකයින් දිගින් දිගට ම ඉල්ලා අස...
11,10,7,10_පත රය_පත උසස_වන පත_පළම රශ,"[පත රය, පත උසස, වන පත, පළම රශ, අයද, උසස, යයන ස...",[උසස් පෙළ විශිෂ්ටයෝ මෙන්න. උසස් විභාග ප්‍රතිඵල...
12,11,7,11_කසල_ටයර_කසල බද_නගර සභ,"[කසල, ටයර, කසල බද, නගර සභ, ඔය නගර, ටන ඔය, ටන, ...",[හිටි හැටියේ වාහන දෙකක් ගිනිගෙන. බදුල්ල වැලිමඩ...
13,12,6,12_කඩ ගන_ගමන බවත_සට ගමන_පහළ කඩ,"[කඩ ගන, ගමන බවත, සට ගමන, පහළ කඩ, ළඹ මහන, ධන අධ...",[අතුරුගිරිය හුවමාරුව ජලයෙන් යටවෙයි. අතුරුගිරිය...
14,13,6,13_අනත වල_යත යක_සට වනය_අනත,"[අනත වල, යත යක, සට වනය, අනත, වනය යත, රක අනත, ය...",[බුජ්ගමුව ඔයට ජීප් රථයක් පෙරළී අයියයි මල්ලියි ...
15,14,6,14_උප_තර සල_ඉග_සල,"[උප, තර සල, ඉග, සල, අධ පනය, සල වල, අධ පන, ඨම, ...",[ජාත්‍යන්තර පාසල් නියාමනය නොකිරීමෙන් 'දරුවන්ට...
16,15,6,15_එරබද_erythrina_ෂම_එරබද කය,"[එරබද, erythrina, ෂම, එරබද කය, කන නය, gall was...",[බඩගින්න දරාගන්න බැරිව කුරුම්බා ගෙඩියක් බිව්වා...
17,16,6,16_රභ ජයස_නය දක_යවන ඩක_නවතම ගත,"[රභ ජයස, නය දක, යවන ඩක, නවතම ගත, ඉද යට, ගත වල,...",[ප්‍රභාත් ජයසූරිය ශ්‍රේණිගත කිරීම් හී ඉහළට - න...
18,17,6,17_යම ඉලක_බද ආද_ආද_වත යල,"[යම ඉලක, බද ආද, ආද, වත යල, ආද යම, වර ෂය, ආයතනය...",[බදු ආදායමේ කැපී පෙනෙන වර්ධනයක්. මෝටර් ආනයන ලි...
19,18,6,18_හන ආනයනය_හන_ආනයනය_ආනයන,"[හන ආනයනය, හන, ආනයනය, ආනයන, හන ආනයන, අඩ මක, කථ...",[පෙබරවාරි 01 සිට පෞද්ගලික පරිහරණය සඳහා වාහන ආන...
20,19,6,19_ආසන_ඡන_වරණය_බලව ගයට,"[ආසන, ඡන, වරණය, බලව ගයට, ගයට ආසන, සමස ඡන, ගන ඡ...",[මහ මැතිවරණය 2024: ජාතික ජන බලවේගයට ආසන 159ක ඓ...
21,20,6,20_තනයට_ලක ගලය_අත අඩ_ටහ,"[තනයට, ලක ගලය, අත අඩ, ටහ, අඩ වට, තවත කකර, ගල ත...",[ග්‍රෑන්ඩ්පාස් වෙඩි තැබීමට සැක දෙදෙනෙකු අල්ලයි...
22,21,6,21_ටර රථය_රථය_බද ගම_අපර,"[ටර රථය, රථය, බද ගම, අපර, රධ කකර, කහත, ඥවරය ඔහ...",[මෝටර් රිය කොල්ල කෑ කල්ලියේ දෙන්නෙක් අල්ලයි. ක...
23,22,6,22_සත පක_රන රමස_රමස_රමස ජන,"[සත පක, රන රමස, රමස, රමස ජන, රමස මහත, සමග බලව,...",[තවත් පැනිල්ලක් ගැන මනූෂගෙන් හෙළිදරව්වක්. සමගි...
24,23,6,23_තර අරම_අරම දල_අරම_imf,"[තර අරම, අරම දල, අරම, imf, දල, ලර, පහස කම, දල ...",[වොෂිංටන් නුවරින් එන සුබ පණිවුඩය. ලංකාවට තුන්ව...
25,24,6,24_ජල_ජල ශය_ශය රට_මල ජල,"[ජල, ජල ශය, ශය රට, මල ජල, ලක ජය, ෂක නර, රට මට,...",[රත්කිඳ ජලාශයේ වාන් දොරටු විවෘත කිරිමට ආසන්නයි...
26,25,6,25_ආභරණ_භරණ_කට යක_වර භරණ,"[ආභරණ, භරණ, කට යක, වර භරණ, ගම රකථන, යක වන, භරණ...",[ලූවර් කෞතුකාගාර කොල්ල කරුවන් අල්ලයි. සුප්‍රසි...
27,26,6,26_දඬ_දඬ වම_වම_ලත,"[දඬ, දඬ වම, වම, ලත, අන කරණය, වරදක, දණ, වය රප, ...",[ශාරීරික දඬුවම් අපරාධයක් බවට පත් කිරීමට අනුමැත...
28,27,6,27_පනත පත_පනත_බල පනත_බල,"[පනත පත, පනත, බල පනත, බල, twitter, බලශක, අන තර...",[මතභේදයට තුඩු දී ඇති විදුලිබල පනත් කෙටුම්පත ආණ...
29,28,5,28_වන හම_කට යක_යක වන_හන වන,"[වන හම, කට යක, යක වන, හන වන, සත අර, භටයන, වර ක...",[අරාබියේ විශාලතම ගුවන් යානා දෙක ආධාර රැගෙන මෙර...

In [21]:
# Inspect sample titles per topic
for topic_id, group in df[df["topic_id"] != -1].groupby("topic_id"):
    print(f"=== Topic {topic_id} ({len(group)} articles) ===")
    for title in group["title"].head(10):
        print(f"- {title}")
    print()

=== Topic 0 (11 articles) ===
- විදුලි බිල සියයට 30කින් අඩු කළ හැකියි
- බස් ගාස්තු පහළට
- බිල්පත් ගෙවීම් ගැන විදුලි පාරිභෝගිකයින්ට දැනුම්දීමක්
- විදුලි බල මණ්ඩලය ඉල්ලා සිටි 6.8%ක විදුලි ගාස්තු වැඩි කිරීම මහජන උපයෝගීතා කොමිසම ප්‍රතික්ෂේප කළේ ඇයි?
- වසර තුනකින් විදුලි ගාස්තු තවත් පහළට
- විදුලි ගාස්තු ඉහළ දැමීමේ තීරණය 15වැනිදා
- යෝජිත විදුලි ගාස්තු සංශෝධනය ගැන මහජන අදහස් ලබාගැනීම අද
- ලංවිම ප්‍රතිසංස්කරණ ඉදිරියට, පෞද්ලීකරණය නවතී
- විදුලි ගාස්තු සංශෝදනය ගැන සාවද්‍ය වාර්තා මණ්ඩලය ප්‍රතික්ෂේප කරයි
- සියයට 13.5ක විදුලි ගාස්තු වැඩිවීමක් ඉල්ලයි

=== Topic 1 (8 articles) ===
- ශ්‍රී ලංකා පොලිසියේ මානව හිම්කම් උල්ලංඝණ ලැයිස්තුව තවත් දිගු වෙයි
- පොලිස් නිලධාරියකු සිවිල් ඇඳුමින් කරන ක්‍රියාවන්හි වගකීමෙන් රජයට බැහැර විය නොහැකි බවට ශ්‍රේෂ්ඨාධිකරණයෙන් තීන්දුවක්
- මානව හිමිකම් කොමිසම සිය මානව හිමිකම් කඩකළ බවට එහි නිලධාරිනියක් අඛණ්ඩ සත්‍යග්‍රහයක නිරත වූයේ ඇයි?
- ශ්‍රී ලංකා පොලිසියේ මානව හිමිකම් උල්ලංඝන: වින්දිතයින්ට කෝටි 15ක් වන්දි ගෙවන්නට සිදු වූ පොලිස් නිලධාරීන් කවුද?
- රත්නපුර හිටපු දිසාපතිවරිය, පොලිසිය හා යුද හමුදාව ශ්‍රේෂ්ඨාධිකරණය හමුවේ මාධ්‍යවේදියෙකුගෙන් සමාව ගනී
- පොලිසියට මානව හිමිකම් පාඩමක් උගන්වන්න වෙයි ද?
- යුක්තිය අතරතුර වැරදීමකින් පුද්ගලයෙකුට මාංචු දමා ප්‍රශ්න කළ' පොලිස් නිලධාරීන් පිරිසක් ශ්‍රේෂ්ඨාධිකරණයේදී සමාව ඉල්ලති
- අපරාධකරුවෙකු යැයි සිතා ශ්‍රී ලාංකිකයෙකුට පහර දුන් මෙට්‍රොපොලිටන් පොලිස් නිලධාරියෙකුට අත්හිටවූ සිර දඬුවමක්

=== Topic 2 (8 articles) ===
- කෝටි 19 මත්ද්‍රව්‍ය සමග ඇල්ලූ තරුණයාගේ වාහන පොලිස් භාරයට
- දික්වැල්ලගේ තරග තහනම අවසන්
- කංජිපානි ලංකාවට ගේන්න බලය පවරන්නැයි හිටපු අයි පී දුමින්ද කියයි
- ඩුබායි මත්ද්‍රව්‍ය ජාලයක තවත් පුරුකක් අල්ලයි
- දෙහිබාලා අල්ලන්නැයි නියෝගයක්
- බඩෝවිට අසංකගේ මත්ජාවාරම මෙහෙයවු  කතුන් දෙකක් මාට්ටු
- ශිරාන් බාසික් නිදොස් කොට නිදහස්
- හෙරොයින් මත්කුඩු ළඟ තබා ගත් අයෙකුට ජීවිතාන්තය දක්වා සිර දඬුවම්

=== Topic 3 (7 articles) ===
- සියලු මන්ත්‍රීවරුන්ට අධ්‍යාපන ප්‍රතිසංස්කරණ ගැන උගන්වන්න යයි
- තැපැල් සේවාව නව මාදිලියකට ගෙන ඒම අත්‍යාවශ්‍යයි
- 2026 වසරේ අධ්‍යාපනය සඳහා අයවැයෙන් යෝජිත මුදල් බෙදී යන්නේ මෙහෙමයි
- ’’ආණ්ඩුවේ ප්‍රතිපත්ති’’ ක්‍රියාත්මක කිරීම ගැන සතුටුයි
- 2026 අයවැයෙන් සෞඛ්‍ය සඳහා මුදල් වෙන් කිරීමට යෝජනා කර ඇත්තේ මෙහෙමයි
- නිදහස් සෞඛ්‍යයට දක්වන අවධානය පොදු ප්‍රවාහනයටත් දෙන්න
- බන්ධනාගාර ගැටලු විසඳන්න ජනපති ප්‍රධානත්වයෙන් සාකච්ඡාවක්

=== Topic 4 (7 articles) ===
- ලංකාවට උදව් කරන බව විදෙස් රාජ්‍ය තාන්ත්‍රිකයෝ කියති
- රටින් එවන සහන බඩු ඉක්මනින් නිදහස් කරන්න ක්‍රමයක්
- ජෙයශන්කර්-හරිනි හමුවක්
- ලංකාව ගොඩනගන්න චීනයෙන් තල්ලුවක්
- ජීවිත ගොඩනගන්න නිලධාරීන්ගේ කාර්යක්ෂම සහය අවශ්‍යයි
- අගමැතිනිය චීන මහජන වීරයන් බලන්න යයි
- මියන්මාරයේ රඳවා සිටින ශ්‍රී ලාංකිකයින් බේරාගැනීමට තවත් පියවරක්

=== Topic 5 (7 articles) ===
- චිචීගේ රොකට් එක ගැන අගමැතිනියගේ හෙළිදරව්ව
- වතු කම්කරුවන් ගැන කම්කරු විනිශ්චය සභාව දුන් නිර්දේශ ක්‍රියාත්මක වෙයි ද ?
- වතු කම්කරු වැටුප ඉහළ දැමූ ගැසට් නිවේදනය යථාර්ථයක් වෙයි ද?
- වතු සමාගම්වල කම්කරුවන්ට රජයෙන් දීමනාවක් ගෙවීම නිවැරදි තීරණයක් ද?
- ’වත්ත’ ’නිදහස් ගම්මාන’ ලෙස වෙනස් කරයි
- රනිල් සහ හරිනි අතර වාග් සටන පිටුපස කතාව
- අර්ථ සාධක අරමුදල විශ්‍රාම වැටුපක් කරනවා ද? රජය කියන්නේ කුමක් ද?

=== Topic 6 (7 articles) ===
- මාතර හෝටලයකට පැන්න තිහගොඩ පොලීසිය ට චෝදනාවක්
- කෝටි 10ක මත්පෙති වවිනියාවේදී අල්ලයි
- ශාන් ගේ ගෝලයෙකු හෙරෝයින් සමග අත්අඩංගුවට
- කෝටි 14ක මත්ද්‍රව්‍ය සමඟ අයියා මලෝ මාට්ටු
- කෝටි 15ක මත්ද්‍රව්‍ය සමඟ තිදෙනකු අල්ලයි
- වැඩ තහනම් වූ පීසී කෝටි 8ක මත්ද්‍රව්‍ය සමඟ මාට්ටු
- කෝණා සමග කුඩු සැඟවූ නෝනලා

=== Topic 7 (7 articles) ===
- මෝටර් රිය ඇළට පෙරැළි මව -පියා -පුතා මරුට
- රිය අනතුරකින් 06 දෙනෙකු ජීවිතක්ෂයට
- සෞදියේ බස් අනතුරකින්  40ක් මරුට
- ඉන්දියාවේ නිපා පැතිරෙයි
- බිරිඳගේ හිස රැගෙන පොලීසියට ගිය අනිල්
- සයින්දමරුදු මෝටර් රථයක් ගසාන යයි: තිදෙනෙක් මරුට
- ඉන්දියාවේ රිය අනතුරකින් පුද්ගලයින් සිව්දෙනෙකුට දිවි අහිමි වෙයි

=== Topic 8 (7 articles) ===
- නාරම්මල වෙඩි තැබීමේ සිද්ධියේ SI යළි රක්ෂිත බන්ධනාගාරයට
- නාරම්මල පොලිස් වෙඩි තැබීම: සිවිල් ඇඳුමෙන් සැරසුණු පොලිස් නිලධාරියෙකුට සාමාන්‍ය වැසියෙකුට වෙඩි තැබිය හැකිද?
- ප්‍රේෂර් පම්පය අල්ලා මරුමුවට පත් සිද්ධියට මිතුරන් දෙදෙනා රිමාන්ඩ්
- නාරම්මල පොලිස් වෙඩි තැබීම: 'ලක්ෂ 10ක් දීලා අපි ගැන කිසිම දෙයක් හොයා බැලුවේ නැහැ'
- අණ නොතකා වාහනය පදවන්නන්ට උරුම වෙඩි කා මිය යාම ද?
- රතුපස්වල නඩු තීන්දුව අද
- රිමාන්ඩ් - ජනමතය නිවැරැදිද?

=== Topic 9 (7 articles) ===
- කෝප් සභාපති අයින් කරන්නැයි ඉල්ලා උපවාසයක් ?
- කෝප් කමිටු සාමාජිකයින් දිගින් දිගට ම ඉල්ලා අස් වන්නේ ඇයි?
- අනිවාර්යයෙන් ගෙදර යන්න වෙනවා  - අනුර කුමාර
- මහින්ද යාපා අබේවර්ධන: ශ්‍රී ලංකාවේ කතානායකවරුන්ට එරෙහි විශ්වාසභංග යෝජනාවලට මෙතෙක් සිදුවූ දේ
- ශ්‍රී ලංකා පාර්ලිමේන්තු ඉතිහාසයේ කතානායකවරුන් ගැන මේ කරුණු දන්නවා ද?
- කන්ටේනර්  පැන්නීම හොයන්න  විශේෂ කාරක සභාවක්
- රංග දිසානායක ගැන ඇත්ත කියන්න

=== Topic 10 (7 articles) ===
- ශිෂ්‍යත්ව ප්‍රතිඵලය දින 40කින්
- උසස් පෙළ ඉතිරි විෂයන්වලට දින නියම කරයි
- ශිෂ්‍යත්ව විභාගයේ පිළිතුරු පත්‍ර ඇගයීම 8 වැනිදායින් නැවත ඇරඹෙයි
- උසස් පෙළ ප්‍රතිඵල එළැඹෙන සඳුදාට පෙර
- උසස් පෙළ විශිෂ්ටයෝ මෙන්න
- උ.පෙළ විභාග පරීක්ෂකයන් ඔන්ලයින් තෝරයි
- සරසවි ප්‍ර වේශයට අයදුම් කිරීමට  සියයට 62ක් සුදුසුකම් ලබයි

=== Topic 11 (7 articles) ===
- හොරණ ටයර් කර්මාන්ත ශාලාවක ගින්නක්
- අහස වසාගත් කළු දුමට හේතුව මෙන්න
- හැටන් නගරසභාවේ කසළ බදුන්වලට ගිනි තියලා
- කොළඹ වරාය ආසන්නයේ ගින්නක්
- හොරගස්මුල්ලේ ටයර් වැඩපොළක ගින්නක්
- මහරගම වාහන අලංකරණ උපාංග අලෙවිසැලක ගින්නක්
- හිටි හැටියේ වාහන දෙකක් ගිනිගෙන

=== Topic 12 (6 articles) ===
- වැසුණු කඩුගන්නාව යළි විවෘත කෙරේ
- අතුරුගිරිය හුවමාරුව ජලයෙන් යටවෙයි
- ගාලු පාරේ කොටසක් වැසෙයි
- කඩුගන්නාව ගනේතැන්න මාර්ගය අදත් වසයි
- යක්කලදී ගිලා බැස්ස පාලම ප්‍රතිසංස්කරණය කරයි
- කොළඹ - මහනුවර මාර්ගය කඩුගන්නැවෙන් වහයි

=== Topic 13 (6 articles) ===
- ගත වූ මාස කිහිපය තුළ රිය අනතුරුවලින් ජීවිත 1,417ක් මරුට
- මාරක රිය අනතුරු 3ක් - පොලිස් නිලධාරියෙකුටත් දිවි අහිමි වෙයි
- කැබ් රථයක් ට්‍රැක්ටරයක ගැටීමෙන් දෙදෙනෙක් මරුට, පහකට තුවාල
- බුජ්ගමුව ඔයට ජීප් රථයක් පෙරළී අයියයි මල්ලියි මරුට
- යතුරුපැදියක් තාප්පයක ගැටී තරුණයින් දෙදෙනෙක් මරුට
- බසයේ ගැටී යතුරුපැදිකරු මරුට

=== Topic 14 (6 articles) ===
- උසස් පෙළ නොකර ම වයස අවුරුදු 19 වන විට උපාධිධරයෙක් වන්නේ කෙසේ ද?
- ශ්‍රී ලංකාවේ දුර්වල බදු ප්‍රතිපත්තිය දරුවන්ට අධ්‍යාපනය ලැබීමට ඇති අයිතියට බලපෑ බව හියුමන් රයිට්ස් වොච් වාර්තාවකින් අනාවරණය කරයි
- සා. පෙළ සිට ආචාර්ය උපාධිය දක්වා ඇති එක ම ගමන්මග - ශ්‍රී ලංකා යෝග්‍යතා මාර්ගෝපදේශකය
- ශ්‍රී ලංකාවේ රජයේ පාසල් දරුවන්ගෙන් 97%කට අහිමි වී ඇති ඉංග්‍රීසි මාධ්‍ය අධ්‍යාපනය
- වයස අවුරුදු 97දී ශාස්ත්‍රපති උපාධියක් හිමි කර ගත් ලීලාවතී බීබීසීයට කතා කරයි
- ජාත්‍යන්තර පාසල්  නියාමනය නොකිරීමෙන් 'දරුවන්ට ගැටලු රැසක්'; නියාමනය කිරීමට කළ යුත්තේ කුමක්ද?

=== Topic 15 (6 articles) ===
- කෘමියෙකු නිසා ශ්‍රී ලංකාවට අහිමි වූ 'අපේ එරබදු'
- බඩගින්න දරාගන්න බැරිව කුරුම්බා ගෙඩියක් බිව්වා': ගංවතුරට හසුවී පොල් ගසකට නැග දිවී බේරා ගත් ෂම්සුදීන්
- “රටේ ආහාර හිඟයක් ඇති වෙන්න ඉඩ තියන්නෙ නෑ”
- බිත්තර වී, පොහොර ටික ගන්න අත පයේ තිබ්බ දේවල් ඔක්කොම උකස් කරලා කුඹුරු වගා කළේ' : දිට්වා සුළි කුණාටුව හේතුවෙන් කෘෂිකර්මාන්තයට සිදුවූ හානිය කොපමණ ද?
- මේ වසරේදී පොල් අස්වැන්න අඩුවීමට හේතුව මෙන්න
- දිත්වා නිසා හානි වූ සත්ත්ව ගොවිපොළ සඳහා රු.මි. 3200ක් ගොවීන්ට ගෙව්වා

=== Topic 16 (6 articles) ===
- ප්‍රභාත් ජයසූරිය ශ්‍රේණිගත කිරීම් හී ඉහළට - නවතම ශ්‍රේණිගත කිරීම් මෙන්න
- කෞෂාල් සිල්වාට ප්‍රධාන පුහුණුකාර තනතුරක්
- යෙවාන්, ඩිලන්ත සහ මා වෙනුවෙන් සහය වෙන හැම ශ්‍රී ලාංකිකයෙකුට ම මං ස්තූති කරනවා'
- ප්‍රභාත් ජයසූරිය ඉදිරියට
- ජෝ රූට් අංක එක වෙයි
- ටෙස්ට් ශ්‍රේණිගත කිරීම්හී කමිඳු, චන්දිමාල්, ඇන්ජි, ප්‍රභාත් හිමි කරගත් ස්ථාන මෙන්න

=== Topic 17 (6 articles) ===
- අධිවේගයට ගත් ණය අධිවේගයේ ලාභයෙන් ගෙව්වොත් පියවන්න වසර 171ක් යනවා
- බදු ආදායමේ කැපී පෙනෙන වර්ධනයක්
- කර්මාන්ත අමාත්‍යාංශයෙන් භාණ්ඩාගාරයට කෝටි 75ක්
- ශ්‍රී ලංකා රේගුව 2025 වසරේ ආදායම් ඉලක්ක පසු කරයි
- ලංකාව සෞදියට කරන අපනයන සියයට 19කින් ඉහළට
- මේ වසරේ ගතවු මස නවයට වාර්තා ගත සුරාබදු ආදායමක්

=== Topic 18 (6 articles) ===
- අයවැයෙන් පොඩි මිනිහාට සහන පැකේජයක්
- වාහන ආනයනය සීමා කරන්නේ නෑ
- ණය ගැන මහ බැංකුවෙන් හෙළිදරව්වක්
- LC විවෘත කිරීම ශීඝ්‍රයෙන් පහළට: වාහන වෙළෙඳපොළ ගැන මහ බැංකුවෙන් පුරෝකථනයක්
- කලින් නියම කළ කාල රාමුවට ම වාහන ආනයනය කරන්න බැරි වෙයි ද?
- පෙබරවාරි 01 සිට පෞද්ගලික පරිහරණය සඳහා වාහන ආනයනයට ඉඩ

=== Topic 19 (6 articles) ===
- බ්‍රිතාන්‍යය ට නව අගමැතිවරයෙක්
- මහ මැතිවරණය 2024: සජීවී නිල ප්‍රතිඵල මෙතැනින්
- මැතිවරණ පැමිණිලි තවත් ඉහළ ට
- මහ මැතිවරණය 2024: ඡන්දය දෙන්න කලින් මේ ගැන දැන ගන්න
- මහ මැතිවරණය 2024: ජාතික ජන බලවේගයට ආසන 159ක ඓතිහාසික ජයක්!
- 2024 මනාප ඡන්ද: පාර්ලිමේන්තුවට තේරී පත්වූ මන්ත්‍රීවරුන් මෙන්න

=== Topic 20 (6 articles) ===
- කොටහේන ඝාතනයට හයක් අල්ලයි
- දෙහිවල ඝාතනයක වෙඩික්කරු මාට්ටු
- බෙලිඅත්තේ පංච පුද්ගල ඝාතනයට තවත් තිදෙනෙක් අත්අඩංගුවට
- ග්‍රෑන්ඩ්පාස් වෙඩි තැබීමට සැක දෙදෙනෙකු අල්ලයි
- බෙලිඅත්ත ඝාතනයේ තවත් සැකකරුවෙක් අත්අඩංගුවට
- ඝාතනයක් සම්බන්ධයෙන් අයෙක් අල්ලයි

=== Topic 21 (6 articles) ===
- බුල්නෑව නිවසක් බිඳ ජීප් රථයක්, රන් භාණ්ඩ හා මුදල් කෝල්ල කෑ සැකකරුවන් අල්ලයි
- නීතිඥවරයා හා බිරිඳ ඝාතනයට පැමිණි මෝටර් රථය ගැන තොරතුරු රැසක් හෙළිවෙයි
- මෝටර් රිය කොල්ල කෑ කල්ලියේ දෙන්නෙක් අල්ලයි
- යතුරු පැදි සොර කල්ලියක කාන්තාවන් දෙකක් ඇතුළු 11ක් අල්ලයි
- පච්චයන් තිදෙනෙකු අත්අඩංගුවට
- මෝටර් රිය කොල්ලකෑමේ සිද්ධියේ ප්‍රධාන සැකකරු අල්ලයි

=== Topic 22 (6 articles) ===
- නිදහසින් පසු ආව සෑම රාජ්‍ය නායකයෙක්ම අකල් මරණවලට ගොදුර කර තිබෙනවා
- රුවන් -එ,ජා නේවාසික සම්බන්ධීකාරක හමුවක්
- එජාපය අලුත් තනතුරු දෙකක් පිහිටුවයි
- ’’එකතුවට බාධාව මම නම් යන්න සූදානම්’’
- ලලිත් එල්ලාවල දේශපාලනයෙන් සමුගනී
- තවත් පැනිල්ලක් ගැන මනූෂගෙන් හෙළිදරව්වක්

=== Topic 23 (6 articles) ===
- IMF: නව ආණ්ඩුව සමග පැමිණි එකඟතා මොනවා ද?
- රජය සිදුකරන ප්‍රතිසංස්කරණවල ප්‍රගතිය අගය කරනවා - අයි.එම්.එෆ්.
- අයිඑම්එෆ් පළමු නියෝජ්‍ය කළමනාකාර අධ්‍යක්ෂිකාව ලංකාවේ සංචාරයක
- වොෂිංටන් නුවරින් එන සුබ පණිවුඩය
- IMF: ශ්‍රී ලංකාවට වාහන ආනයනයට මාර්ග සිතියමක්
- ලෝක බැංකුවෙන් ලංකාවට ඩොලර් මිලියන 150ක මූල්‍ය පහසුකමක්

=== Topic 24 (6 articles) ===
- නොරොච්චෝලේ යන්ත්‍ර දෙකක් නවතයි
- කොත්මලේ මඩ සොරොව්ව විවෘත කරයි
- කොල්මලේ ජලාශ වේල්ල මතින් බර වාහන ධාවනය තහනම් කරයි
- රත්කිඳ ජලාශයේ වාන් දොරටු විවෘත කිරිමට ආසන්නයි
- රාජාංගණයේ වාන් දොරටු 22ක් විවෘත කරයි
- කොත්මලේ දොරටු දෙකක් ඇරේ

=== Topic 25 (6 articles) ===
- රාජසන්තක කළ අයි ෆෝන් සහ ලැප්ටොප්
- ලූවර් කෞතුකාගාර කොල්ල කරුවන් අල්ලයි
- ගුවන් යානය තුළ විදෙස් මුදල් හා ස්වණාභරණ සොරකම් කළ චීන ජාතිකයා අත්අඩංගුවට
- රත්‍රං කිලෝ 9ක් සමග දෙදෙනෙක් ගුවන් තොටේ දී මාට්ටු
- කෝටි 12ක රන් ආභරණ සමග ව්‍යාපාරිකයන් දෙදෙනෙක් අල්ලයි
- කෝටියක ජංගම දුරකථන-සුවඳවිලවුන් සමඟ 4ක් දැලේ

=== Topic 26 (6 articles) ===
- රංගන ශිල්පියෙකුගේ රංගන ශෛලිය අනුකරණය කිරීම අපරාධමය වරදක්ද?
- ශ්‍රී ලංකාවේ සිදුවන භික්ෂූත්වයෙන් නෙරපීමේ ක්‍රියාවලිය කෙබඳු ද?
- ශාරීරික දඬුවම්වලට එරෙහි කෙටුම්පතේ ඇත්තේ මොනවා ද? එහි ඔබේ දරුවන්ගේ යහපතට බලපාන 'බරපතළ සංවේදී කරුණු' තිබේ ද?
- ශාරීරික දඬුවම් අපරාධයක් බවට පත් කිරීමට අනුමැතිය: රන්ජන් රාමනායකගේ අත්දැකීම
- දඬුවම් පනත බිල්ලෙක්ද?
- සාපරාධී ක්‍රියාවක්' වූ පාරට බුලත් කෙළ ගැසීමේ නීතිය ගැන ඔබ දන්නවා ද?

=== Topic 27 (6 articles) ===
- මතභේදයට තුඩු දී ඇති විදුලිබල පනත් කෙටුම්පත ආණ්ඩුක්‍රම ව්‍යවස්ථාවට පටහැනි වන්නේ කෙසේද ?
- විදුලිබල පනත් කෙටුම්පත සම්මතයි: දැන් සිදුවන්නේ කුමක් ද?
- විදුලියේ වර්ජකයන්ට ජනපතිගෙන් රතු එළියක්
- ඉන්දියාව එක්ක අත්සන් තැබූ ගිවිසුමේ පිටපතක් දෙන්න
- ශ්‍රී ලංකාව ඉන්දියාවේ කොටසක් ද? :'හරින් ඇමතිකමෙන් නෙරපිය යුතුයි'
- ඉන්දියාව හා යුරෝපා සංගමය නිදහස් වෙළඳ ගිවිසුමකට එයි

=== Topic 28 (5 articles) ===
- මධ්‍යම අප්‍රිකානු සෙබළුන් 14ක් බේරාගත් ලංකා ගුවන් හමුදා මෙහෙයුම
- ආපදාවට සහන සලසන්න ඇමෙරිකා යානා දෙකක් එයි
- අරාබි භූමි මෙහෙයුම් නිමාවට
- අරාබියේ විශාලතම ගුවන් යානා දෙක ආධාර රැගෙන මෙරටට
- ආධාර රැගත් තවත් යානයක් කටුනායකට

=== Topic 29 (5 articles) ===
- නිදහස් පක්ෂය ප්‍රමුඛ නව සන්ධානයේ නායකත්වය ගැන අර්බුදයක්
- දුමින්ද ශ්‍රීලංනිප වැඩබලන මහ ලේකම් ධුරයට
- ශ්‍රීලනිප සභාපතිවරයා වශයෙන් පත්වී සිටින විජයදාසට එරෙහිව දුමින්ද ඉල්ලා සිටින වාරණ නියෝග නිකුත් කිරීම අධිකරණය ප්‍රතික්ෂේප කරයි
- ශ්‍රීලනිප මූලස්ථානයේ ආරක්ෂාව තර කෙරේ
- මෛත්‍රී ශ්‍රී ලනිප සභාපති ධූරයෙන් හදිසියේ ඉල්ලා අස්වූයේ ඇයි? ඉදිරියට කුමක් වෙයි ද?

=== Topic 30 (5 articles) ===
- අම්බලන්ගොඩ වෙඩි තැබීමකින් අයෙක් මරුට
- ඝාතන රැසක වෙඩික්කරුවෙක් මාට්ටු
- දරුවන් ඉදිරියේ පියාට තැබූ වෙඩිල්ල ගැන තවත් තොරතුරු
- සමගි ජන බලවේගයේ අම්බලන්ගොඩ නගරාධිපති අපේක්ෂකයා වෙඩි තබා ඝාතනය කෙරේ
- අම්බලන්ගොඩදී වෙඩි තබා ඝාතනය කළ ධීවර ව්‍යාපාරිකයා කවුද?

=== Topic 31 (5 articles) ===
- අවු. 14ක දරුවෙක් දියේ ගිලී මරුට
- දියේ ගිලි දෙදෙනෙක් මරුට
- 11වැනිදා නිවසින් අතුරුදන්වූ මදුෂාන් කොත්මලේ ජලාශයට ආවේ කොහොමද ?
- කලවානේ ළිඳකින් සිරුරක් හමුවෙයි
- මහජන සෞඛ්‍ය පරීක්ෂකවරුන් දෙදෙනෙක් මරුට

=== Topic 32 (5 articles) ===
- බදුල්ලේ වැව් අමුණු ඇළ මාර්ග 920 ක් විනාශයි
- බදුල්ලේ 82ක් මරුට
- ‘‘දිට්වා‘‘ කුණාටුවෙන් දරුවන් 2,75,000 පීඩාවට
- කොත්මලේ අවතැන් වූ පිරිසක් පහසුකම් ඉල්ලා උද්ගෝෂණයක
- මහනුවර පවුල් 633ක පුද්ගලයන් 2135ක් තවමත් අවතැන් කඳවුරුවල

=== Topic 33 (5 articles) ===
- ඉතාලි රියැදුරු බලපත්‍රය: 'ඩ්‍රයිවින් කරන රස්සාවක් හොයාගන්න තිබුණා ලයිසන් එක තිබුණා නම්. එහෙනම් මේ සීතලේ මැරෙන්න වෙන්නේ නෑ'
- පාස්පෝට් අර්බුදයට සඳුදා සිට තිත
- ලෝකයේ ගන්න අමාරු ම ශ්‍රී ලංකාවේ පාස්පෝට් එක ද?
- ඔක්තෝබරයේ පාස්පෝට් වෙනස් වෙයි
- අද සිට සිදුවන ගාස්තු වෙනස

=== Topic 34 (5 articles) ===
- අලුත් වුණ තල්පේ දුම්රිය ස්ථානය ජනතා අයිතියට
- මත්තල ගුවන්තොටට හොද සහතිකයක්
- මත්තල ගුවන්තොට සමාගම් තුනකට
- ඇමතිලා දෙන්නෙක් අහසින් බේරෙට
- තලල්ල වෙරළ ජාත්‍යන්තරයට

=== Topic 35 (5 articles) ===
- ඉන්දුනීසියානු රජයට එරෙහිව පැවති විරෝධතා තවත් දරුණු අතට
- මියන්මාර - ඉන්දියානු දේශසීමාව ආසන්නයේ ප්‍රබල භූකම්පනයක්
- ඉන්දියන් සාගර සුනාමියෙන් 20 වසරකට පසු: එය සිදු වූයේ කෙසේ ද? සුනාමි ගැන අප දන්නේ මොනවා ද?
- ඉන්දුනීසියාවේ මගී නෞකාවක ගින්නක්
- ඉන්දුනීසියාවේ භූමිකම්පාවක්: සුනාමි අනතුරු

=== Topic 36 (5 articles) ===
- දුම්රියේ ගැටී පුද්ගලයෙක් මරුට
- එකම දුම්රියට තැන් දෙකකදී ජීවිත දෙකක් බිලි
- දුම්රියේ ගැටී පුද්ගලයෙකු මරුට
- කොටුව දුම්රියපොළ ඉදිරිපිට නාඳුනන මළ සිරුරක්
- යතුරුපැදියක් දුම්රියේ ගැටී කාන්තාවක් ජීවිතක්ෂයට

=== Topic 37 (5 articles) ===
- රාජ්‍ය පරිපාලන වැය ශීර්ෂය සම්මතයි
- නාවුල අයවැයත් පරදී
- කරුවලගස්වැව අයවැයට විපක්ෂයේ හතරකගේ සහාය
- පදියතලාව ප්‍රා. සභා අයවැය දෙවන වරටත් පරාදයි
- කොළොන්න ප්‍රා.සභා අය වැය දෙවනවරටත් පරදි

=== Topic 38 (5 articles) ===
- නාකොටික් නව අධ්‍යක්ෂ SSP හේරත්
- පතිනායක ඉවත් කරන්න පොලිස් කොමිසමේ අනුමැතිය
- උප්පුවේලි වැඩ බැලූ ස්ථානාධිපති සේවයෙන් පිටව යෑම ගැන පරීක්ෂණයක්
- ඉහළ පොලිස් නිලධාරීන් පිරිසකට ස්ථාන මාරුවීම්
- පොලිසියේ ලොකු පුටු මාරුවෙන් කාන්තා නිලධාරිනියන්ට ලොකු වගකීම්

=== Topic 39 (5 articles) ===
- හමුදා සෙබළා වෙඩි වැදී රෝහලේ
- බීමත් රෝගීයා හෙදියකට පහරදී රෝහලෙන් පලායයි
- ජනේලයෙන් වෙඩි තබා ගිය වෙඩික්කරුගේ ඉලක්කය වරදී
- සංගීත ප්‍රසංගයකදී ගායන ශිල්පී නදිමාල්ට පහරදුන් අයෙකු අත්අත්අඩංගුවට
- පුද්ගලයෙක් ඇතුගලින් ඇදවැටෙයි

=== Topic 40 (5 articles) ===
- පොලිසියට ආරක්ෂාව ලබා දෙන්න පුළුවන් කාට ද?
- මිදිගම ලසා වෙඩි ප්‍රහාරයකින් මරුට
- සමගි ජනබලවේගයේ වැලිගම ප්‍රාදේශීය සභාවේ සභාපති ලසන්ත වික්‍රමසේකර කාර්යාලය තුළදී  වෙඩි තබා ඝාතනය කරයි
- ‘‘ලසාගේ‘‘ වෙඩික්කරු අත්අඩංගුවට ගත් නිලධාරීන් ගැන විමර්ශනයක්
- ලසන්ත වික්‍රමතුංග: ' දැන් මේ මහා ලොකුවට යුක්තිය යුක්තිය කිව්වට කෝ යුක්තිය ලසන්ත ට?'

=== Topic 41 (5 articles) ===
- ඉෂාරා සෙව්වන්දි නේපාලයේදී අත්අඩංගුවට
- අමිතිරිගල ත්‍රිත්ව ඝාතනයට මන්නා රමේෂ්ගේ සමීපතමයන් 2ක් අල්ලයි
- දින හතරක මෙහෙයුමකින් 'ඉෂාරා සෙව්වන්දි' නේපාලයේදී අත්අඩංගුවට ගත් හැටි
- මිදිගම රුවන් කළ අපරාධ ගැන ප්‍රශ්න කරයි
- ගණේමුල්ල සංජීවගේ මත්ද්‍රව්‍ය ජාලයේ දෙදෙනෙක් කොටුවෙති

=== Topic 42 (5 articles) ===
- ඇමැති බංගලා 4ක් මහාධිකරණවලට
- මහාධිකරණවලට ලබා දුන් රජයේ නිල නිවාසවල මීට පෙර සිටි ඇමැතිවරුන් කවුද?
- රුපියල් මිලියන 168,000 ක භාණ්ඩාගාර බිල්පත් වෙන්දේසියක්
- නඩු වැඩ ඉක්මන් කරන්න අභියාචන මහාධිකරණයක්
- ඇමති බංගලා හතරක් අගවිනිසුරුවරයාට භාරදෙයි

=== Topic 43 (5 articles) ===
- අනුරත් ඇප තියයි
- නීතිය ශක්තිමත් කරන බවට අනුරගෙන් සහතිකයක්
- වැට් බදු සම්පූර්ණයෙන්ම ඉවත් කරනවා
- අනුර අපුරේ ආගමික වතාවත්වල
- ආණ්ඩුවේ බලාපොරොත්තු සුන් කරමින් නුගේගොඩ මහා හිස් ගොඩක් බවට පත් වුණා

=== Topic 44 (5 articles) ===
- ලෝක කුසලානය අතරේ ක්‍රිකට් තරු දෙකක් විවාහ ගිවිස ගනිති
- Lanka T10: අත්අඩංගුවට පත් ගෝල් මාවල්ස් හිමිකරුගෙන් අධිකරණයට රහස් ප්‍රකාශයක්
- ලෝක කුසලානය අතරේ ක්‍රිකට් තරුදෙකක් ගල්කිස්ස හෝටලයේදි අතිනත ගනිති
- මෙසීව හරි හැටි බලන්න බැරි වුණැයි කලහයක්
- ක්‍රිකට් ක්‍රීඩකයන්ට වැඳ නමස්කාර කිරිමට පල්‍ලේකැලේදි පිටිය මැදට ආපු තරුණයා

=== Topic 45 (5 articles) ===
- ශ්‍රී ලංකාවට සුවිශේෂී වූ අලි ඇතුන් බොහොමයක් මරා දමන්නේ ඇයි ?
- වසරකට දෙවරක් ගල්ඔය සිට කුමනට සිදුවන අලි සංක්‍රමණය ඔබ දැක තිබේ ද?
- දවල්ට අව්ව - රෑට අලි, පීඩාව දරාගෙන වැවූ අස්වැන්නට මිලක් නැතිව රජරට ගොවියෝ ලතැවෙති
- අලි පන්නන්න හැදූ කුටි කැලෑවට
- කොළඹ දෙහි කිලෝව 2000යි රජරට දෙහි විකුණගන්නත් බෑ

=== Topic 46 (5 articles) ===
- උන්ඩියල් හා හවාලා ක්‍රියාකරුවන්ට මහ බැංකුවේ ලියාපදිංචි වෙන්න කියයි
- හිටිහැටියේ කෝටිපතියන් බිහි කරන කළු සල්ලි සුදු වෙන්නේ කොහොමද?
- ශ්‍රී ලංකාවේ දළ නිල සංචිත ඩොලර් බිලියන 7 කඩඉම පසු කිරීමට නොහැකි වීමට හේතු
- වසරකට සංචාරකයන් මිලියන 4ක ඉලක්කයක්
- මහ බැංකුව අලුතින් මුදල් අච්චු ගැහුවා ද?

=== Topic 47 (5 articles) ===
- 2025 වසරේ පාර්ලිමේන්තුවේදී සම්මත කර ගත් පනත් මොනවා ද?
- රන්මිහිතැන්න පෞද්ගලික ආයෝජනයකට
- බැංකු දෙකක් ප්‍රතිව්‍යුහගත කරයි
- දූෂණ විරෝධී පනත වෙනස් කිරීමට කළ යෝජනාවට කැබිනට් අනුමැතිය
- ආයෝජන ආරක්‍ෂණයට අලුත් පනතක් එයි

=== Topic 48 (5 articles) ===
- ජන අරගල සන්ධානය : 'ගෝල්ෆේස් අරගලකරුවන්' රැසක් සමග දේශපාලන කරලියට එන නව සන්ධානය
- ජනාධිපතිවරණයෙන් දිනන අලුත් ජනපතිට මේ අභියෝග දිනන්න හැකි වෙයි ද?
- ජාතික ජන බලවේගයට තුනෙන් දෙක ඉක්මවූ බලයක් දීමෙන් ජනතාව දුන් පණිවුඩය කුමක් ද?
- අනුර කුමාර දිසානායක : 'ප්‍රභූ තන්ත්‍රයේ ආරක්ෂාව ද? පොදු ජනතාවගේ අපේක්ෂාව ද? තීන්දුවක් ගන්න'
- නව රජයේ පැවැත්ම තීරණය කරන නව අභියෝග සහ ඒවා ජය ගැනීමට ඇති බාධා මොනවා ද?

=== Topic 49 (5 articles) ===
- අතුරුදන්වූවන්ගේ ඥාතීන්ගේ විරෝධතාවට වසර 7: 'ජාත්‍යන්තර විමර්ශනයක් අවශ්‍යයයි'
- උතුරේ හා නැගෙනහිර 'කළු නිදහස් දින' විරෝධතා වලට බාධා; යාපනය විශ්වවිද්‍යාල සිසුන් හතරක් අත්අඩංගුවට
- වෙරුගල්ආර ප්‍රා.ලේ.කාර්ය මණ්ඩලය සිර කර තැබීමට එරෙහිව අදත් විරෝධතා
- නෝර්වුඩ්  ප්‍රා.ලේ සේවකයින් උද්ඝෝෂණයක
- අධ්‍යාපන අමාත්‍යාංශය ඉදිරිපිට විරෝධතාවය විසුරුවාහැරීමේදී උණුසුම් තත්ත්වයක්

=== Topic 50 (5 articles) ===
- හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් ගැන ආරංචියක්
- අමෙරිකානුවන් සිව් දෙනෙක්ට චීනයේදී පිහි ප්‍රහාරයක්
- හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් දෙදෙනා ඇතුළු කාර්ය මණ්ඩලය බේරා ගැනෙයි
- හූති ප්‍රහාරයට ලක්වූ නැවේ සිටි 21ක් මුදාගනී
- ලෙබනනයේ යුද අත්දැකීම් ලැබූ ලාංකිකයා : 'වටේටම බෝම්බ දාන නිසා අපි එහෙන් ආවා'

=== Topic 51 (5 articles) ===
- ජනපති බුද්ධගයාව වැඳ පුදා ගනී
- සංචාර,රත්රන් මිලට ගැනිම, ඉන්ධ භාවිතය, ආනයන, පොහොර භාවිතය සීමා කරන ලෙස මෝදි ජනතාවට කියයි
- මෝදිගෙන් අනුරට විශේෂ ලිපියක්
- ජනපති අනුරගේ ඉන්දිය සංචාරය අද
- ජනපති ට ඉන්දියාවෙන් උණුසුම් පිළිගැනීමක්

=== Topic 52 (5 articles) ===
- දින 8කින් ලංකාව පුරා තනිව සංචාරය කළ චිත්‍ර ශිල්පිනිය සමන්මලී ලැබූ අත්දැකීම්
- පුංචි මොස්කව්' බවට පත්වූ උණවටුනේ 'සුදු මුහුණු සාදය'
- දුම්රිය සේවයට කාන්තාවන් බඳවා ගැනීමට කැබිනට් අනුමැතිය: බඳවා ගන්නා තනතුරු මොනවා ද?
- විදෙස් රටකට යාමට ගුවන් තොටුපළට යන ඔබව ආපසු හරවා එවන්න පුළුවන් කාට ද?
- කාන්තාවන්ට තනිව සංචාරය කිරීමට ශ්‍රී ලංකාව ආරක්ෂිතද? සමාජ කථා බහක් මතුව ඇත්තේ ඇයි?

=== Topic 53 (5 articles) ===
- කාන්තා T20 ක්‍රිකට් ලෝක කුසලානය: වාර්තාගත උඩපන්දු ගිලිහී යාමට හේතුව කුමක් ද?
- T20 කාන්තා ලෝක කුසලානය : ශ්‍රී ලංකා කණ්ඩායමේ සූදානම කොහොමද?
- ජාතික ක්‍රිකට් ක්‍රීඩකයෙකුට අත්වූ ඛේදනීය ඉරණම
- පිරිමින්ට පෙර කාන්තාවන් පිහිටවූ සුවිශේෂී ක්‍රිකට් වාර්තා 10ක්
- චමරී අතපත්තු යළිත් අසාර්ථක වෙයි: දෙවන තරගයෙනුත් ශ්‍රී ලංකාවට පරාජය

=== Topic 54 (5 articles) ===
- තිස්සමහාරාම වෙඩි තැබීමකින් අයෙක් මරුට
- වෙඩි වැදීමකින් අයෙක් මරුට
- දෙහිවල වෙඩිතැබීමෙන් තුවාල ලැබූ පුද්ගලයා මරුට
- සෝපානයකින් වැටී පුද්ගලයෙක් මරුට
- පිහි ඇනුමකින් අයෙක් මරුට

=== Topic 55 (5 articles) ===
- පේරේ මුහුණ දුන් තත්ත්වය උප කුලපති කියයි
- ජල ගැල්මෙන් පේරාදෙණිය  සරසවියට කෝටි 300ක පාඩුවක්
- ජලයට කොටූ  පේරේ සිසුන් දුෂ්කරතාවන්ට
- අග්නිදිග සරසවි සිසුන් 125ක් ආපනශාලාවක රැය පහන් කරයි
- වයඹ සරසවි වෙද සිසුන්ට ඉන්න තැනක් හදයි

=== Topic 56 (5 articles) ===
- පුද්ගලයකුගේ දත් හතරක් කැඩූ ප්‍රා. මන්ත්‍රීට ඇප
- අර්චුනා හඬා වැටෙයි
- අලි සබ්රි රහීම් ට ඇප
- අර්චුනා කැබ් රථය  පිනට දෙයි
- මන්ත්‍රී අර්චුනාට ඇප

=== Topic 57 (5 articles) ===
- පාසල් සිසුවියක් අතුරුදන්
- මහනුවර දරුවන් දෙදෙනෙක් අතුරුදන්
- සාපෙළ ලියන්න ගිය සිසුවියන් දෙදෙනා අතුරුදන්
- දරුවන්ගේ ආරක්ෂාව තුට්ටු දෙකට දැමූ බලධාරීන්
- පිහියකින් ඇන 16 සිසුවිය මරලා

=== Topic 58 (5 articles) ===
- රෝහිතගේ බෑනා රිමාන්ඩ් - ජගත්ගේ පුතාට ඇප
- උතුරේ සිවාජිලින්ගම්ට එක නීතියක්. දකුණට වෙන නීතියක් ද?'
- අර්ජුන මහේන්ද්‍රන් ඕනෑ: සිංගප්පූරුවට දන්වයි
- මහජන ආරක්ෂක ඇමතිට විශ්වාස භංගයක් ?
- විපක්ෂයේ පක්ෂ විශේෂ සාකච්ඡාවක

=== Topic 59 (5 articles) ===
- යුක්තියෙන් රැකියාත් ලබාදෙයි
- රතු වරෙන්තු: අපරාධකරුවන් මෙරටට ගෙන්වා ගන්නේ කෙසේද ?
- පාතාලේ 43කට ජාත්‍යන්තර රතු නිවේදන
- පාතාලකරුවන් කොටු කරන්න ගුවන් නාවික මෙහෙයුමක්
- කන්ජිපානිට සහ ගනේමුල්ලේ සංජීවට රටින් පැනයෑමට උපකාර කළ නීතිඥයින් ගැන පොලීසිය භාර ඇමති කියයි

=== Topic 60 (5 articles) ===

In [22]:
# Save article-level assignments and topic summaries
assignments_path = RESULTS_DIR / "bge_m3_bertopic_assignments.csv"
topics_path = RESULTS_DIR / "bge_m3_bertopic_topics.csv"

df.drop(columns=["document"], errors="ignore").to_csv(assignments_path, index=False, encoding="utf-8-sig")
topic_info.to_csv(topics_path, index=False, encoding="utf-8-sig")

print(f"Saved assignments: {assignments_path.resolve()}")
print(f"Saved topics: {topics_path.resolve()}")

Saved assignments: /kaggle/working/results/bge_m3_bertopic/bge_m3_bertopic_assignments.csv
Saved topics: /kaggle/working/results/bge_m3_bertopic/bge_m3_bertopic_topics.csv

In [23]:
# Optional BERTopic visualizations
# These are useful in Jupyter/Colab but can be slow for large corpora.

# topic_model.visualize_topics()
# topic_model.visualize_barchart(top_n_topics=20)
# topic_model.visualize_hierarchy()