# multilingual-e5-large + UMAP + K-Means (auto-k)

Pairs the finalized embedding model, `multilingual-e5-large`, with **K-Means**. Motivated by a
short-text clustering benchmark (arXiv:2511.19350) finding K-Means, given a good cluster-count
estimate, significantly outperforms parameter-light methods like HDBSCAN/OPTICS.

K-Means needs k up front — here we sweep a wide range (10 to ~900, since events in this corpus tend
to form many small clusters) and keep whichever k maximizes silhouette score.

In [1]:
!pip install -q umap-learn

In [2]:
# Paths (Kaggle)
import pandas as pd
import numpy as np
import re
import unicodedata
from pathlib import Path

SEED = 42
np.random.seed(SEED)

DATA_DIR = Path("/kaggle/input/datasets/uom230425m/aggregation-pipeline-data/data")
RESULTS_DIR = Path("/kaggle/working/results/e5_kmeans")
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

print(f"Data dir: {DATA_DIR.resolve()}")
print(f"Results dir: {RESULTS_DIR.resolve()}")

Data dir: /kaggle/input/datasets/uom230425m/aggregation-pipeline-data/data
Results dir: /kaggle/working/results/e5_kmeans

In [3]:
# Load annotator files
df_a = pd.read_csv(DATA_DIR / "a.csv")
df_d = pd.read_csv(DATA_DIR / "d.csv")
df_p = pd.read_csv(DATA_DIR / "p.csv")

for frame in (df_a, df_d, df_p):
    frame.drop(columns=["bias_label"], inplace=True, errors="ignore")

print(df_a.shape, df_d.shape, df_p.shape)

(750, 6) (750, 8) (800, 6)

In [4]:
# Concatenate dataframes and drop duplicate articles by article_id
df = pd.concat([df_a, df_d, df_p], ignore_index=True, sort=False)
df = df.drop_duplicates(subset="article_id", keep="first").reset_index(drop=True)
df.drop(columns=["flags", "Unnamed: 8"], inplace=True, errors="ignore")

print("df shape:", df.shape)
df.head()

df shape: (2000, 6)

,article_id,publisher,url,published_at,title,body_text
0,f92797eb-a338-5886-a45a-66f01292a912,Lanka Deepa,https://www.lankadeepa.lk/news/දන-තර-මර-අහවන-ක...,2025-09-26 00:00:00+00:00,දැන් තෝරු-මෝරු අහුවෙන කාලේ,දැන් තෝරු-මෝරු අහුවෙන කාලේ\n\nදැන් හාල්මැස්සො ...
1,5c7946aa-a810-59e2-a126-ff58347aad21,BBC Sinhala,https://www.bbc.com/sinhala/articles/c0vy04qd14yo,2024-01-17 00:00:00+00:00,අවුරුදු 67යි. ඇස් දෙකම පේන්නේ නෑ. මම පොල් කඩනවා',අවුරුදු 67යි. ඇස් දෙකම පේන්නේ නෑ. මම පොල් කඩනව...
2,6fc575d1-2be5-5d49-be20-c846617bdacd,Ada,https://www.ada.lk/breaking_news/පිදුරංගල-ගිය-...,2026-02-17 00:00:00+00:00,පිදුරංගල ගිය විදේශිකයා වන අලි ප්‍රහාරයෙන් මරුට,පිදුරංගල ගිය විදේශිකයා වන අලි ප්‍රහාරයෙන් මරුට...
3,47965836-064f-530a-a34d-02f6898fb94a,Ada Derana Sinhala,http://sinhala.adaderana.lk/news/194266,2024-03-07 00:00:00+00:00,හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් ගැ...,හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් ගැ...
4,132990f7-a4f4-54ba-8b12-b469d9803bde,Ada Derana Sinhala,http://sinhala.adaderana.lk/news/195779,2024-04-19 00:00:00+00:00,ස්ථාන දෙකකදී ඝාතන දෙකක්,ස්ථාන දෙකකදී ඝාතන දෙකක්\n\nකුලී නිවසක පදිංචිව ...

In [5]:
# Keep rows with the fields required for clustering
required_columns = ["article_id", "publisher", "url", "published_at", "title", "body_text"]
df = df.dropna(subset=required_columns).copy()

print("df shape after required-field dropna:", df.shape)
df.info()

df shape after required-field dropna: (1999, 6)
<class 'pandas.core.frame.DataFrame'>
Index: 1999 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   article_id    1999 non-null   object
 1   publisher     1999 non-null   object
 2   url           1999 non-null   object
 3   published_at  1999 non-null   object
 4   title         1999 non-null   object
 5   body_text     1999 non-null   object
dtypes: object(6)
memory usage: 109.3+ KB

In [6]:
# Unicode normalization (NFC - canonical decomposition + composition)
for column in ["title", "body_text"]:
    df[column] = df[column].astype(str).map(lambda value: unicodedata.normalize("NFC", value))

df.head()

,article_id,publisher,url,published_at,title,body_text
0,f92797eb-a338-5886-a45a-66f01292a912,Lanka Deepa,https://www.lankadeepa.lk/news/දන-තර-මර-අහවන-ක...,2025-09-26 00:00:00+00:00,දැන් තෝරු-මෝරු අහුවෙන කාලේ,දැන් තෝරු-මෝරු අහුවෙන කාලේ\n\nදැන් හාල්මැස්සො ...
1,5c7946aa-a810-59e2-a126-ff58347aad21,BBC Sinhala,https://www.bbc.com/sinhala/articles/c0vy04qd14yo,2024-01-17 00:00:00+00:00,අවුරුදු 67යි. ඇස් දෙකම පේන්නේ නෑ. මම පොල් කඩනවා',අවුරුදු 67යි. ඇස් දෙකම පේන්නේ නෑ. මම පොල් කඩනව...
2,6fc575d1-2be5-5d49-be20-c846617bdacd,Ada,https://www.ada.lk/breaking_news/පිදුරංගල-ගිය-...,2026-02-17 00:00:00+00:00,පිදුරංගල ගිය විදේශිකයා වන අලි ප්‍රහාරයෙන් මරුට,පිදුරංගල ගිය විදේශිකයා වන අලි ප්‍රහාරයෙන් මරුට...
3,47965836-064f-530a-a34d-02f6898fb94a,Ada Derana Sinhala,http://sinhala.adaderana.lk/news/194266,2024-03-07 00:00:00+00:00,හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් ගැ...,හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් ගැ...
4,132990f7-a4f4-54ba-8b12-b469d9803bde,Ada Derana Sinhala,http://sinhala.adaderana.lk/news/195779,2024-04-19 00:00:00+00:00,ස්ථාන දෙකකදී ඝාතන දෙකක්,ස්ථාන දෙකකදී ඝාතන දෙකක්\n\nකුලී නිවසක පදිංචිව ...

In [7]:
# Remove title duplication from the beginning of the body text
def remove_title_from_body(row):
    body = row["body_text"].strip()
    title = row["title"].strip()
    if body.startswith(title):
        body = body[len(title):].lstrip("\n").lstrip()
    return body


df["text"] = df.apply(remove_title_from_body, axis=1)
df[["title", "text"]].head()

,title,text
0,දැන් තෝරු-මෝරු අහුවෙන කාලේ,දැන් හාල්මැස්සො නොව තෝරු මෝරු අහුවෙන කාලය බවමහ...
1,අවුරුදු 67යි. ඇස් දෙකම පේන්නේ නෑ. මම පොල් කඩනවා',"මෙහි කිසිවක් අඩංගු නැත.Play video, ""දිරිය මිනි..."
2,පිදුරංගල ගිය විදේශිකයා වන අලි ප්‍රහාරයෙන් මරුට,සිගිරිය පිදුරංගල මාර්ගයේදී ඊයේ සවස වන අලියෙකු ...
3,හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් ගැ...,හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් දෙ...
4,ස්ථාන දෙකකදී ඝාතන දෙකක්,කුලී නිවසක පදිංචිව සිටි පුද්ගලයෙකුව ඊයේ (18) ර...

In [8]:
# Whitespace normalization
df["text"] = df["text"].map(lambda value: re.sub(r"\n{2,}", "\n", value))
df["text"] = df["text"].map(lambda value: re.sub(r"[ \t]+", " ", value))
df["text"] = df["text"].str.strip()

df = df[df["text"].str.len() > 0].reset_index(drop=True)
print("df shape after text cleaning:", df.shape)
df.head()

df shape after text cleaning: (1999, 7)

,article_id,publisher,url,published_at,title,body_text,text
0,f92797eb-a338-5886-a45a-66f01292a912,Lanka Deepa,https://www.lankadeepa.lk/news/දන-තර-මර-අහවන-ක...,2025-09-26 00:00:00+00:00,දැන් තෝරු-මෝරු අහුවෙන කාලේ,දැන් තෝරු-මෝරු අහුවෙන කාලේ\n\nදැන් හාල්මැස්සො ...,දැන් හාල්මැස්සො නොව තෝරු මෝරු අහුවෙන කාලය බවමහ...
1,5c7946aa-a810-59e2-a126-ff58347aad21,BBC Sinhala,https://www.bbc.com/sinhala/articles/c0vy04qd14yo,2024-01-17 00:00:00+00:00,අවුරුදු 67යි. ඇස් දෙකම පේන්නේ නෑ. මම පොල් කඩනවා',අවුරුදු 67යි. ඇස් දෙකම පේන්නේ නෑ. මම පොල් කඩනව...,"මෙහි කිසිවක් අඩංගු නැත.Play video, ""දිරිය මිනි..."
2,6fc575d1-2be5-5d49-be20-c846617bdacd,Ada,https://www.ada.lk/breaking_news/පිදුරංගල-ගිය-...,2026-02-17 00:00:00+00:00,පිදුරංගල ගිය විදේශිකයා වන අලි ප්‍රහාරයෙන් මරුට,පිදුරංගල ගිය විදේශිකයා වන අලි ප්‍රහාරයෙන් මරුට...,සිගිරිය පිදුරංගල මාර්ගයේදී ඊයේ සවස වන අලියෙකු ...
3,47965836-064f-530a-a34d-02f6898fb94a,Ada Derana Sinhala,http://sinhala.adaderana.lk/news/194266,2024-03-07 00:00:00+00:00,හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් ගැ...,හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් ගැ...,හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් දෙ...
4,132990f7-a4f4-54ba-8b12-b469d9803bde,Ada Derana Sinhala,http://sinhala.adaderana.lk/news/195779,2024-04-19 00:00:00+00:00,ස්ථාන දෙකකදී ඝාතන දෙකක්,ස්ථාන දෙකකදී ඝාතන දෙකක්\n\nකුලී නිවසක පදිංචිව ...,කුලී නිවසක පදිංචිව සිටි පුද්ගලයෙකුව ඊයේ (18) ර...

In [9]:
# Build documents for embedding (title + body), with the "passage: " prefix multilingual-e5
# models require for corpus-side text
def build_passage_text(title, body):
    title = str(title).strip() if title else ""
    body = str(body).strip() if body else ""
    combined = f"{title}. {body}" if title else body
    return "passage: " + combined


df["passage_text"] = df.apply(lambda row: build_passage_text(row["title"], row["text"]), axis=1)
print(f"Documents: {len(df)}")
df["passage_text"].iloc[0][:500]

Documents: 1999

'passage: දැන් තෝරු-මෝරු අහුවෙන කාලේ. දැන් හාල්මැස්සො නොව තෝරු මෝරු අහුවෙන කාලය බවමහනුවර දිස්ත්\u200dරික් මන්ත්\u200dරී ජගත් මනුවර්ණ මහතා:-(ජා.ජ.බ) පාර්ලිමේන්තුවේදී පැවසීය.\nදූෂණයට විරුද්ධ වීම භයානක බවත් දූෂණයට විරුද්ධ නොවී සිටීම ඊට වඩා භයානක බවත් අනුර දිසානායක ජනාධිපති\xa0 එක්සත් ජාතීන්ගේ මහා මණ්ඩලයේ අමතමින් ප්\u200dරකාශ කළා.එය අප නැවත අවධාරණය කළ යුතුයි.අපි දේශපාලන පලි ගැනීම් කරනවා යැයි චෝදනා කරනවා.නමුත් ඇත්ත ඒක නෙමෙයි.මත්තල ගුවන් තොටුපොලේ මගින් පර්යන්තය එක\xa0 ආණ්ඩුවක් නෙළුම් පොහොට්ටුවක හැඩයකට හදන්න තීරණය කළාම ඊට පස'

In [10]:
# Load multilingual-e5-large (the finalized embedding model for this project)
import torch
from transformers import AutoTokenizer, AutoModel

device = "cuda" if torch.cuda.is_available() else "cpu"
embedding_model_name = "intfloat/multilingual-e5-large"
tokenizer = AutoTokenizer.from_pretrained(embedding_model_name)
model = AutoModel.from_pretrained(embedding_model_name).to(device)
model.eval()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

XLMRobertaModel LOAD REPORT from: intfloat/multilingual-e5-large
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

XLMRobertaModel(
  (embeddings): XLMRobertaEmbeddings(
    (word_embeddings): Embedding(250002, 1024, padding_idx=1)
    (token_type_embeddings): Embedding(1, 1024)
    (LayerNorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (position_embeddings): Embedding(514, 1024, padding_idx=1)
  )
  (encoder): XLMRobertaEncoder(
    (layer): ModuleList(
      (0-23): 24 x XLMRobertaLayer(
        (attention): XLMRobertaAttention(
          (self): XLMRobertaSelfAttention(
            (query): Linear(in_features=1024, out_features=1024, bias=True)
            (key): Linear(in_features=1024, out_features=1024, bias=True)
            (value): Linear(in_features=1024, out_features=1024, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): XLMRobertaSelfOutput(
            (dense): Linear(in_features=1024, out_features=1024, bias=True)
            (LayerNorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): XLMRobertaIntermediate(
          (dense): Linear(in_features=1024, out_features=4096, bias=True)
          (intermediate_act_fn): GELUActivation()
        )
        (output): XLMRobertaOutput(
          (dense): Linear(in_features=4096, out_features=1024, bias=True)
          (LayerNorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
  (pooler): XLMRobertaPooler(
    (dense): Linear(in_features=1024, out_features=1024, bias=True)
    (activation): Tanh()
  )
)

In [11]:
# Mean pooling — established as the best strategy for this model on this corpus in
# notebooks/clustering_e5.ipynb (separation_score 0.2130 for mean vs 0.1264 for max pooling)
def mean_pooling(last_hidden_state, attention_mask):
    mask = attention_mask.unsqueeze(-1).expand(last_hidden_state.size()).float()
    summed = torch.sum(last_hidden_state * mask, dim=1)
    counts = torch.clamp(mask.sum(dim=1), min=1e-9)
    return summed / counts


@torch.no_grad()
def embed_passages(texts, batch_size=16, max_length=512):
    all_embeddings = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i + batch_size]
        encoded = tokenizer(
            batch, padding=True, truncation=True, max_length=max_length, return_tensors="pt",
        ).to(device)
        output = model(**encoded)
        pooled = mean_pooling(output.last_hidden_state, encoded["attention_mask"])
        pooled = torch.nn.functional.normalize(pooled, p=2, dim=1)
        all_embeddings.append(pooled.cpu())
    return torch.cat(all_embeddings, dim=0).numpy()


embeddings = embed_passages(df["passage_text"].tolist(), batch_size=16)
print(embeddings.shape)

(1999, 1024)

In [12]:
# Embedding separation score (comparable across notebooks): 1 - mean pairwise cosine similarity
# on a random 100-document sample of the raw embeddings.
from sklearn.metrics.pairwise import cosine_similarity

rng = np.random.default_rng(SEED)
sample_idx = rng.choice(len(embeddings), size=min(100, len(embeddings)), replace=False)
sample_emb = embeddings[sample_idx]

sims = cosine_similarity(sample_emb)
pairwise = sims[np.triu_indices_from(sims, k=1)]
separation_score = 1 - pairwise.mean()

print(f"Embedding model: {embedding_model_name}")
print(f"mean_sim={pairwise.mean():.4f} std={pairwise.std():.4f} min={pairwise.min():.4f} max={pairwise.max():.4f}")
print(f"Separation score (1 - mean cosine similarity): {separation_score:.4f}")

Embedding model: intfloat/multilingual-e5-large
mean_sim=0.7909 std=0.0243 min=0.7123 max=0.9162
Separation score (1 - mean cosine similarity): 0.2091

In [13]:
# Reduce dimensionality with UMAP (same settings used across this project's UMAP-based
# notebooks, e.g. notebooks/clustering_BGE_M3_BERTopic.ipynb)
from umap import UMAP

umap_model = UMAP(
    n_neighbors=3,
    n_components=5,
    min_dist=0.0,
    metric="cosine",
    random_state=SEED,
)
reduced_embeddings = umap_model.fit_transform(embeddings)
print(reduced_embeddings.shape)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

(1999, 5)

In [14]:
# Sweep k for K-Means, pick the value that maximizes silhouette score
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

candidate_k = sorted(set(list(range(10, 100, 10)) + list(range(100, 400, 25)) + list(range(400, 900, 50))))
sweep_results = []

for k in candidate_k:
    if k >= len(reduced_embeddings):
        continue
    model = KMeans(n_clusters=k, random_state=SEED, n_init=10)
    labels = model.fit_predict(reduced_embeddings)
    sil = silhouette_score(reduced_embeddings, labels, metric="cosine")
    sweep_results.append((k, sil))
    print(f"k={k:>4}  silhouette={sil:.4f}")

sweep_df = pd.DataFrame(sweep_results, columns=["k", "silhouette"]).sort_values("silhouette", ascending=False)
sweep_df.head(10)

k=  10  silhouette=0.4869
k=  20  silhouette=0.5843
k=  30  silhouette=0.5995
k=  40  silhouette=0.6089
k=  50  silhouette=0.6176
k=  60  silhouette=0.6360
k=  70  silhouette=0.6912
k=  80  silhouette=0.7353
k=  90  silhouette=0.7361
k= 100  silhouette=0.7563
k= 125  silhouette=0.7634
k= 150  silhouette=0.7786
k= 175  silhouette=0.7661
k= 200  silhouette=0.7613
k= 225  silhouette=0.7550
k= 250  silhouette=0.7841
k= 275  silhouette=0.7776
k= 300  silhouette=0.7847
k= 325  silhouette=0.7854
k= 350  silhouette=0.7921
k= 375  silhouette=0.8015
k= 400  silhouette=0.7977
k= 450  silhouette=0.7928
k= 500  silhouette=0.7833
k= 550  silhouette=0.7712
k= 600  silhouette=0.7659
k= 650  silhouette=0.7494
k= 700  silhouette=0.7306
k= 750  silhouette=0.7086
k= 800  silhouette=0.6876
k= 850  silhouette=0.6708

      k  silhouette
20  375    0.801486
21  400    0.797744
22  450    0.792837
19  350    0.792059
18  325    0.785444
17  300    0.784698
15  250    0.784076
23  500    0.783281
11  150    0.778595
16  275    0.777595

In [15]:
# Refit at the best k found
best_k = int(sweep_df.iloc[0]["k"])
print(f"Best k: {best_k}")

model = KMeans(n_clusters=best_k, random_state=SEED, n_init=10)
df["cluster_id"] = model.fit_predict(reduced_embeddings)

print(df["cluster_id"].value_counts().head(20))
print("Number of clusters found:", df["cluster_id"].nunique())

extra_row_fields = {"best_k": best_k}

Best k: 375
cluster_id
70     17
93     16
144    15
95     15
66     15
100    13
56     13
73     12
11     12
43     11
18     11
183    11
205    11
337    11
4      10
228    10
26     10
257    10
13     10
160    10
Name: count, dtype: int64
Number of clusters found: 375

In [16]:
# Clustering evaluation
from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score

labels = df["cluster_id"].values
mask = labels != -1  # -1 = noise; only meaningful for density-based algorithms
X_valid = reduced_embeddings[mask]
labels_valid = labels[mask]
n_clusters = len(set(labels_valid))
noise_ratio = 1 - mask.mean()

print(f"Model: {embedding_model_name} + UMAP + KMeans")
print(f"Articles: {len(df)} | Clusters (excl. noise): {n_clusters} | Noise ratio: {noise_ratio:.2%}")

if n_clusters > 1:
    sil = silhouette_score(X_valid, labels_valid, metric="cosine")
    dbi = davies_bouldin_score(X_valid, labels_valid)
    ch = calinski_harabasz_score(X_valid, labels_valid)
    print(f"Silhouette Score (cosine): {sil:.4f}")
    print(f"Davies-Bouldin Index:      {dbi:.4f}  (lower is better)")
    print(f"Calinski-Harabasz Index:   {ch:.2f}  (higher is better)")
else:
    sil = dbi = ch = float("nan")
    print("Not enough clusters to compute silhouette/DBI/CH.")

scores_path = RESULTS_DIR / "e5_kmeans_scores.csv"
row = {
    "model": embedding_model_name,
    "pipeline": "UMAP+KMeans",
    "embedding_dim": embeddings.shape[1],
    "separation_score": round(separation_score, 4),
    "n_articles": len(df),
    "n_clusters": n_clusters,
    "noise_ratio": round(noise_ratio, 4),
    "silhouette": round(sil, 4) if n_clusters > 1 else None,
    "davies_bouldin": round(dbi, 4) if n_clusters > 1 else None,
    "calinski_harabasz": round(ch, 2) if n_clusters > 1 else None,
}
row.update(extra_row_fields)
pd.DataFrame([row]).to_csv(scores_path, index=False)
print(f"Saved scores to {scores_path}")

Model: intfloat/multilingual-e5-large + UMAP + KMeans
Articles: 1999 | Clusters (excl. noise): 375 | Noise ratio: 0.00%
Silhouette Score (cosine): 0.8015
Davies-Bouldin Index:      0.4159  (lower is better)
Calinski-Harabasz Index:   13603.78  (higher is better)
Saved scores to /kaggle/working/results/e5_kmeans/e5_kmeans_scores.csv

In [17]:
# Inspect sample titles per cluster
for cluster_id, group in list(df[df["cluster_id"] != -1].groupby("cluster_id"))[:10]:
    print(f"=== Cluster {cluster_id} ({len(group)} articles) ===")
    for title in group["title"].head(10):
        print(f"- {title}")
    print()

=== Cluster 0 (5 articles) ===
- වසර 45ක් ස්වේච්ඡාවෙන් දරුවන්ට පාර කියන අත්තම්මා
- පතල් වැඩ නැති දාට කැලේ යනවා දර කපන්න. මට ඕනා ළමයව හොඳ තැනකට ගෙනියන්න.'
- මිනිස්සු වෙනුවෙන්, භූමිය වෙනුවෙන් අපි සටන් වැදුණේ. අපිට මොනවාද ලැබුණේ ?'
- නොමිලේ දැනුම බෙදන මහියංගණයේ උපකාරක පන්ති ගුරුතුමා : 'මම කරන්නේ පිං අතේ වැඩක් නොවෙයි'
- අධ්‍යාපනයේ මහිමයෙන් ලෝකය ජය ගත් හේනේ පැලක පාඩම් කළ ශ්‍රී ලාංකිකයා

=== Cluster 1 (5 articles) ===
- විදෙස්ගත ශ්‍රමිකයින්ට මෙරටට භාණ්ඩ රැගෙන ඒමේදී බලාත්මක කර ඇති කොන්දේසි මෙන්න
- සහල් අර්බුදය: ආනයනික සහල් තොග දිවයිනට
- සහල් මෙට්‍රික්ටොන් 67,000ක් මෙරටට ආනයනයකර අවසන්
- වී නිෂ්පාදනය වැඩිවෙලා සහල් ආනයන වියදම අඩුවෙයි
- සහල් ආනයනයට අවසර දුන් කාලය තවත් පැය කිහිපයකින් අවසන්: ජනපති ඇතුළු රජය මෙතෙක් ගත් පියවර මොනවා ද?

=== Cluster 2 (2 articles) ===
- ඩොලරය ගැන රනිල් අනතුරු අඟවයි
- මේක L බෝඩ් ආණ්ඩුවක් - රනිල්

=== Cluster 3 (6 articles) ===
- බුල්නෑව නිවසක් බිඳ ජීප් රථයක්, රන් භාණ්ඩ හා මුදල් කෝල්ල කෑ සැකකරුවන් අල්ලයි
- ග්‍රෑන්ඩ්පාස් වෙඩි තැබීමට සැක දෙදෙනෙකු අල්ලයි
- රත්‍රං බවට සැක පුරාවස්තු තොගයක් පුත්තලමේ නිවසක
- මෙහනින් වහන්සේ නමකට බැන වැදුණ සැකකරුවන් අල්ලයි
- වනඅලියාව විහිළුවට ගත් තරුණයින්
- විල්පත්තුව උද්‍යානයේ සතුන් මැරූ දෙන්නෙක් අල්ලයි

=== Cluster 4 (10 articles) ===
- මම ලියන හැටි' : නිශ්ශංක විජේමාන්න
- මම ලියන හැටි': ආරියවංශ අබේසේකර
- මම ලියන හැටි': අනුරසිරි හෙට්ටිගේ
- මම ලියන හැටි': දර්ශනා ශම්මි විජේතිලක
- මම ලියන හැටි' : රූපා ශ්‍රියානි ඒකනායක
- දැන් පොත්වල ආනන්දයත් නෑ... ප්‍රඥාවත් නෑ...
- මම ලියන හැටි' : චන්දි කොඩිකාර
- මම ලියන හැටි' : සමන් වික්‍රමාරච්චි
- මම ලියන හැටි' : මංජුල සේනාරත්න
- මම ලියන හැටි': කාංචනා අමිලානි

=== Cluster 5 (10 articles) ===
- හලාවත මත්ද්‍රව්‍ය මෙහෙයුමක් අතරතුර පලා යාමට තැත්කළ  සැකකරුවෙකු පොලිස් අත්අඩංගුවට පත්වීමෙන් පසු  මිය යයි
- යුක්තිය' මත්ද්‍රව්‍ය මර්දන මෙහෙයුම : පොලිස්   අත්අඩංගුවට ගැනීම් නිත්‍යානුකූල ද?
- යුක්තියෙන් රැකියාත් ලබාදෙයි
- දේශපාලන බලපෑම් තියෙනවා නම් ඒ හරි දේ කරන්න කියලා විතරයි
- කංජිපානි ලංකාවට ගේන්න බලය පවරන්නැයි හිටපු අයි පී දුමින්ද කියයි
- බස්නාහිර සහ දකුණේ අපරාධ කල්ලි මර්දනයට විශේෂ මෙහෙයුමක්
- ටිරාන් අලස් : ' UN හියුමන් රයිට්ස් ලියුම තුට්ටු දෙකකට ගණන් ගන්නේ නෑ'
- දඹුල්ලේ විදෙස් සංචාරකයෝ පිරිලා , ආරක්ෂාව තර කරයි
- කන්ජිපානිට සහ ගනේමුල්ලේ සංජීවට රටින් පැනයෑමට උපකාර කළ නීතිඥයින් ගැන පොලීසිය භාර ඇමති කියයි
- තරුණයෙකු දුම්රියේ ගැටී මියයාම ගැන මව්පියන්ගෙන් පොලීසියට චෝදනා

=== Cluster 6 (5 articles) ===
- මන්ත්‍රීවරුන්ට ගිනිඅවි දීම: ආණ්ඩුව සැරසෙන්නේ 'මොකක් හරි සෙල්ලමකට' ද?
- විශ්‍රාමික ජනපතිවරුන්ගේ සහ මන්ත්‍රීවරුන්ගේ වරප්‍රසාද කප්පාදු කරන්නේ කෙසේ ද?
- මන්ත්‍රීන්ට, පක්ෂ නායකයන්ට, රජයේ විධායක නිලධාරීන්ට දුන් ගිනි අවි නැවත රජයට ඉල්ලයි
- පාර්ලිමේන්තු මන්ත්‍රීවරුන්ට හිමි වන ප්‍රධාන දීමනා සහ වරප්‍රසාද 7ක්
- ලොක්කෝ විස්සක් මැතිසබය හැර යති

=== Cluster 7 (5 articles) ===
- ශ්‍රී ලංකාවේ රුක් රෝපණය විද්‍යාත්මක ද? දේශපාලනික ද?
- ජනාධිපතිවරණය 2024: ශ්‍රී ලංකාවේ අනාගතය කලාපීය බලවතුන් අතර දෝලනය වෙයි ද?
- අයිඑම්එෆ් පළමු නියෝජ්‍ය කළමනාකාර අධ්‍යක්ෂිකාව ලංකාවේ සංචාරයක
- IMF: ශ්‍රී ලංකාවට වාහන ආනයනයට මාර්ග සිතියමක්
- ශ්‍රී ලංකාව ගැන මූඩීස් කරුණු පහදයි

=== Cluster 8 (4 articles) ===
- ලංකා කඩොලාන කෞතුකාගාරය බලන්න යමු ද?
- හබරණ හුරුළු රක්ෂිතයේ වන විනාශයක්
- හෝටලය තියෙන්නේ වැව් මායිමේ නෙමෙයි, නැති බම්බුවක් කොහොමද අයින් කරන්නේ
- කහල්ල රක්ෂිතයේ ආක්‍රමණික ශාක ඉවත් කිරීමේ සැලැස්ම ගැන නියෝජ්‍ය අමාත්‍ය නාමල් කරුණාරත්නගෙන් ප්‍රතිචාර

=== Cluster 9 (4 articles) ===
- මෛත්‍රී හැදූ මෙත්සිරිපාය සුදු අලියෙක් ?
- රාජ්‍ය ඉදිකිරීම්වලට ප්‍රතිපත්තියක් ඕනෑ
- මහින්දානන්ද පදනම් ගොඩනැගිල්ල දුම්රියේ ඉඩමක
- ප්‍රා.ලේ නැවතුනු ගොඩනැගිලිවල වැඩ අරඹයි

In [18]:
# Inspect a RANDOM sample of clusters (rather than just the first few by id) — a more
# representative check of overall cluster quality than always looking at the same low-numbered
# clusters
rng_inspect = np.random.default_rng(SEED)
cluster_ids = df.loc[df["cluster_id"] != -1, "cluster_id"].unique()
sample_size = min(8, len(cluster_ids))
sampled_cluster_ids = rng_inspect.choice(cluster_ids, size=sample_size, replace=False)

for cluster_id in sampled_cluster_ids:
    group = df[df["cluster_id"] == cluster_id]
    print(f"=== Cluster {cluster_id} ({len(group)} articles) ===")
    for title in group["title"].head(15):
        print(f"- {title}")
    print()

=== Cluster 336 (2 articles) ===
- ‘Visa ශ්‍රී ලංකා සයිබර් ආරක්ෂණ සමුළුව 2026’ සාර්ථකව නිමාවේ
- 2026 අයවැයෙන් ඩිජිටල්කරණය වන ක්ෂේත්‍ර මොනවා ද? මුදල් වෙන් වෙන්නේ කෙසේ ද?

=== Cluster 318 (4 articles) ===
- මැණික්වලට අඟරු චෙක් දුන් පහක් අත්අඩංගුවට
- රජමහ වෙහෙරක  තිබූ මැණික්  සොරු අරන්
- නිධන් සොයන්න ගිය තිදෙනකු පොලිස් දැලේ
- පොලොව බිඳින ස්කෑනරයක් සමග දෙකක් මාට්ටු

=== Cluster 67 (2 articles) ===
- ව්‍යාජ ප්‍රතිදේහ නිෂ්පාදනය කළ කර්මාන්ත ශාලාවෙන් හමුවූ දේ
- මිද්දෙණියේ ඉඩමෙන් පොලිස් නිලධාරීන් රාජකාරි සඳහා භාවිතා කරන උපාංග හමුවෙයි

=== Cluster 218 (4 articles) ===
- දිසා විනිසුරු නිල නිවසේ රාජකාරීය අතරතුරදී  සූර් පිට සිටි පී සී අත්අඩංගුවට
- වැඩ තහනම් වූ පීසී කෝටි 8ක මත්ද්‍රව්‍ය සමඟ මාට්ටු
- හෙරොයින් සමඟ  හිටපු පීසී අල්ලයි
- විනිසුරුවරයෙකුගේ නිවසකටත් හොරු පනී

=== Cluster 175 (5 articles) ===
- මන්දකට හසු වී සිටි කදුකර කොටියා නිර්වින්දනය කර මුදා ගනිියි
- පැරණි පොලිස් මූලස්ථානයේ තිබූ CCTV කැමරා 7ක් අතුරුදන්
- අධිවේගයේ කඩා වැටුණ කොන්ක්‍රීට් ආධාරකය පොලීසියේ පරීක්ෂණයට
- මවගෙන් වෙන් කෙරුණු වන අලි පැටවා උඩවලවට රැගෙන යයි
- අධිවේගයට ආ වන අලියා

=== Cluster 142 (4 articles) ===
- පාප් වහන්සේ ලංකාවට
- ඔස්ට්‍රේලියානු අග්‍රාණ්ඩුකාරවරිය තෙදින නිල සංචාරයකට දිවයිනට
- වතිකාන විදෙස් ඇමැති ජනපති අනුර හමුවෙයි
- ශ්‍රී ලංකාව සමඟ වඩාත් සමීපව කටයුතු කිරීම අපේකෂාවයි - මාලදිවයින් ජනපති කියයි

=== Cluster 1 (5 articles) ===
- විදෙස්ගත ශ්‍රමිකයින්ට මෙරටට භාණ්ඩ රැගෙන ඒමේදී බලාත්මක කර ඇති කොන්දේසි මෙන්න
- සහල් අර්බුදය: ආනයනික සහල් තොග දිවයිනට
- සහල් මෙට්‍රික්ටොන් 67,000ක් මෙරටට ආනයනයකර අවසන්
- වී නිෂ්පාදනය වැඩිවෙලා සහල් ආනයන වියදම අඩුවෙයි
- සහල් ආනයනයට අවසර දුන් කාලය තවත් පැය කිහිපයකින් අවසන්: ජනපති ඇතුළු රජය මෙතෙක් ගත් පියවර මොනවා ද?

=== Cluster 353 (2 articles) ===
- රටපුරා හදිසි තත්ත්වයක් ප්‍රකාශයට පත් කෙරේ: හදිසි අවස්ථා තත්ත්වයක් යනු කුමක් ද?
- හදිසි තත්ත්වය: ජනපති සහ නියෝජ්‍ය ඇමති වටගලගේ 'පරස්පර' ප්‍රකාශ ගැන පොලිසිය භාර ඇමති කියන්නේ මොනවා ද?

In [19]:
# Save article-level assignments
assignments_path = RESULTS_DIR / "e5_kmeans_assignments.csv"
df.drop(columns=["passage_text"], errors="ignore").to_csv(assignments_path, index=False, encoding="utf-8-sig")
print(f"Saved assignments: {assignments_path.resolve()}")

Saved assignments: /kaggle/working/results/e5_kmeans/e5_kmeans_assignments.csv

In [20]:
# Print every cluster (capped at 20 titles each, so this stays readable even when there are
# hundreds of clusters)
for cluster_id, group in sorted(
    df[df["cluster_id"] != -1].groupby("cluster_id"), key=lambda item: item[0]
):
    print(f"=== Cluster {cluster_id} ({len(group)} articles) ===")
    for title in group["title"].head(20):
        print(f"- {title}")
    if len(group) > 20:
        print(f"... ({len(group) - 20} more)")
    print()

=== Cluster 0 (5 articles) ===
- වසර 45ක් ස්වේච්ඡාවෙන් දරුවන්ට පාර කියන අත්තම්මා
- පතල් වැඩ නැති දාට කැලේ යනවා දර කපන්න. මට ඕනා ළමයව හොඳ තැනකට ගෙනියන්න.'
- මිනිස්සු වෙනුවෙන්, භූමිය වෙනුවෙන් අපි සටන් වැදුණේ. අපිට මොනවාද ලැබුණේ ?'
- නොමිලේ දැනුම බෙදන මහියංගණයේ උපකාරක පන්ති ගුරුතුමා : 'මම කරන්නේ පිං අතේ වැඩක් නොවෙයි'
- අධ්‍යාපනයේ මහිමයෙන් ලෝකය ජය ගත් හේනේ පැලක පාඩම් කළ ශ්‍රී ලාංකිකයා

=== Cluster 1 (5 articles) ===
- විදෙස්ගත ශ්‍රමිකයින්ට මෙරටට භාණ්ඩ රැගෙන ඒමේදී බලාත්මක කර ඇති කොන්දේසි මෙන්න
- සහල් අර්බුදය: ආනයනික සහල් තොග දිවයිනට
- සහල් මෙට්‍රික්ටොන් 67,000ක් මෙරටට ආනයනයකර අවසන්
- වී නිෂ්පාදනය වැඩිවෙලා සහල් ආනයන වියදම අඩුවෙයි
- සහල් ආනයනයට අවසර දුන් කාලය තවත් පැය කිහිපයකින් අවසන්: ජනපති ඇතුළු රජය මෙතෙක් ගත් පියවර මොනවා ද?

=== Cluster 2 (2 articles) ===
- ඩොලරය ගැන රනිල් අනතුරු අඟවයි
- මේක L බෝඩ් ආණ්ඩුවක් - රනිල්

=== Cluster 3 (6 articles) ===
- බුල්නෑව නිවසක් බිඳ ජීප් රථයක්, රන් භාණ්ඩ හා මුදල් කෝල්ල කෑ සැකකරුවන් අල්ලයි
- ග්‍රෑන්ඩ්පාස් වෙඩි තැබීමට සැක දෙදෙනෙකු අල්ලයි
- රත්‍රං බවට සැක පුරාවස්තු තොගයක් පුත්තලමේ නිවසක
- මෙහනින් වහන්සේ නමකට බැන වැදුණ සැකකරුවන් අල්ලයි
- වනඅලියාව විහිළුවට ගත් තරුණයින්
- විල්පත්තුව උද්‍යානයේ සතුන් මැරූ දෙන්නෙක් අල්ලයි

=== Cluster 4 (10 articles) ===
- මම ලියන හැටි' : නිශ්ශංක විජේමාන්න
- මම ලියන හැටි': ආරියවංශ අබේසේකර
- මම ලියන හැටි': අනුරසිරි හෙට්ටිගේ
- මම ලියන හැටි': දර්ශනා ශම්මි විජේතිලක
- මම ලියන හැටි' : රූපා ශ්‍රියානි ඒකනායක
- දැන් පොත්වල ආනන්දයත් නෑ... ප්‍රඥාවත් නෑ...
- මම ලියන හැටි' : චන්දි කොඩිකාර
- මම ලියන හැටි' : සමන් වික්‍රමාරච්චි
- මම ලියන හැටි' : මංජුල සේනාරත්න
- මම ලියන හැටි': කාංචනා අමිලානි

=== Cluster 5 (10 articles) ===
- හලාවත මත්ද්‍රව්‍ය මෙහෙයුමක් අතරතුර පලා යාමට තැත්කළ  සැකකරුවෙකු පොලිස් අත්අඩංගුවට පත්වීමෙන් පසු  මිය යයි
- යුක්තිය' මත්ද්‍රව්‍ය මර්දන මෙහෙයුම : පොලිස්   අත්අඩංගුවට ගැනීම් නිත්‍යානුකූල ද?
- යුක්තියෙන් රැකියාත් ලබාදෙයි
- දේශපාලන බලපෑම් තියෙනවා නම් ඒ හරි දේ කරන්න කියලා විතරයි
- කංජිපානි ලංකාවට ගේන්න බලය පවරන්නැයි හිටපු අයි පී දුමින්ද කියයි
- බස්නාහිර සහ දකුණේ අපරාධ කල්ලි මර්දනයට විශේෂ මෙහෙයුමක්
- ටිරාන් අලස් : ' UN හියුමන් රයිට්ස් ලියුම තුට්ටු දෙකකට ගණන් ගන්නේ නෑ'
- දඹුල්ලේ විදෙස් සංචාරකයෝ පිරිලා , ආරක්ෂාව තර කරයි
- කන්ජිපානිට සහ ගනේමුල්ලේ සංජීවට රටින් පැනයෑමට උපකාර කළ නීතිඥයින් ගැන පොලීසිය භාර ඇමති කියයි
- තරුණයෙකු දුම්රියේ ගැටී මියයාම ගැන මව්පියන්ගෙන් පොලීසියට චෝදනා

=== Cluster 6 (5 articles) ===
- මන්ත්‍රීවරුන්ට ගිනිඅවි දීම: ආණ්ඩුව සැරසෙන්නේ 'මොකක් හරි සෙල්ලමකට' ද?
- විශ්‍රාමික ජනපතිවරුන්ගේ සහ මන්ත්‍රීවරුන්ගේ වරප්‍රසාද කප්පාදු කරන්නේ කෙසේ ද?
- මන්ත්‍රීන්ට, පක්ෂ නායකයන්ට, රජයේ විධායක නිලධාරීන්ට දුන් ගිනි අවි නැවත රජයට ඉල්ලයි
- පාර්ලිමේන්තු මන්ත්‍රීවරුන්ට හිමි වන ප්‍රධාන දීමනා සහ වරප්‍රසාද 7ක්
- ලොක්කෝ විස්සක් මැතිසබය හැර යති

=== Cluster 7 (5 articles) ===
- ශ්‍රී ලංකාවේ රුක් රෝපණය විද්‍යාත්මක ද? දේශපාලනික ද?
- ජනාධිපතිවරණය 2024: ශ්‍රී ලංකාවේ අනාගතය කලාපීය බලවතුන් අතර දෝලනය වෙයි ද?
- අයිඑම්එෆ් පළමු නියෝජ්‍ය කළමනාකාර අධ්‍යක්ෂිකාව ලංකාවේ සංචාරයක
- IMF: ශ්‍රී ලංකාවට වාහන ආනයනයට මාර්ග සිතියමක්
- ශ්‍රී ලංකාව ගැන මූඩීස් කරුණු පහදයි

=== Cluster 8 (4 articles) ===
- ලංකා කඩොලාන කෞතුකාගාරය බලන්න යමු ද?
- හබරණ හුරුළු රක්ෂිතයේ වන විනාශයක්
- හෝටලය තියෙන්නේ වැව් මායිමේ නෙමෙයි, නැති බම්බුවක් කොහොමද අයින් කරන්නේ
- කහල්ල රක්ෂිතයේ ආක්‍රමණික ශාක ඉවත් කිරීමේ සැලැස්ම ගැන නියෝජ්‍ය අමාත්‍ය නාමල් කරුණාරත්නගෙන් ප්‍රතිචාර

=== Cluster 9 (4 articles) ===
- මෛත්‍රී හැදූ මෙත්සිරිපාය සුදු අලියෙක් ?
- රාජ්‍ය ඉදිකිරීම්වලට ප්‍රතිපත්තියක් ඕනෑ
- මහින්දානන්ද පදනම් ගොඩනැගිල්ල දුම්රියේ ඉඩමක
- ප්‍රා.ලේ නැවතුනු ගොඩනැගිලිවල වැඩ අරඹයි

=== Cluster 10 (3 articles) ===
- Fox Hill ධාවන ශූරයෙක් වූ බුද්ධික ගැන සංවේදී කතාවක්
- දියතලාව බිහිසුණු ඛේදවාචකයේ නොදත් කතාව
- Fox Hill අනතුර: සාමාන්‍ය මාර්ග නීති මෝටර් රථ ධාවන තරගයකටත් අදාළ කර ගත හැකි ද?

=== Cluster 11 (12 articles) ===
- සමිත දුලාන් කොඩිතුවක්කු: 'ඒක ලෝක වාර්තාවක් වෙයි කියලා හිතුවේ නැහැ'
- කනිෂ්ඨ මලල ක්‍රීඩා ශූරතාවලියේ වටිනාම ක්‍රීඩකයා වූ මෙරෝන් විජේසිංහ කවුද ?
- Asian Youth Games 2025: ශ්‍රී ලංකාවට පළමු රන් පදක්කම ලහිරු අචින්තගෙන්
- 2025 ලෝක රූ රැජිනට ටිෂානි පෙරේරා අපෙන්
- විලාසිතා සහ නිර්මාණශීලිත්වය විදහා දැක්වූ SLIIT VogueFest’25
- පාකිස්තානයට වටිනාකමක් එක්කළ නදීම්
- තරුෂිට සහ නදීෂාට ඔලිම්පික් වරම්
- යෙවාන්, ඩිලන්ත සහ මා වෙනුවෙන් සහය වෙන හැම ශ්‍රී ලාංකිකයෙකුට ම මං ස්තූති කරනවා'
- දකුණු ආසියාවේ වේගවත් ම ක්‍රීඩකයා සහ ක්‍රීඩිකාව ශ්‍රී ලංකාවෙන්
- පැරා ශුරයෝ කටුනායකට
- ලෝකයේ හොඳම යොවුන් නිරූපන ශිල්පියා ලංකාවෙන්
- දියණිය දීනූ රන් පියාණන්ට පළඳවයි

=== Cluster 12 (6 articles) ===
- ඇතැම් නැව් ආරක්ෂිතව ගමන් කරවීමට චීනය හා ඉරානය අතර  සාකච්ඡා
- ආර්ක්ටික් ප්‍රදේශය පාලනය කිරීමට ලෝක බලවතුන් තරග කරන්නේ ඇයි?
- තෙල් බැරලය ඩොලර් 100න් පහළට
- බොරතෙල් මිල ඉහළට
- ඇමෙරිකාව ඉරාන බෝට්ටුවලට පහරදෙද්දි ඉරානය එමීරයේ තෙල් පහසුකමකට පහර දෙයි
- ලංකාවට ඔබ්බෙන් වූ මුහුදු තීරයේදි ඉරාන නැව විනාශ කළේ ටෝපිඩෝවකින් බව ඇමෙරිකාව කියයිි

=== Cluster 13 (10 articles) ===
- මාලිමාවේ හබරාදූව සභාපති ඉල්ලා අස්වෙයි
- නාවුල අයවැයත් පරදී
- කරුවලගස්වැව අයවැයට විපක්ෂයේ හතරකගේ සහාය
- පක්ෂයට පිටින් ගිය සීතාවක සර්ව ජන මන්ත්‍රි  පක්ෂයෙන් දොට්ට
- මීරිගම ප්‍රා.ස. අයවැයත් සම්මතයි
- පදියතලාව ප්‍රා. සභා අයවැය දෙවන වරටත් පරාදයි
- සභාපතිගේ තීරක ඡන්දයෙන් පානදුර අයවැය සම්මතයි
- අයවැය පැරදුණු  පුංචි සභා තිහක්  පඹ ගාලක
- පොල්ගහවෙළ අයවැය සම්මතයි
- කොළොන්න ප්‍රා.සභා අය වැය දෙවනවරටත් පරදි

=== Cluster 14 (7 articles) ===
- දවස් 07ක් සුරාසැල් වැසෙන තැන් මෙන්න
- ජුලි මස සිට වැසෙන සපුගස්කන්ද
- කොළඹ ප්‍රධාන නගර කිහිපයකට හෙට ජල කප්පාදුවක්
- සපුගස්කන්ද තෙල් පිරිපහදුවේ සේවකයින්ගේ රැකියා අවදානමේ
- මහර - ගම්පහට පැය 15ක් ජලය කපයි
- සපුගස්කන්ද තෙල් පිරිපහදුව වෙනම ආයතනයක් කරයි
- කොළඹ ප්‍රදේශ කිහිපයක ජලය කැපෙයි

=== Cluster 15 (8 articles) ===
- ටින්කර් රඳවාගෙන ප්‍රශ්න කරයි
- අන්තරේට බොරැල්ලෙදී ජල ප්‍රහාරයක්  කැඳවුම්කරු අත්ඩංගුවට
- කොටහේන ඝාතනයට හයක් අල්ලයි
- බෙලිඅත්ත ඝාතනයේ තවත් සැකකරුවෙක් අත්අඩංගුවට
- බස් ලලිත් ඩුබායිහිදී අත්අඩංගුවට?
- ළහිරු වීරසේකර අත්අඩංගුවට
- වැලිමඩ උසාවියේ රෙජිස්ට්‍රාර් අල්ලස් දැලේ පැටලේ
- සා/පෙළ විභාග මධ්‍යස්ථානයක සුපරීක්ෂකවරියක් අත්අඩංගුවට

=== Cluster 16 (3 articles) ===
- පරිසර ඇමති හොංකොං සමුළුවට
- ලෝක සෞඛ්‍ය සංවිධානයේ අධ්‍යක්ෂ ජනරාල් කටුනායකට
- හත්වන බිම්ස්ටෙක් සමුළුව හෙට ඇරැඹේ

=== Cluster 17 (3 articles) ===
- නාවික හමුදා සෙබළෙකු කැති පහරින් මරුට
- බිරිඳගේ හිස රැගෙන පොලීසියට ගිය අනිල්
- ගෑණු හුටපටයකට සෙබළෙක් සෙබළකු මරයි

=== Cluster 18 (11 articles) ===
- ජන අරගල සන්ධානය : 'ගෝල්ෆේස් අරගලකරුවන්' රැසක් සමග දේශපාලන කරලියට එන නව සන්ධානය
- මහ මැතිවරණයක් පැවැත්වීමට ආණ්ඩුවට මුදල් තිබේ ද?
- මැතිවරණ ගැසට්ටුව අත්හිටුවන්නැයි ශ්‍රේෂ්ඨාධිකරණයට පෙත්සමක්
- සේමසිංහ පොහොට්ටුවේ මහලේකම්ට ලියයි
- මහ මැතිවරණයේදී  ඡන්ද දායකයෙකු වෙනුවෙන් වියදම් කළ හැකි මුදල් ප්‍රකාශයට පත් කෙරේ
- ෂෙහාන්ගෙන් පොහොට්ටු මහ ලේකම්ට ලිපියක්
- රන්ජන්ගේ නාමයෝජනාව ප්‍රතික්ෂේප කරන්නැයි ඉල්ලා පෙත්සමක්
- ජනාධිපතිවරණය 2024: දෙවැනි පෙත්සමත් ප්‍රතික්ෂේපයි
- 22 ගැන ඇත්ත කතාව ඇමති සුසිල් කියයි
- මහ මැතිවරණ දිනයට එරෙහි පෙත්සම විභාගයට නොගෙන නිෂ්ප්‍රභ කෙරේ
- රනිල් වික්‍රමසිංහ: ජනාධිපතිවරණ ඉතිහාසයේ අඛණ්ඩ පරාජිතයා

=== Cluster 19 (4 articles) ===
- කෙන්යාවේ ඛේදවාචකයක්
- ඇෆ්ගනිස්තානයට යළිත් ගංවතුර - ජීවිත රැසක් අහිමි වෙයි
- උතුරු සුඩානයේ ගැටුම් තීව්‍ර වෙයි
- දකුණු කොරියාවේ ගංවතුර සහ නායයෑම් හේතුවෙන් පුද්ගලයින් 14 දෙනෙකු මරුට

=== Cluster 20 (5 articles) ===
- බඹර ප්‍රහාරයකින් අයෙක් මරුට : 7 ක් රෝහලේ
- හන්තානේ ’’ට්‍රිප් එක’’ රෝහලෙන් නිමාවේ
- ලෝක ළමා දිනය දා ගෝලයාගෙන් ගුරාට පහරක්
- පාසල් සිසු වලියෙන් ළමා දිනයත් හබක්
- බඹරුඇන සරසවි සිසුන් 6 ක් රෝහලේ

=== Cluster 21 (4 articles) ===
- වීසා නොමැතිව රැඳි සිටි තවත් ඉන්දීය ජාතිකයන් පිරිසක් අත්අඩංගුව ට
- ලූවර් කෞතුකාගාර කොල්ල කරුවන් අල්ලයි
- ගුවන් යානය තුළ විදෙස් මුදල් හා ස්වණාභරණ සොරකම් කළ චීන ජාතිකයා අත්අඩංගුවට
- කෝටි 12ක රන් ආභරණ සමග ව්‍යාපාරිකයන් දෙදෙනෙක් අල්ලයි

=== Cluster 22 (8 articles) ===
- අලුත් අවුරුදු ගනුදෙනුවලට මහජන බැංකුවෙන් තිලිණ
- උන්ඩියල් හා හවාලා ක්‍රියාකරුවන්ට මහ බැංකුවේ ලියාපදිංචි වෙන්න කියයි
- ‘ComBank අක්ෂර’ 400 වන IT විද්‍යාගාරයත් දියත් කරයි
- කොමර්ෂල් බැංකු කාඩ්පත් හිමියන්ට සියයට 70ක් දක්වා අවුරුදු වට්ටම්
- HSBC හි ආයතනික සහ සංස්ථා බැංකුකරණ පහසුකම් තවදුරටත්
- බැංකු දෙකක් ප්‍රතිව්‍යුහගත කරයි
- මාර්ගගත ගෙවීම් සඳහා මෙරට ප්‍රථම DCC සේවාව දියත් කරයි
- QR ගනුදෙනු රු 5000ක් දක්වා ගාස්තුවලින් නිදහස්

=== Cluster 23 (6 articles) ===
- ශ්‍රී ලංකාව - ඉරාන අතර අවබෝධතා ගිවිසුම් 05 ක්
- කොළඹ කොටස් හුවමාරුව රුහුණු සරසවිය හා හවුල් වේ
- ලංකා සරසවි පහක් විදෙස් සහයෝගිතා ගිවිසුම් අත්සන් කරයි
- ට්‍රම්ප්ගේ අලුත් ම අනතුරු ඇඟවීම අනුව ඉරානය සමග ගනුදෙනු කිරීම ශ්‍රී ලංකාවට බලපෑ හැක්කේ කෙසේ ද?
- ඉරාන ජනපති කඩිනමින් ලංකාවට එන්න සැරසෙයි
- ඉරාන ජනපති මහින්දට එවූ ත්‍යාගයක් ජනපති මිය ගිය දිනයේදීම ලැබෙයි

=== Cluster 24 (4 articles) ===
- ශ්‍රී ලංකාව වෙනුවෙන් පකිස්ථාන පාර්ලිමේන්තුවට යෝජනාවක්: ක්‍රීඩකයින්ට 'රාජ්‍ය නායක ආරක්ෂාව' ලැබෙන්නේ මෙහෙමයි
- රොෂාන් පත්කළ කමිටුවක් හරීන් විසිරුවා හරී
- LPL කණ්ඩායම් සඳහා අලුත් නීතියක්
- පකිස්ථාන - ශ්‍රී ලංකා ක්‍රිකට් තරගාවලියේ අලුත් ම තත්ත්වය

=== Cluster 25 (3 articles) ===
- උත්සව සමයේ බිත්තර මිල අඩුවෙයිද?
- බිත්තරයක් රුපියල් 10කින් පහළට
- බේකරි නිෂ්පාදන මිල ගණන් ගැන තීරණයක්

=== Cluster 26 (10 articles) ===
- “සුරක්ෂා” රක්ෂණාවරණය යළි ඇරඹේ
- සුරක්ෂා රක්ෂණය යළිත් එයි
- 2026 වසරේ අධ්‍යාපනය සඳහා අයවැයෙන් යෝජිත මුදල් බෙදී යන්නේ මෙහෙමයි
- රුහුණේ සම සෞඛ්‍ය විද්‍යාපීඨයේ ගැටලුව පාර්ලිමේන්තුවට යයි
- හෘදපෙනහළු වෘත්තිකයින්හට පළමු වරට හෘදපෙනහළු නිවේශණය පිළිබඳ උසස් ඩිප්ලෝමා පාඨමාලාවක්
- 2026 අයවැයෙන් සෞඛ්‍ය සඳහා මුදල් වෙන් කිරීමට යෝජනා කර ඇත්තේ මෙහෙමයි
- තවත් කොටසකට රු 6000ක දීමනාව ලැබෙයි
- සරසවි ඇදුරෝ රතු එළි දල්වති
- අග්නිදිග සරසවි සිසුන් 125ක් ආපනශාලාවක රැය පහන් කරයි
- වයඹ සරසවි වෙද සිසුන්ට ඉන්න තැනක් හදයි

=== Cluster 27 (6 articles) ===
- හඳුනානොගත් රෝයකින් වී වගාව විනාශ වෙයි
- ඉඟුරු හා කහ වගාව රක්ෂණය කරයි
- කරාඹු වැටුනාට වන්දි ඉල්ලයි
- කිරි - වී ගොවි හබේකට ගවයන් 22 ක් කපලා
- කුඹුරු අක්කර 10000ක් විනාශයි
- අලවර්ග හා එළවළු වෙනුවෙන් රක්ෂණයක්

=== Cluster 28 (3 articles) ===
- පේරේ මුහුණ දුන් තත්ත්වය උප කුලපති කියයි
- ජල ගැල්මෙන් පේරාදෙණිය  සරසවියට කෝටි 300ක පාඩුවක්
- ජලයට කොටූ  පේරේ සිසුන් දුෂ්කරතාවන්ට

=== Cluster 29 (6 articles) ===
- ආණ්ඩුවේ මැති ඇමැතිවරුන් කිහිප දෙනෙකුට CID යන්න වුණේ ඇයි?
- පැය දෙක හමාරකට පසුව නාමල් CIDයෙන් පිටව යයි
- හම්බන්තොට නියෝජ්‍ය නගරාධිපති අත්අඩංගුවට
- නාමල්ගේ වරෙන්තුව ආපසු කැඳවයි
- බැඳුම්කර වංචාව ගැන පරීක්ෂණ ඇරඹෙයි
- හිටපු කැබිනට් අමාත්‍යවරුන් කිහිප දෙනෙක් සි.අයි.ඩී.ය හමුවට පැමිණෙයි

=== Cluster 30 (3 articles) ===
- ඩෙංගු රෝගින්ගේ ශීඝ්‍ර පහළ යාමක්
- ඩෙංගු වැඩිවීමේ අවධානමක්
- මාස තුනක් ඇතුළත වැඩිම ඩෙංගු රෝගීන් ගෙවුණු දින 25 තුළදී

=== Cluster 31 (9 articles) ===
- ඉන්දියාවට ගිය අනුර විශේෂ හමුවක
- අනුර හා ජපාන විදේශ රාජ්‍ය ඇමති අතර හමුවක්
- ජනපතිගේ ජපාන සංචාරයෙන් ශ්‍රී ලංකාවට ලැබෙන්නේ මොනවා ද?
- ජපාන අගමැති ෂිගේරු ඉෂිබා ඉල්ලා අස්වෙයි
- වෙනස්කම්වලට සාපේක්ෂව වෙනස් වූ බව NPP කියයි
- රුවන් -එ,ජා නේවාසික සම්බන්ධීකාරක හමුවක්
- නිර්-තාර්කික විදේශ ප්‍රතිපත්තිය
- අනියම් ඇසුරක් නිසා ජපාන රූ රැජිනට කිරුළ අහිමි වෙයි
- ජනපති ජපාන -ශ්‍රී ලංකා ව්‍යාපාරික සංසදය අමතයි

=== Cluster 32 (3 articles) ===
- කැනඩා රැකියා සිහින පෙන්වූ ජාවාරම්කරුවෝ
- රුමේනියා රැකියා පෙන්වා මුදල් වංචා කළ සහකාර කළමනාකරුවකු අල්ලයි
- රට රස්සා දෙනවා කියා කෝටි 74 කට පොලු

=== Cluster 33 (7 articles) ===
- පොළොන්නරු - මඩකළපුව මාර්ගය ගල්ලෑල්ලෙන් යටවෙයි
- පොළොන්නරුව - මඩකළපුව දුම්රිය මාර්ගගයටත් දැඩි හානි
- වෙළදසැලක සිරවී සිටි පිරිසක් බේරා ගැනෙති
- ගම්පොළ නුවරඑළිය ප්‍රධාන මාර්ගය තාවකාලිකව වහයි
- කලාඔයේ සිර වී සිටි 40ක්  බේරා ගැනෙති
- මහියංගණය රෝහල යථා තත්වයට
- මහවැලිය පිටාර ගලයි:සෝමාවතිය පාර වහයි

=== Cluster 34 (2 articles) ===
- අතුරුදන්වූවන්ගේ ඥාතීන්ගේ විරෝධතාවට වසර 7: 'ජාත්‍යන්තර විමර්ශනයක් අවශ්‍යයයි'
- 2000 වසරට පෙර අතුරුදන් වූවන් ගැන විමර්ශන යළි අරඹයි

=== Cluster 35 (9 articles) ===
- විවාහ ගිවිසගත් පෙම්වතා පැදවූ වෑන් රිය තුළම අවසන් ගමන් ගිය සඳමාලි
- කැබ් රථයක් ට්‍රැක්ටරයක ගැටීමෙන් දෙදෙනෙක් මරුට, පහකට තුවාල
- මොනරාගල වැලියායේදී බස් රථ දෙකක් ගැටී පුද්ගලයෙක් මරුට, 21ට තුවාල
- මාන්කුලමේ බිහිසුණු අනතුරක්
- රිය අනතුරින් තිදෙනකු මරුට
- බස් රථ හා වෑන් රථ අනතුරකින් තිදෙනෙක් මරුට
- බලන්ගොඩ ඇල්ලෙපොලදී බස් රථ 3ක් එකට ගැටේ
- මව සහ පුතු අනතුරින් මරුට
- බදුල්ලේ මාරක අනතුරක්

=== Cluster 36 (6 articles) ===
- යක්කලදී ගිලා බැස්ස පාලම ප්‍රතිසංස්කරණය කරයි
- දිට්වා: 'ධාවනය වෙමින් තිබූ දුම්රිය නතර කරන්න ගත් හදිසි තීරණයෙන් විශාල අනතුරක් වළක්වා ගන්න ලැබුණා'
- බදුල්ල - අඹේවෙල අතර දුම්රිය ගමන් අරඹයි
- කොළඹ සිට නුවරට සහ බදුල්ලට නැවත දුම්රියෙන් යන්න හැකිවෙන්නේ කවදා ද? නියෝජ්‍ය ඇමති ප්‍රසන්නගෙන් පිළිතුරක්
- බදුල්ලේ සිට නානුඔයට මසක් ඇතුළත දුම්රිය
- නානුඔයට මහ වැසි

=== Cluster 37 (6 articles) ===
- දෙවන අවසන් පූර්ව තරගයට වැස්සෙන් බාධා
- කාසියේ වාසිය කොදෙව් කණ්ඩායමට
- කාසියේ වාසිය ශ්‍රී ලංකාවට
- කාසියේ වාසිය බංග්ලාදේශයට
- කාසියේ වාසිය පාකිස්තානයට
- කාසියේ වාසිය ශ්‍රී ලංකාවට - නුවනිදුට සහ දුෂාන්ට T20 වරම්

=== Cluster 38 (9 articles) ===
- නිලන්තව සේවයෙන් නෙරපීම ගැන කතෝලික සභාවේ ස්ථාවරය කියයි
- පාස්කු වන්දි ගෙවීමට මෛත්‍රීට ඇතුළු පිරිසට අධිකරණයෙන් දින දෙයි
- මෛත්‍රීගේ ප්‍රකාශය ගැන අධිකරණයේ මතය දැනුම්දෙයි
- ප්‍රංශ හිටපු ජනපතිට වසර පහක සිර දඩුවම්
- ලැබී ඇති පාස්කු වන්දි මුදල සම්බන්ධයෙන් අධිකරණයේදී හෙළිදරව්වක්
- පාස්කු ඉරිදා ප්‍රහාරය: හිටපු රාජ්‍ය බුද්ධි ප්‍රධානියා  වන්දි ගෙවා අවසන් කරයි
- මෛත්‍රීපාල සහ පූජිත පාස්කු ප්‍රහාර මූලික අයිතිවාසිකම් නඩුවෙන් මුදා හැරියේ ඇයි?
- PTA යටතේ අසාත් සාලි අත්අඩංගුවට ගැනීම නීතිවිරෝධී බවට ශ්‍රේෂ්ඨාධිකරණය තීන්දු කළේ ඇයි?
- මෛත්‍රීට එරෙහිව අල්ලස් කොමිසමට පැමිණිල්ලක්

=== Cluster 39 (3 articles) ===
- අනේ බුදු බණ එක්ක ජීවත් වෙච්ච දරුවා මගේ. මොනවා හිතෙන්න ඇද්ද?'
- මට දැන් ඕනේ මගේ දරුවන් මිහිදන් කරපු තැනට ගිහින් ඒ අයට මලක් පහනක් තියලා එන්න': කැනඩාවේදී දරුවන් සිව් දෙනෙකු සමග ඝාතනයට ලක් වූ දර්ශනීගේ මව බීබීසීයට කතා කරයි
- කැනඩාවේ ලාංකික පවුලක 6 මරාදාලා - ඝාතකයා පවුල සමගම සිටි අයෙක්

=== Cluster 40 (4 articles) ===
- හිරුණිකාට සහනයක්
- හිරුණිකා ප්‍රේමචන්ද්‍ර: ඇප මත මුදා හැරීමට කොළඹ මහාධිකරණයෙන් නියෝග
- අම්පිටියේ සුමන හිමිට  ඇප
- හිරුණිකාගේ ඉල්ලීමට නීතිපති ගෙන් විරෝධය ?

=== Cluster 41 (8 articles) ===
- ජේතවනාරාම ස්තූපයේ පිපිරුම් වැළැක්වීම සඳහා තාක්ෂණික පිළියම්
- සමෙහි තුවාල ඇතිවීම අවම කරන නව 'මෙට්ටයක්' : 'මේ නිර්මාණය සඳහා මූලික පදනම වුණේ මගේ සීයා අසනීප වීම නිසා මම දැකපු දේවල්'
- ආපදා රෝහල් ප්‍රතිස්ථාපනයට ලෝක සෞඛ්‍ය සංවිධානයෙන් රු. මි. 53 ක්
- මාතලේ පොදු පහසුකම් පද්ධති නැංවීමට යුද හමුදා සහාය
- විජය පුවත්පත් සමාගමට පරිසර සම්මාන පහක්
- යුද හමුදාවෙන් බහුවිධ වෛද්‍ය සායනයක්
- කාන්තාවන්ගෙන් සියයට 48ක් නියමිත ශරීර බරට වඩා වැඩියි
- ලෝක සෞඛ්‍ය සංවිධානය ලංකාවට ලොකු සහයක් දෙන බව කියයි

=== Cluster 42 (3 articles) ===
- සුබ නැකතට රට අනුරට දුන් අය විපතකට
- ආණ්ඩුව මැවූ දිව්‍යලෝකය කඩා වැටිලා
- මාලිමාවත් ගොවියා මංමුලා කළා

=== Cluster 43 (11 articles) ===
- මෙවර කුණාටු වඩාත් ප්‍රචණ්ඩකාරී වෙයි
- 2025 සිට ආර්ථික ස්ථායීතාව වෙනුවෙන් ශ්‍රී ලංකා මහ බැංකුව කරන්න යන දේ
- ශ්‍රී ලංකාවේ දුර්වල බදු ප්‍රතිපත්තිය දරුවන්ට අධ්‍යාපනය ලැබීමට ඇති අයිතියට බලපෑ බව හියුමන් රයිට්ස් වොච් වාර්තාවකින් අනාවරණය කරයි
- රු. 2000 නෝට්ටුව ගැන මහ බැංකුවෙන් දැනුම් දීමක්
- දුප්පත්කම දෙගුණයකින් වැඩි‌ වෙලා
- ලංකාව සෞදියට කරන අපනයන සියයට 19කින් ඉහළට
- රුපියල් මිලියන 168,000 ක භාණ්ඩාගාර බිල්පත් වෙන්දේසියක්
- ශ්‍රි ලංකාවේ සියයට 25ක් තවමත් දුප්පත්
- ශ්‍රී ලංකාවේ දළ නිල සංචිත ඩොලර් බිලියන 7 කඩඉම පසු කිරීමට නොහැකි වීමට හේතු
- දරු උපත් අඩුවීමෙන් ශ්‍රී ලංකාවේ ආර්ථිකයට වෙන්න යන දේ ගැන ඔබ දන්නවා ද?
- ආර්ථිකයේ ඉහළ ඔරොත්තුදීමේ හැකියාව පෙන්නුම් කරනවා

=== Cluster 44 (5 articles) ===
- එක්සත් රාජධානියේ කැරලිවලට මැදි වූ ලාංකිකයෙකුගේ අත්දැකීම
- පවුල් ජීවිත අවුල් කරන අසීමාන්තික මව-පුතු  බැඳීම
- සාරධර්ම නායයාමෙන් සමස්ත සමාජය බේරගනිමු
- වැඩිමල්කම යනු බාලයන්ට පහර දීමට ලැබුණු වරමක් ද?
- නයෝමි අමරසිරි: ‘මගී නෞකාවක පිරිමින්ගේ රස්සාවකට ගිය පළමු ශ්‍රී ලාංකික කත’

=== Cluster 45 (7 articles) ===
- රාජ්‍ය නිලධාරීන් 9ක් මැතිවරණ රාජකාරිවලින් ඉවත් කළේ ඇයි? ඔවුන්ට කුමක් වෙයි ද?
- ඡන්දෙ දවසේ මේවා තහනම්
- ජනමාධ්‍ය නිදහස හා අදහස් ප්‍රකාශ කිරීමේ නිදහස අපි පාලනය කරන්නේ නැහැ - සමන් ශ්‍රී රත්නායක
- මහ මැතිවරණයේදි ඡන්දය ප්‍රකාශ කිරීම අඩුවෙනවා
- මියන්මාර මැතිවරණ​යේ පළමු අධියරේ ඡන්ද විමසීම අවසන්
- ජනපතිවරණ දිනය මේ මස අවසානයේදී
- මහින්ද නිවස ඉදිරිපිට සිට ආරම්භ කළ විරෝධය

=== Cluster 46 (5 articles) ===
- දරුවන්ට ලිංගික අධ්‍යාපනය දෙන එකට විරුද්ධ වෙන්නේ ළමයි දැනුවත් වුණොත් තමන්ට අවාසි වෙයි කියල හිතන අය'
- ශ්‍රී ලංකාවේ රජයේ පාසල් දරුවන්ගෙන් 97%කට අහිමි වී ඇති ඉංග්‍රීසි මාධ්‍ය අධ්‍යාපනය
- ‘‘අපේ දරුවන්ට අශිලාචාර දේ උගන්වන්න එපා‘‘
- කාදිනල්තුමාගෙන්  අනිත්‍ය කතාවක්
- ජාත්‍යන්තර පාසල්  නියාමනය නොකිරීමෙන් 'දරුවන්ට ගැටලු රැසක්'; නියාමනය කිරීමට කළ යුත්තේ කුමක්ද?

=== Cluster 47 (2 articles) ===
- ජනපති ලේකම් හා මෙරට බ්‍රිතාන්‍ය මහකොමසාරිස් අතර හමුවක්
- ලංකාව යළි ගොඩනගන්න ප්‍රංශ සහය

=== Cluster 48 (9 articles) ===
- ආරක්ෂක අමාත්‍යාංශයෙන් නිවේදනයක්
- ධීවර විශ්‍රාම වැටුප යථාර්ථයක් වෙන හැඩ
- විශ්‍රාමික ත්‍රිවිධ හමුදා සාමාජිකයින්ට හා රණවිරු පවුල්වල අයට විදේශ රැකියා
- ජෙනරාල් ශවේන්ද්‍ර සිල්වා: 'මම විශ්‍රාම යන්නේ වැඩිම කාලයක් සේවයේ යෙදුණු හමුදා නිලධාරියා විදිහට'
- අලුත් යුද හමුදාපති සහ නාවික හමුදාපති කවුද?
- ජාතික ධීවර යාත්‍රා සංගණනය අගෝස්තු 20 දක්වා
- වෙදආරච්චි කළු ඇඳගෙන පාර්ලිමේන්තුවට
- ත්‍රිවිධ හමුදාව: සේවය හැරයන සාමාජිකයින් සමාජගත කිරීමට නිසි වැඩපිළිවෙලක් තිබේද?
- තලල්ල වෙරළ ජාත්‍යන්තරයට

=== Cluster 49 (4 articles) ===
- නාරම්මල වෙඩි තැබීමේ සිද්ධියේ SI යළි රක්ෂිත බන්ධනාගාරයට
- නාරම්මල පොලිස් වෙඩි තැබීම: සිවිල් ඇඳුමෙන් සැරසුණු පොලිස් නිලධාරියෙකුට සාමාන්‍ය වැසියෙකුට වෙඩි තැබිය හැකිද?
- බණ්ඩාරවත්තේ සිද්ධිය ගැන STF නිලධාරීන්ට අපරාධ චෝදනා එල්ල කිරීම සාක්ෂි නැහැ - නීතිපති
- නාරම්මල පොලිස් වෙඩි තැබීම: 'ලක්ෂ 10ක් දීලා අපි ගැන කිසිම දෙයක් හොයා බැලුවේ නැහැ'

=== Cluster 50 (6 articles) ===
- කෝටි 10ක් සොරාගත් සුරාබදු නිලධාරීන් පස්දෙනා රිමාන්ඩ්
- කෝටි 600 බදු පැහැර හැර ඇති මත්පැන් සමාගම් 10 ක ලැයිස්තුව ඔබ දන්නවාද?
- කොල්ලකෑමක් සම්බන්ධයෙන් සුරාබදු කෝප්‍රල්වරු දෙන්නෙක් අත්අඩංගුවට
- මෙන්ඩිස් සමාගමේ බලපත්‍රය අත්හිටුවයි
- කෝටි 10 ක් කොල්ල කෑවාට සුරාබදු කෝප්‍රල්වරු දෙකක් දැලේ
- රු. ලක්ෂ 14ක් කොල්ල කෑ බව කියන පොලිස් නිලධාරීන් හඳුනා ගැනිමේ පෙරට්ටුවකට

=== Cluster 51 (4 articles) ===
- කැළණිය විශ්වවිද්‍යාලයෙන් බෝතල් මූඩී බංකුවක් මරදානට
- කෙනෙරක් දුම්රියට බිලි
- වන අලි දුම්රියේ ගැටීම වැළැක්වීමට පේරාදෙණියෙන් කෘතීම බුද්ධිය සහිත කැමරාවක්
- පොලිස් වෙඩිල්ලෙන් පාරේ ගිය රාජා මරුට

=== Cluster 52 (5 articles) ===
- රු. කෝටි 22ක කොකේන් හා මත්පෙති සමග සැකකාරියක් අල්ලයි
- රස පරීක්ෂක කාර්යාලයේ කාර්ය සහයකයෙක් හෙරොයින් සහ අයිස් සමග අත්අඩංගුවට
- හෙරොයින් කිලෝ 1ක් සහ අයිස් මත්ද්‍රව්‍ය සමග පුද්ගලයෙක් අත්අඩංගුවට
- හාලි ඇල නිවසක් මතට කිලෝ පනහක පමණ අයිස් කුට්ටියක් වැටෙයි
- අයිස් කිලෝ 3ක් සමග දෙදෙනෙක් අත්අඩංගුවට

=== Cluster 53 (5 articles) ===
- ඊශ්‍රායල ජාතිකයින් විසින් සිදුකරන ඉදිකිරීම්වලට අවසර දීලා නැහැ - අගමැති
- ආරුගම්බේ ආරක්ෂක තර්ජනය ගැන ඇමති හෙළි කළ කරුණු
- ඔස්ට්‍රේලියාවේ ඉරාන තානාපතිට එරටින් පිටවන්නැයි දැනුම්දීමක්
- ආරුගම්බේ තර්ජනය සම්බන්ධයෙන් අප මෙතෙක් දන්නේ මොනවා ද?
- මම උදේ 3.30 වෙනකල් කෝල් ගත්තා,මැසේජ් දැම්මා; අනේ මොකද ෆෝන් එක බලන්නේ නැත්තේ කියලා'- ඊශ්‍රායලයේදී ඝාතනයට ලක් වූ තරිඳු ශානකගේ බිරිඳ

=== Cluster 54 (9 articles) ===
- අත්අඩංගුවට ගත් හරීන් ප්‍රනාන්දුට අධිකරණ දුන් තීන්දුව මෙන්න
- පුද්ගලයකුගේ දත් හතරක් කැඩූ ප්‍රා. මන්ත්‍රීට ඇප
- ශිවාජිලිංගම් රෝහල්ගත කෙරේ
- මට අද කොන්ද කෙලින් තියන් යන්න පුළුවන් - හරීන්
- අර්චුනා හඬා වැටෙයි
- අලි සබ්රි රහීම් ට ඇප
- හරීන්ට ඇප
- අර්චුනා කැබ් රථය  පිනට දෙයි
- මන්ත්‍රී අර්චුනාට ඇප

=== Cluster 55 (9 articles) ===
- චැනල් ෆෝ නාලිකාවට තොරතුරු දුන් විශ්‍රාමික නිලධාරියා කවුද ?
- පාස්කු වාර්තාව ගැන රනිල්ගෙන් ලියුමක්
- ගම්මන්පිලගේ හඬපටය ගැන වාර්තාවක් කැඳවයි
- ශානි අබේසේකර: යළි සේවයට කැඳවා ඇත්තේ ඇයි?
- මාලිමා ආණ්ඩුවේ විදෙස් ඇමති සුමන්තිරන්
- පාස්කු විමර්ශන කමිටු වාර්තාවක අන්තර්ගතය ගම්මන්පිල හෙළිකරයි
- ජනාධිපති කොමිෂන් සභාවලට ඉදිරිපත් වන සාක්ෂි පදනම් කරගෙන නඩු පැවරිය හැකි ද?
- මාලිමා දේශපාලනය පාසල් ඇතුළට රිංගවලා - ගම්මන්පිල
- නැගෙනහිර පළාතේ හඳුන්වා දෙන 'ජල්ලිකට්ටු' ක්‍රීඩාව ගැන ඔබ දන්නවා ද?

=== Cluster 56 (13 articles) ===
- වැසුණු කඩුගන්නාව යළි විවෘත කෙරේ
- අතුරුගිරිය හුවමාරුව ජලයෙන් යටවෙයි
- ගාලු පාරේ කොටසක් වැසෙයි
- අහස වසාගත් කළු දුමට හේතුව මෙන්න
- කඩුගන්නාව ගනේතැන්න මාර්ගය අදත් වසයි
- අලින්ට පාර මාරු වෙන්න අවුරුදු 10ක් ස්වේච්ඡාවෙන් උපකාර කරන ගැටදිවුලේ කුමාර
- කළුගල් කඩා වැටී කඩුගන්නාවෙන් පාර වැහේ
- තේ කර්මාන්තය සාමාන්‍ය පරිදි අරඹයි
- පුලිදෙ දත්ත පද්ධතිය යළිත් බිඳ වැටෙයි
- පානදුරෙන් ගාලුපාර අවහිර වෙයි
- කොළඹ - මහනුවර මාර්ගය කඩුගන්නැවෙන් වහයි
- කටුගස්තොට පාර වැහේ
- මාවිල්ආරු අමුණ තැන් කිහිපයකින් කැඩෙයි

=== Cluster 57 (2 articles) ===
- ඩිජිටල් සේවා බද්ද  පැනවීම කල් යයි
- ආදායම් බදු වාර්තා 30 පෙර ඕනෑ

=== Cluster 58 (8 articles) ===
- වැඩබලන දියවඩන නිලමේ පත්කිරීමට එරෙහි පෙත්සම සලකාබැලීමට දිනදෙයි
- ශ්‍රී දළදා මාලිගාවේ දියවඩන නිලමේ තෝරන නිලවරණය අද: 7 දෙනෙක් අතර තරගයක්
- පිටිපන ලෙල්ලම: කොළඹ අගරදගරු මැදුර සහ ධීවරයින් අතර ආරවුල කුමක් ද?
- මහනුවර ඇසළ පෙරහැරට බාධාවක්
- ඉන්දි රාජාට ලැබුණ වාසනාව
- නිලමේ තනතුරට හිමි කිසිම වරප්‍රසාදයක් භාවිත නොකරන බව දියවඩන නිලමේ අපේක්ෂක උඩුරාවණ කියයි
- ශ්‍රී දළදා ඇසළ පෙරහැර මංගල්‍යය 30වනදා සිට